[project]
name = "incan-rustc-driver"
version = "0.6.0-dev.7"
private = true

[dependencies]
incan_mir_plan = { loaf = "incan_mir_plan", path = "../../compiler/incan_mir_plan" }
incan_mir_lowering = { loaf = "incan_mir_lowering", path = "../../compiler/incan_mir_lowering" }

incan_driver = { loaf = "incan_driver", path = "../../compiler/incan_driver", default-features = false, features = ["cli", "rust_inspect", "std_async", "std_testing", "std_decorators"] }
thiserror = { loaf = "crates-io/thiserror", version = "2" }
sha2 = { loaf = "crates-io/sha2", version = "0.10.9" }
incan_semantics_core = { loaf = "incan_semantics_core", path = "../../kernel/incan_semantics_core" }
incan_frontend = { loaf = "incan_frontend", path = "../../compiler/incan_frontend", default-features = false }

[[rust.bin]]
name = "incan-rustc-driver"
path = "src/main.rs"
unstable_features = ["rustc_private"]
toolchain_components = ["rustc-dev"]
sysroot_dependencies = ["rustc_driver"]
