//! @generated by `make behavior-roots` from the behavior-fixture area `execution_numerics_and_conversions`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/execution_numerics_and_conversions/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::{assert_fixture_holds, assert_pending_fixtures_still_wait};

/// The area every case of this root runs a fixture of.
const AREA: &str = "execution_numerics_and_conversions";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `a_nan_f64_passes_through_a_call`.
#[test]
fn a_nan_f64_passes_through_a_call() -> CaseResult {
    assert_fixture_holds(AREA, "a_nan_f64_passes_through_a_call")
}

/// Runs the fixture `aliases_normalize_to_canonical_numeric_carriers`.
#[test]
fn aliases_normalize_to_canonical_numeric_carriers() -> CaseResult {
    assert_fixture_holds(AREA, "aliases_normalize_to_canonical_numeric_carriers")
}

/// Runs the fixture `aliases_normalize_to_canonical_numeric_carriers_2`.
#[test]
fn aliases_normalize_to_canonical_numeric_carriers_2() -> CaseResult {
    assert_fixture_holds(AREA, "aliases_normalize_to_canonical_numeric_carriers_2")
}

/// Runs the fixture `checked_source_float_parameters_and_defaults_remain_internal_values`.
#[test]
fn checked_source_float_parameters_and_defaults_remain_internal_values() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "checked_source_float_parameters_and_defaults_remain_internal_values",
    )
}

/// Runs the fixture `checked_widening_of_f32_to_f64_and_float`.
#[test]
fn checked_widening_of_f32_to_f64_and_float() -> CaseResult {
    assert_fixture_holds(AREA, "checked_widening_of_f32_to_f64_and_float")
}

/// Runs the fixture `checked_widening_of_u8_to_u16_through_assignment_and_call`.
#[test]
fn checked_widening_of_u8_to_u16_through_assignment_and_call() -> CaseResult {
    assert_fixture_holds(AREA, "checked_widening_of_u8_to_u16_through_assignment_and_call")
}

/// Runs the fixture `cli_executes_unchanged_type_conversions_with_receipt`.
#[test]
fn cli_executes_unchanged_type_conversions_with_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_executes_unchanged_type_conversions_with_receipt")
}

/// Runs the fixture `contextual_negative_literals_survive_direct_returns_and_same_module_ca`.
#[test]
fn contextual_negative_literals_survive_direct_returns_and_same_module_ca() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "contextual_negative_literals_survive_direct_returns_and_same_module_ca",
    )
}

/// Runs the fixture `contextual_negative_literals_survive_direct_returns_and_same_module_ca_2`.
#[test]
fn contextual_negative_literals_survive_direct_returns_and_same_module_ca_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "contextual_negative_literals_survive_direct_returns_and_same_module_ca_2",
    )
}

/// Runs the fixture `contextual_negative_literals_survive_direct_returns_and_same_module_ca_3`.
#[test]
#[ignore = "pending: the legacy route prints a whole-number f32 without its `.0`; the direct route (#1337 stage 4)"]
fn contextual_negative_literals_survive_direct_returns_and_same_module_ca_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "contextual_negative_literals_survive_direct_returns_and_same_module_ca_3",
    )
}

/// Runs the fixture `contextual_negative_literals_survive_direct_returns_and_same_module_ca_4`.
#[test]
fn contextual_negative_literals_survive_direct_returns_and_same_module_ca_4() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "contextual_negative_literals_survive_direct_returns_and_same_module_ca_4",
    )
}

/// Runs the fixture `every_admitted_scalar_conversion_pair_matches_the_native_route`.
#[test]
fn every_admitted_scalar_conversion_pair_matches_the_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "every_admitted_scalar_conversion_pair_matches_the_native_route")
}

/// Runs the fixture `executes_checked_typed_numeric_locals_through_selected_scalar_conversi`.
#[test]
fn executes_checked_typed_numeric_locals_through_selected_scalar_conversi() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_checked_typed_numeric_locals_through_selected_scalar_conversi",
    )
}

/// Runs the fixture `executes_checked_typed_numeric_locals_through_selected_scalar_conversi_2`.
#[test]
fn executes_checked_typed_numeric_locals_through_selected_scalar_conversi_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_checked_typed_numeric_locals_through_selected_scalar_conversi_2",
    )
}

/// Runs the fixture `executes_checked_typed_numeric_locals_through_selected_scalar_conversi_3`.
#[test]
fn executes_checked_typed_numeric_locals_through_selected_scalar_conversi_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_checked_typed_numeric_locals_through_selected_scalar_conversi_3",
    )
}

/// Runs the fixture `executes_checked_typed_numeric_locals_through_selected_scalar_conversi_4`.
#[test]
fn executes_checked_typed_numeric_locals_through_selected_scalar_conversi_4() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_checked_typed_numeric_locals_through_selected_scalar_conversi_4",
    )
}

/// Runs the fixture `executes_checked_unary_scalar_conversions`.
#[test]
fn executes_checked_unary_scalar_conversions() -> CaseResult {
    assert_fixture_holds(AREA, "executes_checked_unary_scalar_conversions")
}

/// Runs the fixture `float_parameter_default_renders_through_str`.
#[test]
fn float_parameter_default_renders_through_str() -> CaseResult {
    assert_fixture_holds(AREA, "float_parameter_default_renders_through_str")
}

/// Runs the fixture `float_parser_and_int_cast_edges_match_the_native_route`.
#[test]
fn float_parser_and_int_cast_edges_match_the_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "float_parser_and_int_cast_edges_match_the_native_route")
}

/// Runs the fixture `keeps_same_spelled_source_scalar_callables`.
#[test]
fn keeps_same_spelled_source_scalar_callables() -> CaseResult {
    assert_fixture_holds(AREA, "keeps_same_spelled_source_scalar_callables")
}

/// Runs the fixture `keeps_same_spelled_source_scalar_callables_2`.
#[test]
fn keeps_same_spelled_source_scalar_callables_2() -> CaseResult {
    assert_fixture_holds(AREA, "keeps_same_spelled_source_scalar_callables_2")
}

/// Runs the fixture `keeps_same_spelled_source_scalar_callables_3`.
#[test]
fn keeps_same_spelled_source_scalar_callables_3() -> CaseResult {
    assert_fixture_holds(AREA, "keeps_same_spelled_source_scalar_callables_3")
}

/// Runs the fixture `normalizes_ordinary_float_literal_and_runtime_string_spelling`.
#[test]
fn normalizes_ordinary_float_literal_and_runtime_string_spelling() -> CaseResult {
    assert_fixture_holds(AREA, "normalizes_ordinary_float_literal_and_runtime_string_spelling")
}

/// Runs the fixture `ordinary_float_literal_display_matches_the_native_route`.
#[test]
fn ordinary_float_literal_display_matches_the_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "ordinary_float_literal_display_matches_the_native_route")
}

/// Runs the fixture `parity_scalar_conversions_print_and_return`.
#[test]
fn parity_scalar_conversions_print_and_return() -> CaseResult {
    assert_fixture_holds(AREA, "parity_scalar_conversions_print_and_return")
}

/// Runs the fixture `parity_typed_numeric_extremes_and_f32_return`.
#[test]
fn parity_typed_numeric_extremes_and_f32_return() -> CaseResult {
    assert_fixture_holds(AREA, "parity_typed_numeric_extremes_and_f32_return")
}

/// Runs the fixture `preserves_decimal_observation_without_entering_binary_float`.
#[test]
fn preserves_decimal_observation_without_entering_binary_float() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_decimal_observation_without_entering_binary_float")
}

/// Runs the fixture `preserves_float_direct_arguments_and_results`.
#[test]
fn preserves_float_direct_arguments_and_results() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_float_direct_arguments_and_results")
}

/// Runs the fixture `preserves_float_direct_arguments_and_results_2`.
#[test]
fn preserves_float_direct_arguments_and_results_2() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_float_direct_arguments_and_results_2")
}

/// Runs the fixture `preserves_typed_numeric_locals_and_display`.
#[test]
fn preserves_typed_numeric_locals_and_display() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_typed_numeric_locals_and_display")
}

/// Runs the fixture `preserves_typed_numeric_values_in_print_and_fstring_paths`.
#[test]
fn preserves_typed_numeric_values_in_print_and_fstring_paths() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_typed_numeric_values_in_print_and_fstring_paths")
}

/// Runs the fixture `preserves_typed_numeric_values_in_print_and_fstring_paths_2`.
#[test]
fn preserves_typed_numeric_values_in_print_and_fstring_paths_2() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_typed_numeric_values_in_print_and_fstring_paths_2")
}

/// Runs the fixture `preserves_typed_numeric_values_in_print_and_fstring_paths_3`.
#[test]
fn preserves_typed_numeric_values_in_print_and_fstring_paths_3() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_typed_numeric_values_in_print_and_fstring_paths_3")
}

/// Runs the fixture `preserves_typed_numeric_values_in_print_and_fstring_paths_4`.
#[test]
fn preserves_typed_numeric_values_in_print_and_fstring_paths_4() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_typed_numeric_values_in_print_and_fstring_paths_4")
}

/// Runs the fixture `preserves_typed_numeric_values_in_print_and_fstring_paths_5`.
#[test]
fn preserves_typed_numeric_values_in_print_and_fstring_paths_5() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_typed_numeric_values_in_print_and_fstring_paths_5")
}

/// Runs the fixture `refuses_float_debug_interpolation`.
#[test]
fn refuses_float_debug_interpolation() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_float_debug_interpolation")
}

/// Runs the fixture `refuses_nonfloat_carriers_supplied_to_a_float_entrypoint_parameter`.
#[test]
fn refuses_nonfloat_carriers_supplied_to_a_float_entrypoint_parameter() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_nonfloat_carriers_supplied_to_a_float_entrypoint_parameter",
    )
}

/// Runs the fixture `refuses_scalar_conversion_calls_missing_checked_builtin_identity`.
#[test]
fn refuses_scalar_conversion_calls_missing_checked_builtin_identity() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_scalar_conversion_calls_missing_checked_builtin_identity")
}

/// Runs the fixture `refuses_scalar_conversion_calls_missing_checked_builtin_identity_2`.
#[test]
fn refuses_scalar_conversion_calls_missing_checked_builtin_identity_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_scalar_conversion_calls_missing_checked_builtin_identity_2",
    )
}

/// Runs the fixture `refuses_scalar_conversion_calls_missing_checked_builtin_identity_3`.
#[test]
fn refuses_scalar_conversion_calls_missing_checked_builtin_identity_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_scalar_conversion_calls_missing_checked_builtin_identity_3",
    )
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans() -> CaseResult {
    assert_fixture_holds(AREA, "reports_canonical_scalar_parse_failures_at_original_call_spans")
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_2`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_2() -> CaseResult {
    assert_fixture_holds(AREA, "reports_canonical_scalar_parse_failures_at_original_call_spans_2")
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_2_2`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_2_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "reports_canonical_scalar_parse_failures_at_original_call_spans_2_2",
    )
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_3`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_3() -> CaseResult {
    assert_fixture_holds(AREA, "reports_canonical_scalar_parse_failures_at_original_call_spans_3")
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_3_2`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_3_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "reports_canonical_scalar_parse_failures_at_original_call_spans_3_2",
    )
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_4`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_4() -> CaseResult {
    assert_fixture_holds(AREA, "reports_canonical_scalar_parse_failures_at_original_call_spans_4")
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_4_legacy_route`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_4_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "reports_canonical_scalar_parse_failures_at_original_call_spans_4_legacy_route",
    )
}

/// Runs the fixture `reports_canonical_scalar_parse_failures_at_original_call_spans_5`.
#[test]
fn reports_canonical_scalar_parse_failures_at_original_call_spans_5() -> CaseResult {
    assert_fixture_holds(AREA, "reports_canonical_scalar_parse_failures_at_original_call_spans_5")
}

/// Runs the fixture `runtime_non_finite_float_values_flow_through_f64`.
#[test]
fn runtime_non_finite_float_values_flow_through_f64() -> CaseResult {
    assert_fixture_holds(AREA, "runtime_non_finite_float_values_flow_through_f64")
}

/// Runs the fixture `runtime_non_finite_float_values_flow_through_f64_2`.
#[test]
fn runtime_non_finite_float_values_flow_through_f64_2() -> CaseResult {
    assert_fixture_holds(AREA, "runtime_non_finite_float_values_flow_through_f64_2")
}

/// Runs the fixture `runtime_non_finite_float_values_flow_through_f64_3`.
#[test]
fn runtime_non_finite_float_values_flow_through_f64_3() -> CaseResult {
    assert_fixture_holds(AREA, "runtime_non_finite_float_values_flow_through_f64_3")
}

/// Runs the fixture `runtime_non_finite_float_values_flow_through_f64_4`.
#[test]
fn runtime_non_finite_float_values_flow_through_f64_4() -> CaseResult {
    assert_fixture_holds(AREA, "runtime_non_finite_float_values_flow_through_f64_4")
}

/// Runs the fixture `runtime_non_finite_float_values_flow_through_f64_5`.
#[test]
fn runtime_non_finite_float_values_flow_through_f64_5() -> CaseResult {
    assert_fixture_holds(AREA, "runtime_non_finite_float_values_flow_through_f64_5")
}

/// Runs the fixture `runtime_non_finite_float_values_flow_through_f64_6`.
#[test]
fn runtime_non_finite_float_values_flow_through_f64_6() -> CaseResult {
    assert_fixture_holds(AREA, "runtime_non_finite_float_values_flow_through_f64_6")
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_2`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_2",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_2_legacy_route`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_2_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_2_legacy_route",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_3`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_3",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_3_legacy_route`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_3_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_3_legacy_route",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_4`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_4() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_4",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_4_legacy_route`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_4_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_4_legacy_route",
    )
}

/// Runs the fixture `scalar_conversion_failures_keep_their_canonical_class_and_original_inp_legacy_route`.
#[test]
fn scalar_conversion_failures_keep_their_canonical_class_and_original_inp_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "scalar_conversion_failures_keep_their_canonical_class_and_original_inp_legacy_route",
    )
}

/// Runs the fixture `scalar_conversions_do_not_admit_float_binary_arithmetic`.
#[test]
fn scalar_conversions_do_not_admit_float_binary_arithmetic() -> CaseResult {
    assert_fixture_holds(AREA, "scalar_conversions_do_not_admit_float_binary_arithmetic")
}

/// Runs the fixture `scalar_conversions_do_not_admit_float_negation`.
#[test]
fn scalar_conversions_do_not_admit_float_negation() -> CaseResult {
    assert_fixture_holds(AREA, "scalar_conversions_do_not_admit_float_negation")
}

/// Runs the fixture `typed_decimal_value_keeps_its_scale_through_a_call`.
#[test]
fn typed_decimal_value_keeps_its_scale_through_a_call() -> CaseResult {
    assert_fixture_holds(AREA, "typed_decimal_value_keeps_its_scale_through_a_call")
}

/// Runs the fixture `typed_f32_entry_returns_its_argument`.
#[test]
fn typed_f32_entry_returns_its_argument() -> CaseResult {
    assert_fixture_holds(AREA, "typed_f32_entry_returns_its_argument")
}

/// Runs the fixture `typed_f32_value_keeps_its_carrier_through_a_call`.
#[test]
fn typed_f32_value_keeps_its_carrier_through_a_call() -> CaseResult {
    assert_fixture_holds(AREA, "typed_f32_value_keeps_its_carrier_through_a_call")
}

/// Runs the fixture `typed_integer_transport_and_cast_edges_match_the_native_route`.
#[test]
fn typed_integer_transport_and_cast_edges_match_the_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "typed_integer_transport_and_cast_edges_match_the_native_route")
}

/// Runs the fixture `typed_resize_methods_stay_named_non_green_under_issue_988`.
#[test]
fn typed_resize_methods_stay_named_non_green_under_issue_988() -> CaseResult {
    assert_fixture_holds(AREA, "typed_resize_methods_stay_named_non_green_under_issue_988")
}

/// Runs the fixture `typed_u128_value_keeps_its_carrier_through_a_call`.
#[test]
fn typed_u128_value_keeps_its_carrier_through_a_call() -> CaseResult {
    assert_fixture_holds(AREA, "typed_u128_value_keeps_its_carrier_through_a_call")
}

/// Runs the fixture `unsupported_typed_arithmetic_refuses_at_source_span_before_any_output`.
#[test]
fn unsupported_typed_arithmetic_refuses_at_source_span_before_any_output() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "unsupported_typed_arithmetic_refuses_at_source_span_before_any_output",
    )
}

/// Every `pending:` fixture of the area still does not show what it declares.
#[test]
fn pending_fixtures_still_wait() -> CaseResult {
    assert_pending_fixtures_still_wait(AREA)
}
