//! @generated by `make behavior-roots` from the behavior-fixture area `emit_calls_and_builtins`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/emit_calls_and_builtins/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "emit_calls_and_builtins";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `abs_and_sum_are_overflow_checked`.
#[test]
fn abs_and_sum_are_overflow_checked() -> CaseResult {
    assert_fixture_holds(AREA, "abs_and_sum_are_overflow_checked")
}

/// Runs the fixture `arguments_binding_one_type_parameter_widen_to_one_type`.
#[test]
fn arguments_binding_one_type_parameter_widen_to_one_type() -> CaseResult {
    assert_fixture_holds(AREA, "arguments_binding_one_type_parameter_widen_to_one_type")
}

/// Runs the fixture `await_through_a_module_binding`.
#[test]
fn await_through_a_module_binding() -> CaseResult {
    assert_fixture_holds(AREA, "await_through_a_module_binding")
}

/// Runs the fixture `bounded_type_arguments_the_call_settles_or_expects`.
#[test]
fn bounded_type_arguments_the_call_settles_or_expects() -> CaseResult {
    assert_fixture_holds(AREA, "bounded_type_arguments_the_call_settles_or_expects")
}

/// Runs the fixture `closure_parameters_from_their_context`.
#[test]
fn closure_parameters_from_their_context() -> CaseResult {
    assert_fixture_holds(AREA, "closure_parameters_from_their_context")
}

/// Runs the fixture `closures_returning_constructors_have_their_own_result`.
#[test]
fn closures_returning_constructors_have_their_own_result() -> CaseResult {
    assert_fixture_holds(AREA, "closures_returning_constructors_have_their_own_result")
}

/// Runs the fixture `collection_literals_of_constructors_share_one_result_type`.
#[test]
fn collection_literals_of_constructors_share_one_result_type() -> CaseResult {
    assert_fixture_holds(AREA, "collection_literals_of_constructors_share_one_result_type")
}

/// Runs the fixture `compiled_stdlib_module_function_call`.
#[test]
fn compiled_stdlib_module_function_call() -> CaseResult {
    assert_fixture_holds(AREA, "compiled_stdlib_module_function_call")
}

/// Runs the fixture `constructor_arguments_take_the_type_arguments_the_call_infers`.
#[test]
fn constructor_arguments_take_the_type_arguments_the_call_infers() -> CaseResult {
    assert_fixture_holds(AREA, "constructor_arguments_take_the_type_arguments_the_call_infers")
}

/// Runs the fixture `dev7_numeric_instantiation_concrete_model_fields`.
#[test]
fn dev7_numeric_instantiation_concrete_model_fields() -> CaseResult {
    assert_fixture_holds(AREA, "dev7_numeric_instantiation_concrete_model_fields")
}

/// Runs the fixture `dev7_numeric_instantiation_generic_equality`.
#[test]
fn dev7_numeric_instantiation_generic_equality() -> CaseResult {
    assert_fixture_holds(AREA, "dev7_numeric_instantiation_generic_equality")
}

/// Runs the fixture `dev7_numeric_instantiation_model_fields`.
#[test]
fn dev7_numeric_instantiation_model_fields() -> CaseResult {
    assert_fixture_holds(AREA, "dev7_numeric_instantiation_model_fields")
}

/// Runs the fixture `dict_literal_into_optional_union_values`.
#[test]
fn dict_literal_into_optional_union_values() -> CaseResult {
    assert_fixture_holds(AREA, "dict_literal_into_optional_union_values")
}

/// Runs the fixture `dict_lookups_with_str_keys`.
#[test]
fn dict_lookups_with_str_keys() -> CaseResult {
    assert_fixture_holds(AREA, "dict_lookups_with_str_keys")
}

/// Runs the fixture `enumerate_as_a_list_value_and_over_generic_tuples`.
#[test]
fn enumerate_as_a_list_value_and_over_generic_tuples() -> CaseResult {
    assert_fixture_holds(AREA, "enumerate_as_a_list_value_and_over_generic_tuples")
}

/// Runs the fixture `fallible_iterator_take`.
#[test]
fn fallible_iterator_take() -> CaseResult {
    assert_fixture_holds(AREA, "fallible_iterator_take")
}

/// Runs the fixture `file_builtins_report_errors_as_strings`.
#[test]
fn file_builtins_report_errors_as_strings() -> CaseResult {
    assert_fixture_holds(AREA, "file_builtins_report_errors_as_strings")
}

/// Runs the fixture `frozen_str_return_from_literal`.
#[test]
fn frozen_str_return_from_literal() -> CaseResult {
    assert_fixture_holds(AREA, "frozen_str_return_from_literal")
}

/// Runs the fixture `generic_list_of_tuples_literal_argument`.
#[test]
fn generic_list_of_tuples_literal_argument() -> CaseResult {
    assert_fixture_holds(AREA, "generic_list_of_tuples_literal_argument")
}

/// Runs the fixture `identifiers_named_like_host_keywords`.
#[test]
fn identifiers_named_like_host_keywords() -> CaseResult {
    assert_fixture_holds(AREA, "identifiers_named_like_host_keywords")
}

/// Runs the fixture `import_this_prints_the_zen`.
#[test]
fn import_this_prints_the_zen() -> CaseResult {
    assert_fixture_holds(AREA, "import_this_prints_the_zen")
}

/// Runs the fixture `isinstance_str_over_const_union_and_option`.
#[test]
fn isinstance_str_over_const_union_and_option() -> CaseResult {
    assert_fixture_holds(AREA, "isinstance_str_over_const_union_and_option")
}

/// Runs the fixture `iterator_adapters`.
#[test]
fn iterator_adapters() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_adapters")
}

/// Runs the fixture `iterator_terminals`.
#[test]
fn iterator_terminals() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_terminals")
}

/// Runs the fixture `list_index_remove_and_swap`.
#[test]
fn list_index_remove_and_swap() -> CaseResult {
    assert_fixture_holds(AREA, "list_index_remove_and_swap")
}

/// Runs the fixture `logical_operator_precedence`.
#[test]
fn logical_operator_precedence() -> CaseResult {
    assert_fixture_holds(AREA, "logical_operator_precedence")
}

/// Runs the fixture `match_arms_and_loop_values_share_one_type`.
#[test]
fn match_arms_and_loop_values_share_one_type() -> CaseResult {
    assert_fixture_holds(AREA, "match_arms_and_loop_values_share_one_type")
}

/// Runs the fixture `model_argument_beside_rest_parameter`.
#[test]
fn model_argument_beside_rest_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "model_argument_beside_rest_parameter")
}

/// Runs the fixture `open_result_sides_of_match_subjects_and_loop_iterables`.
#[test]
fn open_result_sides_of_match_subjects_and_loop_iterables() -> CaseResult {
    assert_fixture_holds(AREA, "open_result_sides_of_match_subjects_and_loop_iterables")
}

/// Runs the fixture `open_result_sides_take_the_enclosing_function_side`.
#[test]
fn open_result_sides_take_the_enclosing_function_side() -> CaseResult {
    assert_fixture_holds(AREA, "open_result_sides_take_the_enclosing_function_side")
}

/// Runs the fixture `ordinal_map_bytes_round_trip`.
#[test]
fn ordinal_map_bytes_round_trip() -> CaseResult {
    assert_fixture_holds(AREA, "ordinal_map_bytes_round_trip")
}

/// Runs the fixture `reflection_omits_private_fields`.
#[test]
fn reflection_omits_private_fields() -> CaseResult {
    assert_fixture_holds(AREA, "reflection_omits_private_fields")
}

/// Runs the fixture `result_combinator_closures_return_constructors`.
#[test]
fn result_combinator_closures_return_constructors() -> CaseResult {
    assert_fixture_holds(AREA, "result_combinator_closures_return_constructors")
}

/// Runs the fixture `result_observer_closures_take_their_payload`.
#[test]
fn result_observer_closures_take_their_payload() -> CaseResult {
    assert_fixture_holds(AREA, "result_observer_closures_take_their_payload")
}

/// Runs the fixture `slice_syntax_calls_the_getslice_hook`.
#[test]
fn slice_syntax_calls_the_getslice_hook() -> CaseResult {
    assert_fixture_holds(AREA, "slice_syntax_calls_the_getslice_hook")
}

/// Runs the fixture `static_method_with_str_argument`.
#[test]
fn static_method_with_str_argument() -> CaseResult {
    assert_fixture_holds(AREA, "static_method_with_str_argument")
}

/// Runs the fixture `std_fs_path_str_or_path_targets`.
#[test]
fn std_fs_path_str_or_path_targets() -> CaseResult {
    assert_fixture_holds(AREA, "std_fs_path_str_or_path_targets")
}

/// Runs the fixture `std_result_combinator_functions`.
#[test]
fn std_result_combinator_functions() -> CaseResult {
    assert_fixture_holds(AREA, "std_result_combinator_functions")
}

/// Runs the fixture `std_testing_assert_helpers`.
#[test]
fn std_testing_assert_helpers() -> CaseResult {
    assert_fixture_holds(AREA, "std_testing_assert_helpers")
}

/// Runs the fixture `stdlib_facade_import_utc`.
#[test]
fn stdlib_facade_import_utc() -> CaseResult {
    assert_fixture_holds(AREA, "stdlib_facade_import_utc")
}

/// Runs the fixture `struct_literals_in_condition_positions`.
#[test]
fn struct_literals_in_condition_positions() -> CaseResult {
    assert_fixture_holds(AREA, "struct_literals_in_condition_positions")
}

/// Runs the fixture `trait_adopted_through_module_binding`.
#[test]
fn trait_adopted_through_module_binding() -> CaseResult {
    assert_fixture_holds(AREA, "trait_adopted_through_module_binding")
}

/// Runs the fixture `type_parameter_values_where_a_bound_makes_them_the_expected_type`.
#[test]
fn type_parameter_values_where_a_bound_makes_them_the_expected_type() -> CaseResult {
    assert_fixture_holds(AREA, "type_parameter_values_where_a_bound_makes_them_the_expected_type")
}

/// Runs the fixture `union_parameter_call_returned_from_str_function`.
#[test]
fn union_parameter_call_returned_from_str_function() -> CaseResult {
    assert_fixture_holds(AREA, "union_parameter_call_returned_from_str_function")
}

/// Runs the fixture `user_method_named_join`.
#[test]
fn user_method_named_join() -> CaseResult {
    assert_fixture_holds(AREA, "user_method_named_join")
}
