//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_functions_and_projections`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_functions_and_projections/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_functions_and_projections";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `basic_function`.
#[test]
fn basic_function() -> CaseResult {
    assert_fixture_holds(AREA, "basic_function")
}

/// Runs the fixture `classmethod_with_explicit_type_arguments`.
#[test]
fn classmethod_with_explicit_type_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "classmethod_with_explicit_type_arguments")
}

/// Runs the fixture `cross_module_function_alias`.
#[test]
fn cross_module_function_alias() -> CaseResult {
    assert_fixture_holds(AREA, "cross_module_function_alias")
}

/// Runs the fixture `decorated_variadic_function`.
#[test]
fn decorated_variadic_function() -> CaseResult {
    assert_fixture_holds(AREA, "decorated_variadic_function")
}

/// Runs the fixture `decorator_factory_on_function_and_method`.
#[test]
fn decorator_factory_on_function_and_method() -> CaseResult {
    assert_fixture_holds(AREA, "decorator_factory_on_function_and_method")
}

/// Runs the fixture `derived_default_associated_function`.
#[test]
fn derived_default_associated_function() -> CaseResult {
    assert_fixture_holds(AREA, "derived_default_associated_function")
}

/// Runs the fixture `fixed_call_unpack`.
#[test]
fn fixed_call_unpack() -> CaseResult {
    assert_fixture_holds(AREA, "fixed_call_unpack")
}

/// Runs the fixture `function_alias_and_partial`.
#[test]
fn function_alias_and_partial() -> CaseResult {
    assert_fixture_holds(AREA, "function_alias_and_partial")
}

/// Runs the fixture `function_calls`.
#[test]
fn function_calls() -> CaseResult {
    assert_fixture_holds(AREA, "function_calls")
}

/// Runs the fixture `function_references`.
#[test]
fn function_references() -> CaseResult {
    assert_fixture_holds(AREA, "function_references")
}

/// Runs the fixture `functions`.
#[test]
fn functions() -> CaseResult {
    assert_fixture_holds(AREA, "functions")
}

/// Runs the fixture `method_alias_and_partial`.
#[test]
fn method_alias_and_partial() -> CaseResult {
    assert_fixture_holds(AREA, "method_alias_and_partial")
}

/// Runs the fixture `method_classmethod_staticmethod_property`.
#[test]
fn method_classmethod_staticmethod_property() -> CaseResult {
    assert_fixture_holds(AREA, "method_classmethod_staticmethod_property")
}

/// Runs the fixture `panic_function_name`.
#[test]
fn panic_function_name() -> CaseResult {
    assert_fixture_holds(AREA, "panic_function_name")
}

/// Runs the fixture `param_mut_unused`.
#[test]
fn param_mut_unused() -> CaseResult {
    assert_fixture_holds(AREA, "param_mut_unused")
}

/// Runs the fixture `power_operator_receivers`.
#[test]
fn power_operator_receivers() -> CaseResult {
    assert_fixture_holds(AREA, "power_operator_receivers")
}

/// Runs the fixture `public_model_static_method_and_property`.
#[test]
fn public_model_static_method_and_property() -> CaseResult {
    assert_fixture_holds(AREA, "public_model_static_method_and_property")
}

/// Runs the fixture `reexport_chain`.
#[test]
fn reexport_chain() -> CaseResult {
    assert_fixture_holds(AREA, "reexport_chain")
}

/// Runs the fixture `returns`.
#[test]
fn returns() -> CaseResult {
    assert_fixture_holds(AREA, "returns")
}

/// Runs the fixture `same_spelling_type_owned_and_instance_methods`.
#[test]
fn same_spelling_type_owned_and_instance_methods() -> CaseResult {
    assert_fixture_holds(AREA, "same_spelling_type_owned_and_instance_methods")
}

/// Runs the fixture `static_factory_named_like_field`.
#[test]
fn static_factory_named_like_field() -> CaseResult {
    assert_fixture_holds(AREA, "static_factory_named_like_field")
}

/// Runs the fixture `trait_method_and_adopted_default`.
#[test]
fn trait_method_and_adopted_default() -> CaseResult {
    assert_fixture_holds(AREA, "trait_method_and_adopted_default")
}

/// Runs the fixture `user_defined_decorators`.
#[test]
fn user_defined_decorators() -> CaseResult {
    assert_fixture_holds(AREA, "user_defined_decorators")
}

/// Runs the fixture `user_defined_method_decorators`.
#[test]
fn user_defined_method_decorators() -> CaseResult {
    assert_fixture_holds(AREA, "user_defined_method_decorators")
}

/// Runs the fixture `user_defined_mutable_method_decorator_replacement`.
#[test]
fn user_defined_mutable_method_decorator_replacement() -> CaseResult {
    assert_fixture_holds(AREA, "user_defined_mutable_method_decorator_replacement")
}

/// Runs the fixture `user_defined_mutable_method_decorators`.
#[test]
fn user_defined_mutable_method_decorators() -> CaseResult {
    assert_fixture_holds(AREA, "user_defined_mutable_method_decorators")
}

/// Runs the fixture `validated_newtype_hook_and_coercion`.
#[test]
fn validated_newtype_hook_and_coercion() -> CaseResult {
    assert_fixture_holds(AREA, "validated_newtype_hook_and_coercion")
}

/// Runs the fixture `variadic_calls`.
#[test]
fn variadic_calls() -> CaseResult {
    assert_fixture_holds(AREA, "variadic_calls")
}
