//! @generated by `make behavior-roots` from the behavior-fixture area `cli_refusals_mutation`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_refusals_mutation/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_refusals_mutation";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `refused_bare_tuple_swap_through_plain_self`.
#[test]
fn refused_bare_tuple_swap_through_plain_self() -> CaseResult {
    assert_fixture_holds(AREA, "refused_bare_tuple_swap_through_plain_self")
}

/// Runs the fixture `refused_change_through_a_parameter_not_marked_mut`.
#[test]
fn refused_change_through_a_parameter_not_marked_mut() -> CaseResult {
    assert_fixture_holds(AREA, "refused_change_through_a_parameter_not_marked_mut")
}

/// Runs the fixture `refused_change_through_a_pattern_binding_of_an_immutable_local`.
#[test]
fn refused_change_through_a_pattern_binding_of_an_immutable_local() -> CaseResult {
    assert_fixture_holds(AREA, "refused_change_through_a_pattern_binding_of_an_immutable_local")
}

/// Runs the fixture `refused_changing_call_through_a_let_binding`.
#[test]
fn refused_changing_call_through_a_let_binding() -> CaseResult {
    assert_fixture_holds(AREA, "refused_changing_call_through_a_let_binding")
}

/// Runs the fixture `refused_closure_changing_a_captured_local`.
#[test]
fn refused_closure_changing_a_captured_local() -> CaseResult {
    assert_fixture_holds(AREA, "refused_closure_changing_a_captured_local")
}

/// Runs the fixture `refused_field_write_through_a_let_binding`.
#[test]
fn refused_field_write_through_a_let_binding() -> CaseResult {
    assert_fixture_holds(AREA, "refused_field_write_through_a_let_binding")
}

/// Runs the fixture `refused_generator_changing_the_items_of_a_place`.
#[test]
fn refused_generator_changing_the_items_of_a_place() -> CaseResult {
    assert_fixture_holds(AREA, "refused_generator_changing_the_items_of_a_place")
}

/// Runs the fixture `refused_immutable_argument_changed_through_a_match_binding`.
#[test]
fn refused_immutable_argument_changed_through_a_match_binding() -> CaseResult {
    assert_fixture_holds(AREA, "refused_immutable_argument_changed_through_a_match_binding")
}

/// Runs the fixture `refused_immutable_argument_through_a_reassigned_function_local`.
#[test]
fn refused_immutable_argument_through_a_reassigned_function_local() -> CaseResult {
    assert_fixture_holds(AREA, "refused_immutable_argument_through_a_reassigned_function_local")
}

/// Runs the fixture `refused_immutable_argument_to_marked_parameter_of_a_callable_type`.
#[test]
fn refused_immutable_argument_to_marked_parameter_of_a_callable_type() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refused_immutable_argument_to_marked_parameter_of_a_callable_type",
    )
}

/// Runs the fixture `refused_immutable_argument_to_mut_parameter`.
#[test]
fn refused_immutable_argument_to_mut_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_immutable_argument_to_mut_parameter")
}

/// Runs the fixture `refused_immutable_argument_to_mut_parameter_changed_through_a_loop_variable`.
#[test]
fn refused_immutable_argument_to_mut_parameter_changed_through_a_loop_variable() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refused_immutable_argument_to_mut_parameter_changed_through_a_loop_variable",
    )
}

/// Runs the fixture `refused_immutable_argument_to_trait_dispatched_mut_parameter`.
#[test]
fn refused_immutable_argument_to_trait_dispatched_mut_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_immutable_argument_to_trait_dispatched_mut_parameter")
}

/// Runs the fixture `refused_immutable_generator_argument_to_mut_parameter`.
#[test]
fn refused_immutable_generator_argument_to_mut_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_immutable_generator_argument_to_mut_parameter")
}

/// Runs the fixture `refused_loop_changing_items_of_an_immutable_list`.
#[test]
fn refused_loop_changing_items_of_an_immutable_list() -> CaseResult {
    assert_fixture_holds(AREA, "refused_loop_changing_items_of_an_immutable_list")
}

/// Runs the fixture `refused_loop_changing_items_through_a_static_alias`.
#[test]
fn refused_loop_changing_items_through_a_static_alias() -> CaseResult {
    assert_fixture_holds(AREA, "refused_loop_changing_items_through_a_static_alias")
}

/// Runs the fixture `refused_mut_marked_function_for_unmarked_shape`.
#[test]
fn refused_mut_marked_function_for_unmarked_shape() -> CaseResult {
    assert_fixture_holds(AREA, "refused_mut_marked_function_for_unmarked_shape")
}

/// Runs the fixture `refused_mut_marker_on_int_parameter_of_function_type`.
#[test]
fn refused_mut_marker_on_int_parameter_of_function_type() -> CaseResult {
    assert_fixture_holds(AREA, "refused_mut_marker_on_int_parameter_of_function_type")
}

/// Runs the fixture `refused_mut_parameter_held_in_another_name_or_value`.
#[test]
fn refused_mut_parameter_held_in_another_name_or_value() -> CaseResult {
    assert_fixture_holds(AREA, "refused_mut_parameter_held_in_another_name_or_value")
}

/// Runs the fixture `refused_mutation_through_plain_self`.
#[test]
fn refused_mutation_through_plain_self() -> CaseResult {
    assert_fixture_holds(AREA, "refused_mutation_through_plain_self")
}

/// Runs the fixture `refused_partial_of_a_changing_method`.
#[test]
fn refused_partial_of_a_changing_method() -> CaseResult {
    assert_fixture_holds(AREA, "refused_partial_of_a_changing_method")
}

/// Runs the fixture `refused_rebinding_of_caller_visible_mut_parameter`.
#[test]
fn refused_rebinding_of_caller_visible_mut_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_rebinding_of_caller_visible_mut_parameter")
}
