//! @generated by `make behavior-roots` from the behavior-fixture area `cli_modules_and_declarations`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_modules_and_declarations/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_modules_and_declarations";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `aliased_builtin_bound_maps_to_rust_trait`.
#[test]
fn aliased_builtin_bound_maps_to_rust_trait() -> CaseResult {
    assert_fixture_holds(AREA, "aliased_builtin_bound_maps_to_rust_trait")
}

/// Runs the fixture `default_static_reads_across_modules`.
#[test]
fn default_static_reads_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "default_static_reads_across_modules")
}

/// Runs the fixture `error_adopter_displays_its_message`.
#[test]
fn error_adopter_displays_its_message() -> CaseResult {
    assert_fixture_holds(AREA, "error_adopter_displays_its_message")
}

/// Runs the fixture `external_impl_bound_reaches_a_generic_caller`.
#[test]
fn external_impl_bound_reaches_a_generic_caller() -> CaseResult {
    assert_fixture_holds(AREA, "external_impl_bound_reaches_a_generic_caller")
}

/// Runs the fixture `facade_reexport_alias_target`.
#[test]
fn facade_reexport_alias_target() -> CaseResult {
    assert_fixture_holds(AREA, "facade_reexport_alias_target")
}

/// Runs the fixture `facade_reexports_an_alias_without_its_target`.
#[test]
fn facade_reexports_an_alias_without_its_target() -> CaseResult {
    assert_fixture_holds(AREA, "facade_reexports_an_alias_without_its_target")
}

/// Runs the fixture `gen_named_function_field_and_module`.
#[test]
fn gen_named_function_field_and_module() -> CaseResult {
    assert_fixture_holds(AREA, "gen_named_function_field_and_module")
}

/// Runs the fixture `generic_caller_of_a_model_method_formatting_its_payload`.
#[test]
fn generic_caller_of_a_model_method_formatting_its_payload() -> CaseResult {
    assert_fixture_holds(AREA, "generic_caller_of_a_model_method_formatting_its_payload")
}

/// Runs the fixture `generic_callers_forwarding_to_generic_methods`.
#[test]
fn generic_callers_forwarding_to_generic_methods() -> CaseResult {
    assert_fixture_holds(AREA, "generic_callers_forwarding_to_generic_methods")
}

/// Runs the fixture `generic_list_index_without_clone_bound`.
#[test]
fn generic_list_index_without_clone_bound() -> CaseResult {
    assert_fixture_holds(AREA, "generic_list_index_without_clone_bound")
}

/// Runs the fixture `host_keyword_identifiers`.
#[test]
fn host_keyword_identifiers() -> CaseResult {
    assert_fixture_holds(AREA, "host_keyword_identifiers")
}

/// Runs the fixture `imported_static_decorator_receiver`.
#[test]
fn imported_static_decorator_receiver() -> CaseResult {
    assert_fixture_holds(AREA, "imported_static_decorator_receiver")
}

/// Runs the fixture `method_alias_calls_target`.
#[test]
fn method_alias_calls_target() -> CaseResult {
    assert_fixture_holds(AREA, "method_alias_calls_target")
}

/// Runs the fixture `method_called_through_a_helper_keeps_its_callees`.
#[test]
fn method_called_through_a_helper_keeps_its_callees() -> CaseResult {
    assert_fixture_holds(AREA, "method_called_through_a_helper_keeps_its_callees")
}

/// Runs the fixture `method_partial_over_model_method`.
#[test]
fn method_partial_over_model_method() -> CaseResult {
    assert_fixture_holds(AREA, "method_partial_over_model_method")
}

/// Runs the fixture `method_returning_a_later_declared_model`.
#[test]
fn method_returning_a_later_declared_model() -> CaseResult {
    assert_fixture_holds(AREA, "method_returning_a_later_declared_model")
}

/// Runs the fixture `model_field_of_newtype_over_str`.
#[test]
fn model_field_of_newtype_over_str() -> CaseResult {
    assert_fixture_holds(AREA, "model_field_of_newtype_over_str")
}

/// Runs the fixture `model_named_like_a_std_web_type`.
#[test]
fn model_named_like_a_std_web_type() -> CaseResult {
    assert_fixture_holds(AREA, "model_named_like_a_std_web_type")
}

/// Runs the fixture `module_derive_default_method_direct_call`.
#[test]
fn module_derive_default_method_direct_call() -> CaseResult {
    assert_fixture_holds(AREA, "module_derive_default_method_direct_call")
}

/// Runs the fixture `module_member_alias_beside_a_direct_import`.
#[test]
fn module_member_alias_beside_a_direct_import() -> CaseResult {
    assert_fixture_holds(AREA, "module_member_alias_beside_a_direct_import")
}

/// Runs the fixture `module_member_alias_calls_the_member`.
#[test]
fn module_member_alias_calls_the_member() -> CaseResult {
    assert_fixture_holds(AREA, "module_member_alias_calls_the_member")
}

/// Runs the fixture `namespace_prelude_imports`.
#[test]
fn namespace_prelude_imports() -> CaseResult {
    assert_fixture_holds(AREA, "namespace_prelude_imports")
}

/// Runs the fixture `partial_pattern_over_imported_private_field`.
#[test]
fn partial_pattern_over_imported_private_field() -> CaseResult {
    assert_fixture_holds(AREA, "partial_pattern_over_imported_private_field")
}

/// Runs the fixture `private_default_items_across_modules`.
#[test]
fn private_default_items_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "private_default_items_across_modules")
}

/// Runs the fixture `relative_import_from_a_nested_module`.
#[test]
fn relative_import_from_a_nested_module() -> CaseResult {
    assert_fixture_holds(AREA, "relative_import_from_a_nested_module")
}

/// Runs the fixture `same_named_default_consts_across_modules`.
#[test]
fn same_named_default_consts_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "same_named_default_consts_across_modules")
}

/// Runs the fixture `self_method_decorator_factory_and_direct_call`.
#[test]
fn self_method_decorator_factory_and_direct_call() -> CaseResult {
    assert_fixture_holds(AREA, "self_method_decorator_factory_and_direct_call")
}

/// Runs the fixture `set_of_rust_derived_hashable_model`.
#[test]
fn set_of_rust_derived_hashable_model() -> CaseResult {
    assert_fixture_holds(AREA, "set_of_rust_derived_hashable_model")
}

/// Runs the fixture `subtrait_default_and_class_override`.
#[test]
fn subtrait_default_and_class_override() -> CaseResult {
    assert_fixture_holds(AREA, "subtrait_default_and_class_override")
}

/// Runs the fixture `trait_default_constructs_module_type_across_modules`.
#[test]
fn trait_default_constructs_module_type_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_constructs_module_type_across_modules")
}

/// Runs the fixture `trait_default_generic_element_read_across_modules`.
#[test]
fn trait_default_generic_element_read_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_generic_element_read_across_modules")
}

/// Runs the fixture `trait_default_names_its_own_module_types`.
#[test]
fn trait_default_names_its_own_module_types() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_names_its_own_module_types")
}

/// Runs the fixture `trait_default_reaches_its_module_names_across_modules`.
#[test]
fn trait_default_reaches_its_module_names_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_reaches_its_module_names_across_modules")
}

/// Runs the fixture `user_model_named_field_info`.
#[test]
fn user_model_named_field_info() -> CaseResult {
    assert_fixture_holds(AREA, "user_model_named_field_info")
}

/// Runs the fixture `web_extractor_value_reads_the_payload`.
#[test]
fn web_extractor_value_reads_the_payload() -> CaseResult {
    assert_fixture_holds(AREA, "web_extractor_value_reads_the_payload")
}

/// Runs the fixture `web_html_response_type`.
#[test]
fn web_html_response_type() -> CaseResult {
    assert_fixture_holds(AREA, "web_html_response_type")
}
