//! @generated by `make behavior-roots` from the behavior-fixture area `cli_refusals`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_refusals/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_refusals";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `derived_display_beside_an_inherited_str`.
#[test]
fn derived_display_beside_an_inherited_str() -> CaseResult {
    assert_fixture_holds(AREA, "derived_display_beside_an_inherited_str")
}

/// Runs the fixture `json_stringify_of_a_value_without_serialize`.
#[test]
fn json_stringify_of_a_value_without_serialize() -> CaseResult {
    assert_fixture_holds(AREA, "json_stringify_of_a_value_without_serialize")
}

/// Runs the fixture `literal_pattern_where_no_literal_matches`.
#[test]
fn literal_pattern_where_no_literal_matches() -> CaseResult {
    assert_fixture_holds(AREA, "literal_pattern_where_no_literal_matches")
}

/// Runs the fixture `local_partial_of_a_generic_leaves_a_type_parameter_unfixed`.
#[test]
fn local_partial_of_a_generic_leaves_a_type_parameter_unfixed() -> CaseResult {
    assert_fixture_holds(AREA, "local_partial_of_a_generic_leaves_a_type_parameter_unfixed")
}

/// Runs the fixture `refused_annotated_chained_assignment`.
#[test]
fn refused_annotated_chained_assignment() -> CaseResult {
    assert_fixture_holds(AREA, "refused_annotated_chained_assignment")
}

/// Runs the fixture `refused_bare_collection_annotations`.
#[test]
fn refused_bare_collection_annotations() -> CaseResult {
    assert_fixture_holds(AREA, "refused_bare_collection_annotations")
}

/// Runs the fixture `refused_bare_tuple_annotation`.
#[test]
fn refused_bare_tuple_annotation() -> CaseResult {
    assert_fixture_holds(AREA, "refused_bare_tuple_annotation")
}

/// Runs the fixture `refused_bounded_model_built_over_a_bare_generic`.
#[test]
fn refused_bounded_model_built_over_a_bare_generic() -> CaseResult {
    assert_fixture_holds(AREA, "refused_bounded_model_built_over_a_bare_generic")
}

/// Runs the fixture `refused_callable_marker_over_two_parameters`.
#[test]
fn refused_callable_marker_over_two_parameters() -> CaseResult {
    assert_fixture_holds(AREA, "refused_callable_marker_over_two_parameters")
}

/// Runs the fixture `refused_debug_interpolation_of_a_generator`.
#[test]
fn refused_debug_interpolation_of_a_generator() -> CaseResult {
    assert_fixture_holds(AREA, "refused_debug_interpolation_of_a_generator")
}

/// Runs the fixture `refused_empty_list_at_two_list_members`.
#[test]
fn refused_empty_list_at_two_list_members() -> CaseResult {
    assert_fixture_holds(AREA, "refused_empty_list_at_two_list_members")
}

/// Runs the fixture `refused_float_argument_to_a_generic_dict_writer`.
#[test]
fn refused_float_argument_to_a_generic_dict_writer() -> CaseResult {
    assert_fixture_holds(AREA, "refused_float_argument_to_a_generic_dict_writer")
}

/// Runs the fixture `refused_generic_model_without_its_declared_bound`.
#[test]
fn refused_generic_model_without_its_declared_bound() -> CaseResult {
    assert_fixture_holds(AREA, "refused_generic_model_without_its_declared_bound")
}

/// Runs the fixture `refused_interpolated_union_value`.
#[test]
fn refused_interpolated_union_value() -> CaseResult {
    assert_fixture_holds(AREA, "refused_interpolated_union_value")
}

/// Runs the fixture `refused_json_model_with_a_decimal_field`.
#[test]
fn refused_json_model_with_a_decimal_field() -> CaseResult {
    assert_fixture_holds(AREA, "refused_json_model_with_a_decimal_field")
}

/// Runs the fixture `refused_kept_dict_lookup_of_a_generator`.
#[test]
fn refused_kept_dict_lookup_of_a_generator() -> CaseResult {
    assert_fixture_holds(AREA, "refused_kept_dict_lookup_of_a_generator")
}

/// Runs the fixture `refused_list_read_after_its_handles_were_awaited`.
#[test]
fn refused_list_read_after_its_handles_were_awaited() -> CaseResult {
    assert_fixture_holds(AREA, "refused_list_read_after_its_handles_were_awaited")
}

/// Runs the fixture `refused_literal_only_match_over_an_int`.
#[test]
fn refused_literal_only_match_over_an_int() -> CaseResult {
    assert_fixture_holds(AREA, "refused_literal_only_match_over_an_int")
}

/// Runs the fixture `refused_literal_pattern_of_another_type`.
#[test]
fn refused_literal_pattern_of_another_type() -> CaseResult {
    assert_fixture_holds(AREA, "refused_literal_pattern_of_another_type")
}

/// Runs the fixture `refused_loop_taking_task_handles_out_of_a_list_element`.
#[test]
fn refused_loop_taking_task_handles_out_of_a_list_element() -> CaseResult {
    assert_fixture_holds(AREA, "refused_loop_taking_task_handles_out_of_a_list_element")
}

/// Runs the fixture `refused_lossy_decimal_assignment`.
#[test]
fn refused_lossy_decimal_assignment() -> CaseResult {
    assert_fixture_holds(AREA, "refused_lossy_decimal_assignment")
}

/// Runs the fixture `refused_match_arms_of_two_types`.
#[test]
fn refused_match_arms_of_two_types() -> CaseResult {
    assert_fixture_holds(AREA, "refused_match_arms_of_two_types")
}

/// Runs the fixture `refused_match_leaving_a_payload_uncovered`.
#[test]
fn refused_match_leaving_a_payload_uncovered() -> CaseResult {
    assert_fixture_holds(AREA, "refused_match_leaving_a_payload_uncovered")
}

/// Runs the fixture `refused_method_decorator_calling_the_decorated_callable`.
#[test]
fn refused_method_decorator_calling_the_decorated_callable() -> CaseResult {
    assert_fixture_holds(AREA, "refused_method_decorator_calling_the_decorated_callable")
}

/// Runs the fixture `refused_method_decorator_from_another_module`.
#[test]
fn refused_method_decorator_from_another_module() -> CaseResult {
    assert_fixture_holds(AREA, "refused_method_decorator_from_another_module")
}

/// Runs the fixture `refused_method_decorator_replacement_passed_as_value`.
#[test]
fn refused_method_decorator_replacement_passed_as_value() -> CaseResult {
    assert_fixture_holds(AREA, "refused_method_decorator_replacement_passed_as_value")
}

/// Runs the fixture `refused_method_decorator_returning_a_closure`.
#[test]
fn refused_method_decorator_returning_a_closure() -> CaseResult {
    assert_fixture_holds(AREA, "refused_method_decorator_returning_a_closure")
}

/// Runs the fixture `refused_method_decorator_shape_through_alias`.
#[test]
fn refused_method_decorator_shape_through_alias() -> CaseResult {
    assert_fixture_holds(AREA, "refused_method_decorator_shape_through_alias")
}

/// Runs the fixture `refused_mixed_width_bitwise_operands`.
#[test]
fn refused_mixed_width_bitwise_operands() -> CaseResult {
    assert_fixture_holds(AREA, "refused_mixed_width_bitwise_operands")
}

/// Runs the fixture `refused_mixed_width_integer_arithmetic`.
#[test]
fn refused_mixed_width_integer_arithmetic() -> CaseResult {
    assert_fixture_holds(AREA, "refused_mixed_width_integer_arithmetic")
}

/// Runs the fixture `refused_model_field_holding_a_join_handle`.
#[test]
fn refused_model_field_holding_a_join_handle() -> CaseResult {
    assert_fixture_holds(AREA, "refused_model_field_holding_a_join_handle")
}

/// Runs the fixture `refused_module_path_import_of_a_private_declaration`.
#[test]
fn refused_module_path_import_of_a_private_declaration() -> CaseResult {
    assert_fixture_holds(AREA, "refused_module_path_import_of_a_private_declaration")
}

/// Runs the fixture `refused_modulo_on_type_parameter`.
#[test]
fn refused_modulo_on_type_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_modulo_on_type_parameter")
}

/// Runs the fixture `refused_named_argument_to_a_str_method`.
#[test]
fn refused_named_argument_to_a_str_method() -> CaseResult {
    assert_fixture_holds(AREA, "refused_named_argument_to_a_str_method")
}

/// Runs the fixture `refused_prelude_trait_imported_from_the_std_root`.
#[test]
fn refused_prelude_trait_imported_from_the_std_root() -> CaseResult {
    assert_fixture_holds(AREA, "refused_prelude_trait_imported_from_the_std_root")
}

/// Runs the fixture `refused_print_of_a_list_of_generators`.
#[test]
fn refused_print_of_a_list_of_generators() -> CaseResult {
    assert_fixture_holds(AREA, "refused_print_of_a_list_of_generators")
}

/// Runs the fixture `refused_print_of_model_without_str`.
#[test]
fn refused_print_of_model_without_str() -> CaseResult {
    assert_fixture_holds(AREA, "refused_print_of_model_without_str")
}

/// Runs the fixture `refused_public_method_decorator_replacement`.
#[test]
fn refused_public_method_decorator_replacement() -> CaseResult {
    assert_fixture_holds(AREA, "refused_public_method_decorator_replacement")
}

/// Runs the fixture `refused_python_import`.
#[test]
fn refused_python_import() -> CaseResult {
    assert_fixture_holds(AREA, "refused_python_import")
}

/// Runs the fixture `refused_reader_chunks_over_a_bare_generic`.
#[test]
fn refused_reader_chunks_over_a_bare_generic() -> CaseResult {
    assert_fixture_holds(AREA, "refused_reader_chunks_over_a_bare_generic")
}

/// Runs the fixture `refused_reserved_compiler_name_prefix`.
#[test]
fn refused_reserved_compiler_name_prefix() -> CaseResult {
    assert_fixture_holds(AREA, "refused_reserved_compiler_name_prefix")
}

/// Runs the fixture `refused_route_handler_returning_int`.
#[test]
fn refused_route_handler_returning_int() -> CaseResult {
    assert_fixture_holds(AREA, "refused_route_handler_returning_int")
}

/// Runs the fixture `refused_route_parameter_without_segment`.
#[test]
fn refused_route_parameter_without_segment() -> CaseResult {
    assert_fixture_holds(AREA, "refused_route_parameter_without_segment")
}

/// Runs the fixture `refused_route_payload_without_json_form`.
#[test]
fn refused_route_payload_without_json_form() -> CaseResult {
    assert_fixture_holds(AREA, "refused_route_payload_without_json_form")
}

/// Runs the fixture `refused_set_of_underived_enum`.
#[test]
fn refused_set_of_underived_enum() -> CaseResult {
    assert_fixture_holds(AREA, "refused_set_of_underived_enum")
}

/// Runs the fixture `refused_spawn_of_a_function_value`.
#[test]
fn refused_spawn_of_a_function_value() -> CaseResult {
    assert_fixture_holds(AREA, "refused_spawn_of_a_function_value")
}

/// Runs the fixture `refused_tuple_element_assignment`.
#[test]
fn refused_tuple_element_assignment() -> CaseResult {
    assert_fixture_holds(AREA, "refused_tuple_element_assignment")
}

/// Runs the fixture `refused_variant_pattern_with_too_few_sub_patterns`.
#[test]
fn refused_variant_pattern_with_too_few_sub_patterns() -> CaseResult {
    assert_fixture_holds(AREA, "refused_variant_pattern_with_too_few_sub_patterns")
}
