//! @generated by `make behavior-roots` from the behavior-fixture area `cli_logic_comparisons_and_patterns`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_logic_comparisons_and_patterns/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_logic_comparisons_and_patterns";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `decimal_values_compare_by_value`.
#[test]
fn decimal_values_compare_by_value() -> CaseResult {
    assert_fixture_holds(AREA, "decimal_values_compare_by_value")
}

/// Runs the fixture `list_count_and_index_forms`.
#[test]
fn list_count_and_index_forms() -> CaseResult {
    assert_fixture_holds(AREA, "list_count_and_index_forms")
}

/// Runs the fixture `match_payload_patterns_that_cover_together`.
#[test]
fn match_payload_patterns_that_cover_together() -> CaseResult {
    assert_fixture_holds(AREA, "match_payload_patterns_that_cover_together")
}

/// Runs the fixture `negation_keeps_its_operand_grouping`.
#[test]
fn negation_keeps_its_operand_grouping() -> CaseResult {
    assert_fixture_holds(AREA, "negation_keeps_its_operand_grouping")
}

/// Runs the fixture `nested_not_and_over_parameter_comparisons`.
#[test]
fn nested_not_and_over_parameter_comparisons() -> CaseResult {
    assert_fixture_holds(AREA, "nested_not_and_over_parameter_comparisons")
}

/// Runs the fixture `not_and_or_over_runtime_bool_operands`.
#[test]
fn not_and_or_over_runtime_bool_operands() -> CaseResult {
    assert_fixture_holds(AREA, "not_and_or_over_runtime_bool_operands")
}

/// Runs the fixture `not_and_over_parameter_comparisons`.
#[test]
fn not_and_over_parameter_comparisons() -> CaseResult {
    assert_fixture_holds(AREA, "not_and_over_parameter_comparisons")
}

/// Runs the fixture `not_or_over_parameter_comparisons`.
#[test]
fn not_or_over_parameter_comparisons() -> CaseResult {
    assert_fixture_holds(AREA, "not_or_over_parameter_comparisons")
}

/// Runs the fixture `numeric_widening_reaches_every_destination`.
#[test]
fn numeric_widening_reaches_every_destination() -> CaseResult {
    assert_fixture_holds(AREA, "numeric_widening_reaches_every_destination")
}

/// Runs the fixture `operator_precedence_follows_the_parser_ladder`.
#[test]
fn operator_precedence_follows_the_parser_ladder() -> CaseResult {
    assert_fixture_holds(AREA, "operator_precedence_follows_the_parser_ladder")
}

/// Runs the fixture `or_pattern_with_nested_str_literals`.
#[test]
fn or_pattern_with_nested_str_literals() -> CaseResult {
    assert_fixture_holds(AREA, "or_pattern_with_nested_str_literals")
}

/// Runs the fixture `record_patterns_over_generic_models_and_classes`.
#[test]
fn record_patterns_over_generic_models_and_classes() -> CaseResult {
    assert_fixture_holds(AREA, "record_patterns_over_generic_models_and_classes")
}
