//! @generated by `make behavior-roots` from the behavior-fixture area `execution_strings_and_output`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/execution_strings_and_output/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::{assert_fixture_holds, assert_pending_fixtures_still_wait};

/// The area every case of this root runs a fixture of.
const AREA: &str = "execution_strings_and_output";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `a_returned_string_keeps_its_trailing_newline`.
#[test]
fn a_returned_string_keeps_its_trailing_newline() -> CaseResult {
    assert_fixture_holds(AREA, "a_returned_string_keeps_its_trailing_newline")
}

/// Runs the fixture `both_backends_render_a_multi_argument_print_the_same_way`.
#[test]
fn both_backends_render_a_multi_argument_print_the_same_way() -> CaseResult {
    assert_fixture_holds(AREA, "both_backends_render_a_multi_argument_print_the_same_way")
}

/// Runs the fixture `canonical_string_comparisons_use_shared_unicode_order`.
#[test]
fn canonical_string_comparisons_use_shared_unicode_order() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_string_comparisons_use_shared_unicode_order")
}

/// Runs the fixture `canonical_string_comparisons_use_shared_unicode_order_2`.
#[test]
fn canonical_string_comparisons_use_shared_unicode_order_2() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_string_comparisons_use_shared_unicode_order_2")
}

/// Runs the fixture `canonical_string_comparisons_use_shared_unicode_order_3`.
#[test]
fn canonical_string_comparisons_use_shared_unicode_order_3() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_string_comparisons_use_shared_unicode_order_3")
}

/// Runs the fixture `canonical_string_comparisons_use_shared_unicode_order_4`.
#[test]
fn canonical_string_comparisons_use_shared_unicode_order_4() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_string_comparisons_use_shared_unicode_order_4")
}

/// Runs the fixture `canonical_string_comparisons_use_shared_unicode_order_5`.
#[test]
fn canonical_string_comparisons_use_shared_unicode_order_5() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_string_comparisons_use_shared_unicode_order_5")
}

/// Runs the fixture `canonical_string_comparisons_use_shared_unicode_order_6`.
#[test]
fn canonical_string_comparisons_use_shared_unicode_order_6() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_string_comparisons_use_shared_unicode_order_6")
}

/// Runs the fixture `canonical_string_membership_uses_the_selected_contains_helper_membership`.
#[test]
fn canonical_string_membership_uses_the_selected_contains_helper_membership() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "canonical_string_membership_uses_the_selected_contains_helper_membership",
    )
}

/// Runs the fixture `canonical_string_membership_uses_the_selected_contains_helper_membership_2`.
#[test]
fn canonical_string_membership_uses_the_selected_contains_helper_membership_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "canonical_string_membership_uses_the_selected_contains_helper_membership_2",
    )
}

/// Runs the fixture `canonical_string_membership_uses_the_selected_contains_helper_membership_3`.
#[test]
fn canonical_string_membership_uses_the_selected_contains_helper_membership_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "canonical_string_membership_uses_the_selected_contains_helper_membership_3",
    )
}

/// Runs the fixture `cli_reports_scalar_json_without_legacy_artifacts`.
#[test]
fn cli_reports_scalar_json_without_legacy_artifacts() -> CaseResult {
    assert_fixture_holds(AREA, "cli_reports_scalar_json_without_legacy_artifacts")
}

/// Runs the fixture `committed_strings_example_executes_with_ordinary_output`.
#[test]
fn committed_strings_example_executes_with_ordinary_output() -> CaseResult {
    assert_fixture_holds(AREA, "committed_strings_example_executes_with_ordinary_output")
}

/// Runs the fixture `concatenation_leaves_both_operands_usable`.
#[test]
fn concatenation_leaves_both_operands_usable() -> CaseResult {
    assert_fixture_holds(AREA, "concatenation_leaves_both_operands_usable")
}

/// Runs the fixture `concatenation_result_iterates_from_the_start`.
#[test]
fn concatenation_result_iterates_from_the_start() -> CaseResult {
    assert_fixture_holds(AREA, "concatenation_result_iterates_from_the_start")
}

/// Runs the fixture `dispatches_a_lexical_json_stringify_function_by_declaration_identity`.
#[test]
fn dispatches_a_lexical_json_stringify_function_by_declaration_identity() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "dispatches_a_lexical_json_stringify_function_by_declaration_identity",
    )
}

/// Runs the fixture `executes_dict_membership_with_a_hashed_value`.
#[test]
fn executes_dict_membership_with_a_hashed_value() -> CaseResult {
    assert_fixture_holds(AREA, "executes_dict_membership_with_a_hashed_value")
}

/// Runs the fixture `executes_f_string_interpolation`.
#[test]
fn executes_f_string_interpolation() -> CaseResult {
    assert_fixture_holds(AREA, "executes_f_string_interpolation")
}

/// Runs the fixture `executes_json_stringify_for_the_admitted_scalar_domain`.
#[test]
fn executes_json_stringify_for_the_admitted_scalar_domain() -> CaseResult {
    assert_fixture_holds(AREA, "executes_json_stringify_for_the_admitted_scalar_domain")
}

/// Runs the fixture `executes_json_stringify_for_the_admitted_scalar_domain_2`.
#[test]
fn executes_json_stringify_for_the_admitted_scalar_domain_2() -> CaseResult {
    assert_fixture_holds(AREA, "executes_json_stringify_for_the_admitted_scalar_domain_2")
}

/// Runs the fixture `executes_json_stringify_for_the_admitted_scalar_domain_3`.
#[test]
fn executes_json_stringify_for_the_admitted_scalar_domain_3() -> CaseResult {
    assert_fixture_holds(AREA, "executes_json_stringify_for_the_admitted_scalar_domain_3")
}

/// Runs the fixture `executes_json_stringify_for_the_admitted_scalar_domain_4`.
#[test]
fn executes_json_stringify_for_the_admitted_scalar_domain_4() -> CaseResult {
    assert_fixture_holds(AREA, "executes_json_stringify_for_the_admitted_scalar_domain_4")
}

/// Runs the fixture `executes_list_concatenation_and_membership`.
#[test]
fn executes_list_concatenation_and_membership() -> CaseResult {
    assert_fixture_holds(AREA, "executes_list_concatenation_and_membership")
}

/// Runs the fixture `executes_print_by_recording_its_output`.
#[test]
fn executes_print_by_recording_its_output() -> CaseResult {
    assert_fixture_holds(AREA, "executes_print_by_recording_its_output")
}

/// Runs the fixture `global_len_str_executes_unicode_scalar_rows_length`.
#[test]
fn global_len_str_executes_unicode_scalar_rows_length() -> CaseResult {
    assert_fixture_holds(AREA, "global_len_str_executes_unicode_scalar_rows_length")
}

/// Runs the fixture `global_len_str_executes_unicode_scalar_rows_length_2`.
#[test]
fn global_len_str_executes_unicode_scalar_rows_length_2() -> CaseResult {
    assert_fixture_holds(AREA, "global_len_str_executes_unicode_scalar_rows_length_2")
}

/// Runs the fixture `global_len_str_executes_unicode_scalar_rows_length_3`.
#[test]
fn global_len_str_executes_unicode_scalar_rows_length_3() -> CaseResult {
    assert_fixture_holds(AREA, "global_len_str_executes_unicode_scalar_rows_length_3")
}

/// Runs the fixture `global_len_str_executes_unicode_scalar_rows_length_4`.
#[test]
fn global_len_str_executes_unicode_scalar_rows_length_4() -> CaseResult {
    assert_fixture_holds(AREA, "global_len_str_executes_unicode_scalar_rows_length_4")
}

/// Runs the fixture `global_len_str_executes_unicode_scalar_rows_length_5`.
#[test]
fn global_len_str_executes_unicode_scalar_rows_length_5() -> CaseResult {
    assert_fixture_holds(AREA, "global_len_str_executes_unicode_scalar_rows_length_5")
}

/// Runs the fixture `iterates_any_list_of_representable_elements`.
#[test]
fn iterates_any_list_of_representable_elements() -> CaseResult {
    assert_fixture_holds(AREA, "iterates_any_list_of_representable_elements")
}

/// Runs the fixture `iterates_any_list_of_representable_elements_2`.
#[test]
fn iterates_any_list_of_representable_elements_2() -> CaseResult {
    assert_fixture_holds(AREA, "iterates_any_list_of_representable_elements_2")
}

/// Runs the fixture `iterates_any_list_of_representable_elements_3`.
#[test]
fn iterates_any_list_of_representable_elements_3() -> CaseResult {
    assert_fixture_holds(AREA, "iterates_any_list_of_representable_elements_3")
}

/// Runs the fixture `iterates_any_list_of_representable_elements_4`.
#[test]
fn iterates_any_list_of_representable_elements_4() -> CaseResult {
    assert_fixture_holds(AREA, "iterates_any_list_of_representable_elements_4")
}

/// Runs the fixture `iterates_any_list_of_representable_elements_5`.
#[test]
fn iterates_any_list_of_representable_elements_5() -> CaseResult {
    assert_fixture_holds(AREA, "iterates_any_list_of_representable_elements_5")
}

/// Runs the fixture `json_report_file_preserves_program_stdout`.
#[test]
fn json_report_file_preserves_program_stdout() -> CaseResult {
    assert_fixture_holds(AREA, "json_report_file_preserves_program_stdout")
}

/// Runs the fixture `json_stringify_evaluates_its_operand_once`.
#[test]
fn json_stringify_evaluates_its_operand_once() -> CaseResult {
    assert_fixture_holds(AREA, "json_stringify_evaluates_its_operand_once")
}

/// Runs the fixture `lexical_len_shadow_executes_the_user_declaration`.
#[test]
fn lexical_len_shadow_executes_the_user_declaration() -> CaseResult {
    assert_fixture_holds(AREA, "lexical_len_shadow_executes_the_user_declaration")
}

/// Runs the fixture `method_len_str_executes_unicode_scalar_rows_length`.
#[test]
fn method_len_str_executes_unicode_scalar_rows_length() -> CaseResult {
    assert_fixture_holds(AREA, "method_len_str_executes_unicode_scalar_rows_length")
}

/// Runs the fixture `method_len_str_executes_unicode_scalar_rows_length_2`.
#[test]
fn method_len_str_executes_unicode_scalar_rows_length_2() -> CaseResult {
    assert_fixture_holds(AREA, "method_len_str_executes_unicode_scalar_rows_length_2")
}

/// Runs the fixture `method_len_str_executes_unicode_scalar_rows_length_3`.
#[test]
fn method_len_str_executes_unicode_scalar_rows_length_3() -> CaseResult {
    assert_fixture_holds(AREA, "method_len_str_executes_unicode_scalar_rows_length_3")
}

/// Runs the fixture `method_len_str_executes_unicode_scalar_rows_length_4`.
#[test]
fn method_len_str_executes_unicode_scalar_rows_length_4() -> CaseResult {
    assert_fixture_holds(AREA, "method_len_str_executes_unicode_scalar_rows_length_4")
}

/// Runs the fixture `method_len_str_executes_unicode_scalar_rows_length_5`.
#[test]
fn method_len_str_executes_unicode_scalar_rows_length_5() -> CaseResult {
    assert_fixture_holds(AREA, "method_len_str_executes_unicode_scalar_rows_length_5")
}

/// Runs the fixture `nested_failure_retains_program_stdout`.
#[test]
fn nested_failure_retains_program_stdout() -> CaseResult {
    assert_fixture_holds(AREA, "nested_failure_retains_program_stdout")
}

/// Runs the fixture `parity_bytes_literal_passed_to_a_bytes_parameter`.
#[test]
fn parity_bytes_literal_passed_to_a_bytes_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "parity_bytes_literal_passed_to_a_bytes_parameter")
}

/// Runs the fixture `parity_concatenate_a_str_parameter`.
#[test]
fn parity_concatenate_a_str_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "parity_concatenate_a_str_parameter")
}

/// Runs the fixture `parity_return_an_owned_local_str`.
#[test]
fn parity_return_an_owned_local_str() -> CaseResult {
    assert_fixture_holds(AREA, "parity_return_an_owned_local_str")
}

/// Runs the fixture `parity_str_membership_in_a_str`.
#[test]
fn parity_str_membership_in_a_str() -> CaseResult {
    assert_fixture_holds(AREA, "parity_str_membership_in_a_str")
}

/// Runs the fixture `refuses_f_string_interpolation_it_cannot_render_identically`.
#[test]
fn refuses_f_string_interpolation_it_cannot_render_identically() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_f_string_interpolation_it_cannot_render_identically")
}

/// Runs the fixture `refuses_json_stringify_outside_the_scalar_domain_at_the_call_span`.
#[test]
fn refuses_json_stringify_outside_the_scalar_domain_at_the_call_span() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_json_stringify_outside_the_scalar_domain_at_the_call_span",
    )
}

/// Runs the fixture `refuses_list_membership_it_cannot_compare`.
#[test]
fn refuses_list_membership_it_cannot_compare() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_list_membership_it_cannot_compare")
}

/// Runs the fixture `refuses_to_print_a_value_it_cannot_render_identically`.
#[test]
fn refuses_to_print_a_value_it_cannot_render_identically() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_to_print_a_value_it_cannot_render_identically")
}

/// Runs the fixture `reused_program_io_isolates_each_successful_execution`.
#[test]
fn reused_program_io_isolates_each_successful_execution() -> CaseResult {
    assert_fixture_holds(AREA, "reused_program_io_isolates_each_successful_execution")
}

/// Runs the fixture `selected_string_helpers_execute_from_checked_operations`.
#[test]
fn selected_string_helpers_execute_from_checked_operations() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_execute_from_checked_operations")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_2`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_2() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_2")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_3`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_3() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_3")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_4`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_4() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_4")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_5`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_5() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_5")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_6`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_6() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_6")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_7`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_7() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_7")
}

/// Runs the fixture `selected_string_helpers_preserve_shared_edge_semantics_8`.
#[test]
fn selected_string_helpers_preserve_shared_edge_semantics_8() -> CaseResult {
    assert_fixture_holds(AREA, "selected_string_helpers_preserve_shared_edge_semantics_8")
}

/// Runs the fixture `short_writes_preserve_output_and_identity`.
#[test]
fn short_writes_preserve_output_and_identity() -> CaseResult {
    assert_fixture_holds(AREA, "short_writes_preserve_output_and_identity")
}

/// Runs the fixture `split_default_separator_on_a_parameter`.
#[test]
fn split_default_separator_on_a_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "split_default_separator_on_a_parameter")
}

/// Runs the fixture `split_without_a_separator_keeps_surrounding_whitespace`.
#[test]
fn split_without_a_separator_keeps_surrounding_whitespace() -> CaseResult {
    assert_fixture_holds(AREA, "split_without_a_separator_keeps_surrounding_whitespace")
}

/// Runs the fixture `stdout_survives_a_later_runtime_failure`.
#[test]
fn stdout_survives_a_later_runtime_failure() -> CaseResult {
    assert_fixture_holds(AREA, "stdout_survives_a_later_runtime_failure")
}

/// Runs the fixture `stdout_survives_a_later_runtime_failure_legacy_route`.
#[test]
fn stdout_survives_a_later_runtime_failure_legacy_route() -> CaseResult {
    assert_fixture_holds(AREA, "stdout_survives_a_later_runtime_failure_legacy_route")
}

/// Runs the fixture `still_refuses_iteration_over_an_unrepresentable_element`.
#[test]
fn still_refuses_iteration_over_an_unrepresentable_element() -> CaseResult {
    assert_fixture_holds(AREA, "still_refuses_iteration_over_an_unrepresentable_element")
}

/// Runs the fixture `string_len_matches_the_receipt_backed_native_route`.
#[test]
fn string_len_matches_the_receipt_backed_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "string_len_matches_the_receipt_backed_native_route")
}

/// Runs the fixture `string_len_output_is_delivered_exactly_once`.
#[test]
fn string_len_output_is_delivered_exactly_once() -> CaseResult {
    assert_fixture_holds(AREA, "string_len_output_is_delivered_exactly_once")
}

/// Runs the fixture `string_len_output_is_delivered_exactly_once_2`.
#[test]
fn string_len_output_is_delivered_exactly_once_2() -> CaseResult {
    assert_fixture_holds(AREA, "string_len_output_is_delivered_exactly_once_2")
}

/// Runs the fixture `string_membership_cli_records_the_shared_helper_result`.
#[test]
fn string_membership_cli_records_the_shared_helper_result() -> CaseResult {
    assert_fixture_holds(AREA, "string_membership_cli_records_the_shared_helper_result")
}

/// Runs the fixture `success_keeps_program_streams_separate_from_metadata`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn success_keeps_program_streams_separate_from_metadata() -> CaseResult {
    assert_fixture_holds(AREA, "success_keeps_program_streams_separate_from_metadata")
}

/// Runs the fixture `unselected_string_methods_refuse_before_program_output`.
#[test]
fn unselected_string_methods_refuse_before_program_output() -> CaseResult {
    assert_fixture_holds(AREA, "unselected_string_methods_refuse_before_program_output")
}

/// Every `pending:` fixture of the area still does not show what it declares.
#[test]
fn pending_fixtures_still_wait() -> CaseResult {
    assert_pending_fixtures_still_wait(AREA)
}
