//! @generated by `make behavior-roots` from the behavior-fixture area `cli_dependencies`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_dependencies/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_dependencies";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `callable_across_package_boundary`.
#[test]
fn callable_across_package_boundary() -> CaseResult {
    assert_fixture_holds(AREA, "callable_across_package_boundary")
}

/// Runs the fixture `compiled_generic_bounds`.
#[test]
fn compiled_generic_bounds() -> CaseResult {
    assert_fixture_holds(AREA, "compiled_generic_bounds")
}

/// Runs the fixture `dependency_enums_sharing_variant_names`.
#[test]
fn dependency_enums_sharing_variant_names() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_enums_sharing_variant_names")
}

/// Runs the fixture `dependency_helper_defaults_and_unions`.
#[test]
fn dependency_helper_defaults_and_unions() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_helper_defaults_and_unions")
}

/// Runs the fixture `dependency_method_returning_a_union`.
#[test]
fn dependency_method_returning_a_union() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_method_returning_a_union")
}

/// Runs the fixture `dependency_model_built_with_empty_fields_of_unimported_types`.
#[test]
fn dependency_model_built_with_empty_fields_of_unimported_types() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_model_built_with_empty_fields_of_unimported_types")
}

/// Runs the fixture `dependency_reexported_type_identity`.
#[test]
fn dependency_reexported_type_identity() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_reexported_type_identity")
}

/// Runs the fixture `dependency_renamed_export_reexported_under_a_new_name`.
#[test]
fn dependency_renamed_export_reexported_under_a_new_name() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_renamed_export_reexported_under_a_new_name")
}

/// Runs the fixture `dependency_same_named_declarations_in_two_modules`.
#[test]
fn dependency_same_named_declarations_in_two_modules() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_same_named_declarations_in_two_modules")
}

/// Runs the fixture `dependency_submodule_reexports`.
#[test]
fn dependency_submodule_reexports() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_submodule_reexports")
}

/// Runs the fixture `dependency_trait_adopted_and_bound_under_different_spellings`.
#[test]
fn dependency_trait_adopted_and_bound_under_different_spellings() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_trait_adopted_and_bound_under_different_spellings")
}

/// Runs the fixture `dependency_trait_through_a_module_binding`.
#[test]
fn dependency_trait_through_a_module_binding() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_trait_through_a_module_binding")
}

/// Runs the fixture `dependency_trait_under_another_spelling`.
#[test]
fn dependency_trait_under_another_spelling() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_trait_under_another_spelling")
}

/// Runs the fixture `dependency_union_surface_keeps_reexported_element_fields`.
#[test]
fn dependency_union_surface_keeps_reexported_element_fields() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_union_surface_keeps_reexported_element_fields")
}

/// Runs the fixture `dev7_dependency_enum_reexports`.
#[test]
fn dev7_dependency_enum_reexports() -> CaseResult {
    assert_fixture_holds(AREA, "dev7_dependency_enum_reexports")
}

/// Runs the fixture `dev7_nested_carrier_ownership`.
#[test]
fn dev7_nested_carrier_ownership() -> CaseResult {
    assert_fixture_holds(AREA, "dev7_nested_carrier_ownership")
}

/// Runs the fixture `fallible_iterator_chain_without_trait_import`.
#[test]
fn fallible_iterator_chain_without_trait_import() -> CaseResult {
    assert_fixture_holds(AREA, "fallible_iterator_chain_without_trait_import")
}

/// Runs the fixture `imported_partial_keeps_target_defaults`.
#[test]
fn imported_partial_keeps_target_defaults() -> CaseResult {
    assert_fixture_holds(AREA, "imported_partial_keeps_target_defaults")
}

/// Runs the fixture `mut_parameter_across_package_boundary`.
#[test]
fn mut_parameter_across_package_boundary() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_across_package_boundary")
}

/// Runs the fixture `private_default_items_from_dependency`.
#[test]
fn private_default_items_from_dependency() -> CaseResult {
    assert_fixture_holds(AREA, "private_default_items_from_dependency")
}

/// Runs the fixture `public_construction_default_from_dependency`.
#[test]
fn public_construction_default_from_dependency() -> CaseResult {
    assert_fixture_holds(AREA, "public_construction_default_from_dependency")
}

/// Runs the fixture `refused_adopter_relying_on_a_dependency_trait_default`.
#[test]
fn refused_adopter_relying_on_a_dependency_trait_default() -> CaseResult {
    assert_fixture_holds(AREA, "refused_adopter_relying_on_a_dependency_trait_default")
}

/// Runs the fixture `refused_dependency_default_calling_a_builtin`.
#[test]
fn refused_dependency_default_calling_a_builtin() -> CaseResult {
    assert_fixture_holds(AREA, "refused_dependency_default_calling_a_builtin")
}

/// Runs the fixture `refused_dependency_default_constructing_a_private_model`.
#[test]
fn refused_dependency_default_constructing_a_private_model() -> CaseResult {
    assert_fixture_holds(AREA, "refused_dependency_default_constructing_a_private_model")
}

/// Runs the fixture `refused_feature_gated_export_of_dependency`.
#[test]
fn refused_feature_gated_export_of_dependency() -> CaseResult {
    assert_fixture_holds(AREA, "refused_feature_gated_export_of_dependency")
}

/// Runs the fixture `refused_imported_partial_without_carried_default`.
#[test]
fn refused_imported_partial_without_carried_default() -> CaseResult {
    assert_fixture_holds(AREA, "refused_imported_partial_without_carried_default")
}

/// Runs the fixture `some_member_into_dependency_option_union`.
#[test]
fn some_member_into_dependency_option_union() -> CaseResult {
    assert_fixture_holds(AREA, "some_member_into_dependency_option_union")
}
