//! @generated by `make behavior-roots` from the behavior-fixture area `lowering_declarations`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/lowering_declarations/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "lowering_declarations";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `adopted_serde_traits_by_owner`.
#[test]
fn adopted_serde_traits_by_owner() -> CaseResult {
    assert_fixture_holds(AREA, "adopted_serde_traits_by_owner")
}

/// Runs the fixture `assert_is_some_binds_the_payload`.
#[test]
fn assert_is_some_binds_the_payload() -> CaseResult {
    assert_fixture_holds(AREA, "assert_is_some_binds_the_payload")
}

/// Runs the fixture `assert_raises_forms`.
#[test]
fn assert_raises_forms() -> CaseResult {
    assert_fixture_holds(AREA, "assert_raises_forms")
}

/// Runs the fixture `comparison_dunders_of_an_adopter_from_another_module`.
#[test]
fn comparison_dunders_of_an_adopter_from_another_module() -> CaseResult {
    assert_fixture_holds(AREA, "comparison_dunders_of_an_adopter_from_another_module")
}

/// Runs the fixture `comparison_dunders_through_every_spelling`.
#[test]
fn comparison_dunders_through_every_spelling() -> CaseResult {
    assert_fixture_holds(AREA, "comparison_dunders_through_every_spelling")
}

/// Runs the fixture `comparison_trait_adopters_compare_and_sort`.
#[test]
fn comparison_trait_adopters_compare_and_sort() -> CaseResult {
    assert_fixture_holds(AREA, "comparison_trait_adopters_compare_and_sort")
}

/// Runs the fixture `comparison_trait_adopters_of_every_kind`.
#[test]
fn comparison_trait_adopters_of_every_kind() -> CaseResult {
    assert_fixture_holds(AREA, "comparison_trait_adopters_of_every_kind")
}

/// Runs the fixture `default_type_constructors_keep_module_identity`.
#[test]
fn default_type_constructors_keep_module_identity() -> CaseResult {
    assert_fixture_holds(AREA, "default_type_constructors_keep_module_identity")
}

/// Runs the fixture `dunders_of_a_derived_ord`.
#[test]
fn dunders_of_a_derived_ord() -> CaseResult {
    assert_fixture_holds(AREA, "dunders_of_a_derived_ord")
}

/// Runs the fixture `dunders_through_builtin_bounds`.
#[test]
fn dunders_through_builtin_bounds() -> CaseResult {
    assert_fixture_holds(AREA, "dunders_through_builtin_bounds")
}

/// Runs the fixture `exact_float_width_arithmetic`.
#[test]
fn exact_float_width_arithmetic() -> CaseResult {
    assert_fixture_holds(AREA, "exact_float_width_arithmetic")
}

/// Runs the fixture `frozen_collections_display_structurally`.
#[test]
fn frozen_collections_display_structurally() -> CaseResult {
    assert_fixture_holds(AREA, "frozen_collections_display_structurally")
}

/// Runs the fixture `frozen_collections_nested_strings`.
#[test]
fn frozen_collections_nested_strings() -> CaseResult {
    assert_fixture_holds(AREA, "frozen_collections_nested_strings")
}

/// Runs the fixture `function_model_enum_and_entry`.
#[test]
fn function_model_enum_and_entry() -> CaseResult {
    assert_fixture_holds(AREA, "function_model_enum_and_entry")
}

/// Runs the fixture `generic_nominal_arguments`.
#[test]
fn generic_nominal_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "generic_nominal_arguments")
}

/// Runs the fixture `immutable_reassignment_refused`.
#[test]
fn immutable_reassignment_refused() -> CaseResult {
    assert_fixture_holds(AREA, "immutable_reassignment_refused")
}

/// Runs the fixture `imported_function_alias`.
#[test]
fn imported_function_alias() -> CaseResult {
    assert_fixture_holds(AREA, "imported_function_alias")
}

/// Runs the fixture `imported_union_member_identity`.
#[test]
fn imported_union_member_identity() -> CaseResult {
    assert_fixture_holds(AREA, "imported_union_member_identity")
}

/// Runs the fixture `imported_user_json_keeps_field`.
#[test]
fn imported_user_json_keeps_field() -> CaseResult {
    assert_fixture_holds(AREA, "imported_user_json_keeps_field")
}

/// Runs the fixture `isinstance_over_string_storages`.
#[test]
fn isinstance_over_string_storages() -> CaseResult {
    assert_fixture_holds(AREA, "isinstance_over_string_storages")
}

/// Runs the fixture `local_trait_shadows_imported_trait_issue1592`.
#[test]
fn local_trait_shadows_imported_trait_issue1592() -> CaseResult {
    assert_fixture_holds(AREA, "local_trait_shadows_imported_trait_issue1592")
}

/// Runs the fixture `ne_reaches_the_eq_default_of_an_ord_only_adopter`.
#[test]
fn ne_reaches_the_eq_default_of_an_ord_only_adopter() -> CaseResult {
    assert_fixture_holds(AREA, "ne_reaches_the_eq_default_of_an_ord_only_adopter")
}

/// Runs the fixture `option_identity_and_comparison_bounds`.
#[test]
fn option_identity_and_comparison_bounds() -> CaseResult {
    assert_fixture_holds(AREA, "option_identity_and_comparison_bounds")
}

/// Runs the fixture `phantom_type_parameter_model_issue1370`.
#[test]
fn phantom_type_parameter_model_issue1370() -> CaseResult {
    assert_fixture_holds(AREA, "phantom_type_parameter_model_issue1370")
}

/// Runs the fixture `pub_model_private_field_refused_issue884`.
#[test]
fn pub_model_private_field_refused_issue884() -> CaseResult {
    assert_fixture_holds(AREA, "pub_model_private_field_refused_issue884")
}

/// Runs the fixture `serde_derive_propagation`.
#[test]
fn serde_derive_propagation() -> CaseResult {
    assert_fixture_holds(AREA, "serde_derive_propagation")
}

/// Runs the fixture `statements_and_expressions`.
#[test]
fn statements_and_expressions() -> CaseResult {
    assert_fixture_holds(AREA, "statements_and_expressions")
}

/// Runs the fixture `stdlib_trait_default_names_its_own_module_type`.
#[test]
fn stdlib_trait_default_names_its_own_module_type() -> CaseResult {
    assert_fixture_holds(AREA, "stdlib_trait_default_names_its_own_module_type")
}

/// Runs the fixture `trait_default_appending_its_own_item`.
#[test]
fn trait_default_appending_its_own_item() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_appending_its_own_item")
}

/// Runs the fixture `trait_default_calls_on_self`.
#[test]
fn trait_default_calls_on_self() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_calls_on_self")
}

/// Runs the fixture `trait_default_local_shadows_module_type`.
#[test]
fn trait_default_local_shadows_module_type() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_local_shadows_module_type")
}

/// Runs the fixture `trait_default_nested_module_identity`.
#[test]
fn trait_default_nested_module_identity() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_nested_module_identity")
}

/// Runs the fixture `trait_default_passes_self_by_value`.
#[test]
fn trait_default_passes_self_by_value() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_passes_self_by_value")
}
