//! @generated by `make behavior-roots` from the behavior-fixture area `cli_values_and_calls`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_values_and_calls/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_values_and_calls";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `annotated_collection_literals`.
#[test]
fn annotated_collection_literals() -> CaseResult {
    assert_fixture_holds(AREA, "annotated_collection_literals")
}

/// Runs the fixture `annotated_tuple_literal_types_its_elements`.
#[test]
fn annotated_tuple_literal_types_its_elements() -> CaseResult {
    assert_fixture_holds(AREA, "annotated_tuple_literal_types_its_elements")
}

/// Runs the fixture `awaiting_each_task_handle_of_a_list`.
#[test]
fn awaiting_each_task_handle_of_a_list() -> CaseResult {
    assert_fixture_holds(AREA, "awaiting_each_task_handle_of_a_list")
}

/// Runs the fixture `awaiting_task_handles_of_a_call_result_and_a_literal`.
#[test]
fn awaiting_task_handles_of_a_call_result_and_a_literal() -> CaseResult {
    assert_fixture_holds(AREA, "awaiting_task_handles_of_a_call_result_and_a_literal")
}

/// Runs the fixture `awaiting_task_handles_of_nested_and_parenthesized_lists`.
#[test]
fn awaiting_task_handles_of_nested_and_parenthesized_lists() -> CaseResult {
    assert_fixture_holds(AREA, "awaiting_task_handles_of_nested_and_parenthesized_lists")
}

/// Runs the fixture `bitwise_operators_keep_the_integer_type`.
#[test]
fn bitwise_operators_keep_the_integer_type() -> CaseResult {
    assert_fixture_holds(AREA, "bitwise_operators_keep_the_integer_type")
}

/// Runs the fixture `callable_presets_of_constructors_and_declaration_safe_values`.
#[test]
fn callable_presets_of_constructors_and_declaration_safe_values() -> CaseResult {
    assert_fixture_holds(AREA, "callable_presets_of_constructors_and_declaration_safe_values")
}

/// Runs the fixture `capturing_closures_as_result_combinator_callbacks`.
#[test]
fn capturing_closures_as_result_combinator_callbacks() -> CaseResult {
    assert_fixture_holds(AREA, "capturing_closures_as_result_combinator_callbacks")
}

/// Runs the fixture `capturing_closures_in_function_types`.
#[test]
fn capturing_closures_in_function_types() -> CaseResult {
    assert_fixture_holds(AREA, "capturing_closures_in_function_types")
}

/// Runs the fixture `chained_assignment_reassigns_names_inside_a_loop`.
#[test]
fn chained_assignment_reassigns_names_inside_a_loop() -> CaseResult {
    assert_fixture_holds(AREA, "chained_assignment_reassigns_names_inside_a_loop")
}

/// Runs the fixture `chained_integer_literal_takes_each_target_type`.
#[test]
fn chained_integer_literal_takes_each_target_type() -> CaseResult {
    assert_fixture_holds(AREA, "chained_integer_literal_takes_each_target_type")
}

/// Runs the fixture `channel_constructors_with_an_explicit_element_type`.
#[test]
fn channel_constructors_with_an_explicit_element_type() -> CaseResult {
    assert_fixture_holds(AREA, "channel_constructors_with_an_explicit_element_type")
}

/// Runs the fixture `collection_copies_leave_their_source`.
#[test]
fn collection_copies_leave_their_source() -> CaseResult {
    assert_fixture_holds(AREA, "collection_copies_leave_their_source")
}

/// Runs the fixture `compound_assignment_keeps_operator_result_type`.
#[test]
fn compound_assignment_keeps_operator_result_type() -> CaseResult {
    assert_fixture_holds(AREA, "compound_assignment_keeps_operator_result_type")
}

/// Runs the fixture `const_frozen_collection_reads`.
#[test]
fn const_frozen_collection_reads() -> CaseResult {
    assert_fixture_holds(AREA, "const_frozen_collection_reads")
}

/// Runs the fixture `display_positions_render_collections_alike`.
#[test]
fn display_positions_render_collections_alike() -> CaseResult {
    assert_fixture_holds(AREA, "display_positions_render_collections_alike")
}

/// Runs the fixture `empty_list_assigned_to_optional_binding_is_wrapped`.
#[test]
fn empty_list_assigned_to_optional_binding_is_wrapped() -> CaseResult {
    assert_fixture_holds(AREA, "empty_list_assigned_to_optional_binding_is_wrapped")
}

/// Runs the fixture `exact_width_integer_arithmetic_keeps_its_type`.
#[test]
fn exact_width_integer_arithmetic_keeps_its_type() -> CaseResult {
    assert_fixture_holds(AREA, "exact_width_integer_arithmetic_keeps_its_type")
}

/// Runs the fixture `expected_literal_followups`.
#[test]
fn expected_literal_followups() -> CaseResult {
    assert_fixture_holds(AREA, "expected_literal_followups")
}

/// Runs the fixture `generator_mut_parameter_advanced_by_the_callee`.
#[test]
fn generator_mut_parameter_advanced_by_the_callee() -> CaseResult {
    assert_fixture_holds(AREA, "generator_mut_parameter_advanced_by_the_callee")
}

/// Runs the fixture `int_spellings_are_one_type`.
#[test]
fn int_spellings_are_one_type() -> CaseResult {
    assert_fixture_holds(AREA, "int_spellings_are_one_type")
}

/// Runs the fixture `integer_literal_assigned_to_float_binding`.
#[test]
fn integer_literal_assigned_to_float_binding() -> CaseResult {
    assert_fixture_holds(AREA, "integer_literal_assigned_to_float_binding")
}

/// Runs the fixture `local_partials_of_generic_and_imported_callables`.
#[test]
fn local_partials_of_generic_and_imported_callables() -> CaseResult {
    assert_fixture_holds(AREA, "local_partials_of_generic_and_imported_callables")
}

/// Runs the fixture `method_alias_on_a_mut_parameter`.
#[test]
fn method_alias_on_a_mut_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "method_alias_on_a_mut_parameter")
}

/// Runs the fixture `mut_local_changed_through_a_pattern_binding`.
#[test]
fn mut_local_changed_through_a_pattern_binding() -> CaseResult {
    assert_fixture_holds(AREA, "mut_local_changed_through_a_pattern_binding")
}

/// Runs the fixture `mut_marked_callable_value_changes_the_argument`.
#[test]
fn mut_marked_callable_value_changes_the_argument() -> CaseResult {
    assert_fixture_holds(AREA, "mut_marked_callable_value_changes_the_argument")
}

/// Runs the fixture `mut_parameter_changed_through_a_callable_type_reaches_the_caller`.
#[test]
fn mut_parameter_changed_through_a_callable_type_reaches_the_caller() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_changed_through_a_callable_type_reaches_the_caller")
}

/// Runs the fixture `mut_parameter_changed_through_a_loop_variable_reaches_the_caller`.
#[test]
fn mut_parameter_changed_through_a_loop_variable_reaches_the_caller() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_changed_through_a_loop_variable_reaches_the_caller")
}

/// Runs the fixture `mut_parameter_changed_through_a_pattern_binding`.
#[test]
fn mut_parameter_changed_through_a_pattern_binding() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_changed_through_a_pattern_binding")
}

/// Runs the fixture `mut_parameter_changed_through_trait_dispatch_reaches_the_caller`.
#[test]
fn mut_parameter_changed_through_trait_dispatch_reaches_the_caller() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_changed_through_trait_dispatch_reaches_the_caller")
}

/// Runs the fixture `mut_parameter_of_a_scalar_alias`.
#[test]
fn mut_parameter_of_a_scalar_alias() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_of_a_scalar_alias")
}

/// Runs the fixture `mut_parameter_read_through_a_pattern_or_a_trait_method`.
#[test]
fn mut_parameter_read_through_a_pattern_or_a_trait_method() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_read_through_a_pattern_or_a_trait_method")
}

/// Runs the fixture `mut_parameter_takes_a_copy_of_a_loop_variable_it_does_not_change`.
#[test]
fn mut_parameter_takes_a_copy_of_a_loop_variable_it_does_not_change() -> CaseResult {
    assert_fixture_holds(AREA, "mut_parameter_takes_a_copy_of_a_loop_variable_it_does_not_change")
}

/// Runs the fixture `mutation_ownership_regressions`.
#[test]
fn mutation_ownership_regressions() -> CaseResult {
    assert_fixture_holds(AREA, "mutation_ownership_regressions")
}

/// Runs the fixture `numeric_resize_policies_and_decimal`.
#[test]
fn numeric_resize_policies_and_decimal() -> CaseResult {
    assert_fixture_holds(AREA, "numeric_resize_policies_and_decimal")
}

/// Runs the fixture `passing_channel_senders_and_locks_on`.
#[test]
fn passing_channel_senders_and_locks_on() -> CaseResult {
    assert_fixture_holds(AREA, "passing_channel_senders_and_locks_on")
}

/// Runs the fixture `passing_each_task_handle_of_a_list_on`.
#[test]
fn passing_each_task_handle_of_a_list_on() -> CaseResult {
    assert_fixture_holds(AREA, "passing_each_task_handle_of_a_list_on")
}

/// Runs the fixture `power_with_literal_base`.
#[test]
fn power_with_literal_base() -> CaseResult {
    assert_fixture_holds(AREA, "power_with_literal_base")
}

/// Runs the fixture `set_constructor_over_generator`.
#[test]
fn set_constructor_over_generator() -> CaseResult {
    assert_fixture_holds(AREA, "set_constructor_over_generator")
}

/// Runs the fixture `static_alias_with_type_annotation`.
#[test]
fn static_alias_with_type_annotation() -> CaseResult {
    assert_fixture_holds(AREA, "static_alias_with_type_annotation")
}

/// Runs the fixture `static_counter_reads_one_key_with_get`.
#[test]
fn static_counter_reads_one_key_with_get() -> CaseResult {
    assert_fixture_holds(AREA, "static_counter_reads_one_key_with_get")
}

/// Runs the fixture `static_dict_get_with_a_reused_str_parameter`.
#[test]
fn static_dict_get_with_a_reused_str_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "static_dict_get_with_a_reused_str_parameter")
}

/// Runs the fixture `stdlib_const_default_omitted`.
#[test]
fn stdlib_const_default_omitted() -> CaseResult {
    assert_fixture_holds(AREA, "stdlib_const_default_omitted")
}

/// Runs the fixture `str_const_assignment_to_owned_places`.
#[test]
fn str_const_assignment_to_owned_places() -> CaseResult {
    assert_fixture_holds(AREA, "str_const_assignment_to_owned_places")
}

/// Runs the fixture `str_const_returned_as_frozen_str`.
#[test]
fn str_const_returned_as_frozen_str() -> CaseResult {
    assert_fixture_holds(AREA, "str_const_returned_as_frozen_str")
}

/// Runs the fixture `trait_default_method_mutable_parameter`.
#[test]
fn trait_default_method_mutable_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "trait_default_method_mutable_parameter")
}

/// Runs the fixture `trait_mut_scalar_parameter_is_a_local_copy`.
#[test]
fn trait_mut_scalar_parameter_is_a_local_copy() -> CaseResult {
    assert_fixture_holds(AREA, "trait_mut_scalar_parameter_is_a_local_copy")
}

/// Runs the fixture `tuple_assignment_declares_a_name_beside_a_place`.
#[test]
fn tuple_assignment_declares_a_name_beside_a_place() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_assignment_declares_a_name_beside_a_place")
}

/// Runs the fixture `tuple_assignment_swaps_fields_and_list_elements`.
#[test]
fn tuple_assignment_swaps_fields_and_list_elements() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_assignment_swaps_fields_and_list_elements")
}

/// Runs the fixture `tuple_assignment_takes_a_bare_tuple_value`.
#[test]
fn tuple_assignment_takes_a_bare_tuple_value() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_assignment_takes_a_bare_tuple_value")
}

/// Runs the fixture `tuple_unpacking_reassigns_names_inside_a_loop`.
#[test]
fn tuple_unpacking_reassigns_names_inside_a_loop() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_unpacking_reassigns_names_inside_a_loop")
}

/// Runs the fixture `unsigned_zero_divisor_stops_the_program`.
#[test]
fn unsigned_zero_divisor_stops_the_program() -> CaseResult {
    assert_fixture_holds(AREA, "unsigned_zero_divisor_stops_the_program")
}
