//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_stdlib`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_stdlib/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_stdlib";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `awaitable_bound_join_handle`.
#[test]
fn awaitable_bound_join_handle() -> CaseResult {
    assert_fixture_holds(AREA, "awaitable_bound_join_handle")
}

/// Runs the fixture `awaitable_wrapper_adoption_refused`.
#[test]
fn awaitable_wrapper_adoption_refused() -> CaseResult {
    assert_fixture_holds(AREA, "awaitable_wrapper_adoption_refused")
}

/// Runs the fixture `generator_iterator_surface`.
#[test]
fn generator_iterator_surface() -> CaseResult {
    assert_fixture_holds(AREA, "generator_iterator_surface")
}

/// Runs the fixture `imported_stdlib_defaults`.
#[test]
fn imported_stdlib_defaults() -> CaseResult {
    assert_fixture_holds(AREA, "imported_stdlib_defaults")
}

/// Runs the fixture `iterator_adopters_reach_the_protocol_methods`.
#[test]
fn iterator_adopters_reach_the_protocol_methods() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_adopters_reach_the_protocol_methods")
}

/// Runs the fixture `iterator_adopters_spelled_through_their_module`.
#[test]
fn iterator_adopters_spelled_through_their_module() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_adopters_spelled_through_their_module")
}

/// Runs the fixture `loops_over_calls_returning_iterator_adopters`.
#[test]
fn loops_over_calls_returning_iterator_adopters() -> CaseResult {
    assert_fixture_holds(AREA, "loops_over_calls_returning_iterator_adopters")
}

/// Runs the fixture `newtype_web_response`.
#[test]
fn newtype_web_response() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_web_response")
}

/// Runs the fixture `result_combinators`.
#[test]
fn result_combinators() -> CaseResult {
    assert_fixture_holds(AREA, "result_combinators")
}

/// Runs the fixture `result_inspect_named_observer_copy_payload`.
#[test]
fn result_inspect_named_observer_copy_payload() -> CaseResult {
    assert_fixture_holds(AREA, "result_inspect_named_observer_copy_payload")
}

/// Runs the fixture `rust_allow_lint_suppressions`.
#[test]
fn rust_allow_lint_suppressions() -> CaseResult {
    assert_fixture_holds(AREA, "rust_allow_lint_suppressions")
}

/// Runs the fixture `rust_extern_delegation`.
#[test]
fn rust_extern_delegation() -> CaseResult {
    assert_fixture_holds(AREA, "rust_extern_delegation")
}

/// Runs the fixture `std_async_channels_and_sync`.
#[test]
fn std_async_channels_and_sync() -> CaseResult {
    assert_fixture_holds(AREA, "std_async_channels_and_sync")
}

/// Runs the fixture `std_async_race`.
#[test]
fn std_async_race() -> CaseResult {
    assert_fixture_holds(AREA, "std_async_race")
}

/// Runs the fixture `std_async_tasks_and_time`.
#[test]
fn std_async_tasks_and_time() -> CaseResult {
    assert_fixture_holds(AREA, "std_async_tasks_and_time")
}

/// Runs the fixture `std_compression`.
#[test]
fn std_compression() -> CaseResult {
    assert_fixture_holds(AREA, "std_compression")
}

/// Runs the fixture `std_derives_collection_adapters`.
#[test]
fn std_derives_collection_adapters() -> CaseResult {
    assert_fixture_holds(AREA, "std_derives_collection_adapters")
}

/// Runs the fixture `std_derives_collection_adapters_with_imported_clone`.
#[test]
fn std_derives_collection_adapters_with_imported_clone() -> CaseResult {
    assert_fixture_holds(AREA, "std_derives_collection_adapters_with_imported_clone")
}

/// Runs the fixture `std_derives_surface`.
#[test]
fn std_derives_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_derives_surface")
}

/// Runs the fixture `std_environ_args`.
#[test]
fn std_environ_args() -> CaseResult {
    assert_fixture_holds(AREA, "std_environ_args")
}

/// Runs the fixture `std_fs_path`.
#[test]
fn std_fs_path() -> CaseResult {
    assert_fixture_holds(AREA, "std_fs_path")
}

/// Runs the fixture `std_graph`.
#[test]
fn std_graph() -> CaseResult {
    assert_fixture_holds(AREA, "std_graph")
}

/// Runs the fixture `std_io_and_fs_trait_method_calls`.
#[test]
fn std_io_and_fs_trait_method_calls() -> CaseResult {
    assert_fixture_holds(AREA, "std_io_and_fs_trait_method_calls")
}

/// Runs the fixture `std_math`.
#[test]
fn std_math() -> CaseResult {
    assert_fixture_holds(AREA, "std_math")
}

/// Runs the fixture `std_regex`.
#[test]
fn std_regex() -> CaseResult {
    assert_fixture_holds(AREA, "std_regex")
}

/// Runs the fixture `std_registry_functions`.
#[test]
fn std_registry_functions() -> CaseResult {
    assert_fixture_holds(AREA, "std_registry_functions")
}

/// Runs the fixture `std_registry_methods`.
#[test]
fn std_registry_methods() -> CaseResult {
    assert_fixture_holds(AREA, "std_registry_methods")
}

/// Runs the fixture `std_registry_subjects`.
#[test]
fn std_registry_subjects() -> CaseResult {
    assert_fixture_holds(AREA, "std_registry_subjects")
}

/// Runs the fixture `std_serde_json_import`.
#[test]
fn std_serde_json_import() -> CaseResult {
    assert_fixture_holds(AREA, "std_serde_json_import")
}

/// Runs the fixture `std_tempfile`.
#[test]
fn std_tempfile() -> CaseResult {
    assert_fixture_holds(AREA, "std_tempfile")
}

/// Runs the fixture `std_testing_assertions`.
#[test]
fn std_testing_assertions() -> CaseResult {
    assert_fixture_holds(AREA, "std_testing_assertions")
}

/// Runs the fixture `std_testing_collections_and_async_in_one_program`.
#[test]
fn std_testing_collections_and_async_in_one_program() -> CaseResult {
    assert_fixture_holds(AREA, "std_testing_collections_and_async_in_one_program")
}

/// Runs the fixture `std_traits_surface`.
#[test]
fn std_traits_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_traits_surface")
}

/// Runs the fixture `std_uuid`.
#[test]
fn std_uuid() -> CaseResult {
    assert_fixture_holds(AREA, "std_uuid")
}

/// Runs the fixture `web_extractor_field_reads`.
#[test]
fn web_extractor_field_reads() -> CaseResult {
    assert_fixture_holds(AREA, "web_extractor_field_reads")
}

/// Runs the fixture `web_route_extractors`.
#[test]
fn web_route_extractors() -> CaseResult {
    assert_fixture_holds(AREA, "web_route_extractors")
}

/// Runs the fixture `web_route_nested_module`.
#[test]
fn web_route_nested_module() -> CaseResult {
    assert_fixture_holds(AREA, "web_route_nested_module")
}

/// Runs the fixture `web_route_private_nested_module`.
#[test]
fn web_route_private_nested_module() -> CaseResult {
    assert_fixture_holds(AREA, "web_route_private_nested_module")
}
