//! @generated by `make behavior-roots` from the behavior-fixture area `cli_refusals_values_and_calls`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/cli_refusals_values_and_calls/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "cli_refusals_values_and_calls";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `refused_arguments_binding_one_type_parameter_to_two_types`.
#[test]
fn refused_arguments_binding_one_type_parameter_to_two_types() -> CaseResult {
    assert_fixture_holds(AREA, "refused_arguments_binding_one_type_parameter_to_two_types")
}

/// Runs the fixture `refused_bounded_type_parameter_no_argument_fixes`.
#[test]
fn refused_bounded_type_parameter_no_argument_fixes() -> CaseResult {
    assert_fixture_holds(AREA, "refused_bounded_type_parameter_no_argument_fixes")
}

/// Runs the fixture `refused_capturing_closure_in_a_function_pointer_slot`.
#[test]
fn refused_capturing_closure_in_a_function_pointer_slot() -> CaseResult {
    assert_fixture_holds(AREA, "refused_capturing_closure_in_a_function_pointer_slot")
}

/// Runs the fixture `refused_capturing_closure_passed_to_an_iterator_terminal`.
#[test]
fn refused_capturing_closure_passed_to_an_iterator_terminal() -> CaseResult {
    assert_fixture_holds(AREA, "refused_capturing_closure_passed_to_an_iterator_terminal")
}

/// Runs the fixture `refused_capturing_closure_stored_by_an_iterator_adapter`.
#[test]
fn refused_capturing_closure_stored_by_an_iterator_adapter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_capturing_closure_stored_by_an_iterator_adapter")
}

/// Runs the fixture `refused_closure_result_with_an_unfixed_side`.
#[test]
fn refused_closure_result_with_an_unfixed_side() -> CaseResult {
    assert_fixture_holds(AREA, "refused_closure_result_with_an_unfixed_side")
}

/// Runs the fixture `refused_concrete_value_as_a_type_parameter`.
#[test]
fn refused_concrete_value_as_a_type_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_concrete_value_as_a_type_parameter")
}

/// Runs the fixture `refused_display_bound_of_a_none_type_argument`.
#[test]
fn refused_display_bound_of_a_none_type_argument() -> CaseResult {
    assert_fixture_holds(AREA, "refused_display_bound_of_a_none_type_argument")
}

/// Runs the fixture `refused_display_of_a_side_no_match_arm_fixes`.
#[test]
fn refused_display_of_a_side_no_match_arm_fixes() -> CaseResult {
    assert_fixture_holds(AREA, "refused_display_of_a_side_no_match_arm_fixes")
}

/// Runs the fixture `refused_display_of_an_open_result_side`.
#[test]
fn refused_display_of_an_open_result_side() -> CaseResult {
    assert_fixture_holds(AREA, "refused_display_of_an_open_result_side")
}

/// Runs the fixture `refused_display_of_an_open_result_side_of_a_match_subject`.
#[test]
fn refused_display_of_an_open_result_side_of_a_match_subject() -> CaseResult {
    assert_fixture_holds(AREA, "refused_display_of_an_open_result_side_of_a_match_subject")
}

/// Runs the fixture `refused_hash_method_through_a_hash_bound`.
#[test]
fn refused_hash_method_through_a_hash_bound() -> CaseResult {
    assert_fixture_holds(AREA, "refused_hash_method_through_a_hash_bound")
}

/// Runs the fixture `refused_iterator_method_on_a_collection`.
#[test]
fn refused_iterator_method_on_a_collection() -> CaseResult {
    assert_fixture_holds(AREA, "refused_iterator_method_on_a_collection")
}

/// Runs the fixture `refused_method_no_bound_of_a_type_parameter_declares`.
#[test]
fn refused_method_no_bound_of_a_type_parameter_declares() -> CaseResult {
    assert_fixture_holds(AREA, "refused_method_no_bound_of_a_type_parameter_declares")
}

/// Runs the fixture `refused_slice_of_a_type_without_getslice`.
#[test]
fn refused_slice_of_a_type_without_getslice() -> CaseResult {
    assert_fixture_holds(AREA, "refused_slice_of_a_type_without_getslice")
}

/// Runs the fixture `refused_type_parameter_value_as_a_concrete_type`.
#[test]
fn refused_type_parameter_value_as_a_concrete_type() -> CaseResult {
    assert_fixture_holds(AREA, "refused_type_parameter_value_as_a_concrete_type")
}

/// Runs the fixture `refused_unwrap_or_default_other_than_the_type_parameter`.
#[test]
fn refused_unwrap_or_default_other_than_the_type_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "refused_unwrap_or_default_other_than_the_type_parameter")
}
