//! @generated by `make behavior-roots` from the behavior-fixture area `execution_calls_types_and_modules`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/execution_calls_types_and_modules/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "execution_calls_types_and_modules";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `a_class_in_a_sibling_module_beside_the_called_function`.
#[test]
fn a_class_in_a_sibling_module_beside_the_called_function() -> CaseResult {
    assert_fixture_holds(AREA, "a_class_in_a_sibling_module_beside_the_called_function")
}

/// Runs the fixture `a_feature_gated_main_left_unselected`.
#[test]
fn a_feature_gated_main_left_unselected() -> CaseResult {
    assert_fixture_holds(AREA, "a_feature_gated_main_left_unselected")
}

/// Runs the fixture `a_feature_gated_main_selected_by_default`.
#[test]
fn a_feature_gated_main_selected_by_default() -> CaseResult {
    assert_fixture_holds(AREA, "a_feature_gated_main_selected_by_default")
}

/// Runs the fixture `a_function_passed_as_a_value`.
#[test]
fn a_function_passed_as_a_value() -> CaseResult {
    assert_fixture_holds(AREA, "a_function_passed_as_a_value")
}

/// Runs the fixture `a_local_shadowing_a_module_name_is_not_a_qualifier`.
#[test]
fn a_local_shadowing_a_module_name_is_not_a_qualifier() -> CaseResult {
    assert_fixture_holds(AREA, "a_local_shadowing_a_module_name_is_not_a_qualifier")
}

/// Runs the fixture `a_rust_import_in_an_imported_module`.
#[test]
fn a_rust_import_in_an_imported_module() -> CaseResult {
    assert_fixture_holds(AREA, "a_rust_import_in_an_imported_module")
}

/// Runs the fixture `a_shadow_request_does_not_alter_replacement_execution`.
#[test]
fn a_shadow_request_does_not_alter_replacement_execution() -> CaseResult {
    assert_fixture_holds(AREA, "a_shadow_request_does_not_alter_replacement_execution")
}

/// Runs the fixture `call_into_a_module_lowered_on_its_own`.
#[test]
fn call_into_a_module_lowered_on_its_own() -> CaseResult {
    assert_fixture_holds(AREA, "call_into_a_module_lowered_on_its_own")
}

/// Runs the fixture `call_into_a_sibling_module`.
#[test]
fn call_into_a_sibling_module() -> CaseResult {
    assert_fixture_holds(AREA, "call_into_a_sibling_module")
}

/// Runs the fixture `checked_nominal_target_refuses_at_its_retained_reference_span`.
#[test]
fn checked_nominal_target_refuses_at_its_retained_reference_span() -> CaseResult {
    assert_fixture_holds(AREA, "checked_nominal_target_refuses_at_its_retained_reference_span")
}

/// Runs the fixture `cli_executes_a_source_local_fieldless_enum_with_a_replacement_receipt`.
#[test]
fn cli_executes_a_source_local_fieldless_enum_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_executes_a_source_local_fieldless_enum_with_a_replacement_receipt",
    )
}

/// Runs the fixture `cli_executes_a_source_local_nominal_model_with_a_replacement_receipt`.
#[test]
fn cli_executes_a_source_local_nominal_model_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_executes_a_source_local_nominal_model_with_a_replacement_receipt",
    )
}

/// Runs the fixture `cli_executes_a_source_local_value_enum_with_a_replacement_receipt`.
#[test]
fn cli_executes_a_source_local_value_enum_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_executes_a_source_local_value_enum_with_a_replacement_receipt",
    )
}

/// Runs the fixture `cli_executes_direct_named_callable_with_a_replacement_receipt`.
#[test]
fn cli_executes_direct_named_callable_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_executes_direct_named_callable_with_a_replacement_receipt")
}

/// Runs the fixture `cli_executes_exact_std_async_activation_with_task_receipts`.
#[test]
fn cli_executes_exact_std_async_activation_with_task_receipts() -> CaseResult {
    assert_fixture_holds(AREA, "cli_executes_exact_std_async_activation_with_task_receipts")
}

/// Runs the fixture `cli_executes_fieldless_enum_matching_with_a_replacement_receipt`.
#[test]
fn cli_executes_fieldless_enum_matching_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_executes_fieldless_enum_matching_with_a_replacement_receipt")
}

/// Runs the fixture `cli_executes_same_error_result_routing_with_a_replacement_receipt`.
#[test]
fn cli_executes_same_error_result_routing_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_executes_same_error_result_routing_with_a_replacement_receipt",
    )
}

/// Runs the fixture `cli_executes_typed_body_ir_and_persists_a_replacement_receipt`.
#[test]
fn cli_executes_typed_body_ir_and_persists_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_executes_typed_body_ir_and_persists_a_replacement_receipt")
}

/// Runs the fixture `cli_executes_typed_empty_scalar_tuple_list_with_a_replacement_receipt`.
#[test]
fn cli_executes_typed_empty_scalar_tuple_list_with_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_executes_typed_empty_scalar_tuple_list_with_a_replacement_receipt",
    )
}

/// Runs the fixture `cli_json_report_projects_canonical_execution_evidence`.
#[test]
fn cli_json_report_projects_canonical_execution_evidence() -> CaseResult {
    assert_fixture_holds(AREA, "cli_json_report_projects_canonical_execution_evidence")
}

/// Runs the fixture `cli_refuses_a_range_aggregate_without_a_receipt`.
#[test]
fn cli_refuses_a_range_aggregate_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_a_range_aggregate_without_a_receipt")
}

/// Runs the fixture `cli_refuses_an_omitted_nominal_field_default_without_a_receipt`.
#[test]
fn cli_refuses_an_omitted_nominal_field_default_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_an_omitted_nominal_field_default_without_a_receipt")
}

/// Runs the fixture `cli_refuses_an_unsupported_sibling_without_a_receipt`.
#[test]
fn cli_refuses_an_unsupported_sibling_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_an_unsupported_sibling_without_a_receipt")
}

/// Runs the fixture `cli_refuses_async_task_failure_without_a_receipt`.
#[test]
fn cli_refuses_async_task_failure_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_async_task_failure_without_a_receipt")
}

/// Runs the fixture `cli_refuses_failing_race_winner_without_a_receipt`.
#[test]
fn cli_refuses_failing_race_winner_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_failing_race_winner_without_a_receipt")
}

/// Runs the fixture `cli_refuses_iteration_over_an_unrepresentable_element_without_a_receip`.
#[test]
fn cli_refuses_iteration_over_an_unrepresentable_element_without_a_receip() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_refuses_iteration_over_an_unrepresentable_element_without_a_receip",
    )
}

/// Runs the fixture `cli_refuses_typed_empty_non_structural_callable_default_without_a_rece`.
#[test]
fn cli_refuses_typed_empty_non_structural_callable_default_without_a_rece() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "cli_refuses_typed_empty_non_structural_callable_default_without_a_rece",
    )
}

/// Runs the fixture `cli_refuses_unsupported_callable_default_without_a_receipt`.
#[test]
fn cli_refuses_unsupported_callable_default_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_unsupported_callable_default_without_a_receipt")
}

/// Runs the fixture `cli_refuses_unsupported_source_without_legacy_generation`.
#[test]
fn cli_refuses_unsupported_source_without_legacy_generation() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_unsupported_source_without_legacy_generation")
}

/// Runs the fixture `cli_refuses_value_enum_from_value_without_a_receipt`.
#[test]
fn cli_refuses_value_enum_from_value_without_a_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_value_enum_from_value_without_a_receipt")
}

/// Runs the fixture `dispatches_generator_methods_by_canonical_target_and_refuses_absent_id`.
#[test]
fn dispatches_generator_methods_by_canonical_target_and_refuses_absent_id() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "dispatches_generator_methods_by_canonical_target_and_refuses_absent_id",
    )
}

/// Runs the fixture `dispatches_named_calls_by_canonical_target_and_refuses_absent_identity`.
#[test]
fn dispatches_named_calls_by_canonical_target_and_refuses_absent_identity() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "dispatches_named_calls_by_canonical_target_and_refuses_absent_identity",
    )
}

/// Runs the fixture `duplicate_async_activation_fails_during_typechecking`.
#[test]
fn duplicate_async_activation_fails_during_typechecking() -> CaseResult {
    assert_fixture_holds(AREA, "duplicate_async_activation_fails_during_typechecking")
}

/// Runs the fixture `duplicate_async_activation_fails_during_typechecking_2`.
#[test]
fn duplicate_async_activation_fails_during_typechecking_2() -> CaseResult {
    assert_fixture_holds(AREA, "duplicate_async_activation_fails_during_typechecking_2")
}

/// Runs the fixture `executes_a_captured_stored_closure_in_an_isolated_frame`.
#[test]
fn executes_a_captured_stored_closure_in_an_isolated_frame() -> CaseResult {
    assert_fixture_holds(AREA, "executes_a_captured_stored_closure_in_an_isolated_frame")
}

/// Runs the fixture `executes_a_lazy_generator_expression_only_when_collect_consumes_it`.
#[test]
fn executes_a_lazy_generator_expression_only_when_collect_consumes_it() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_a_lazy_generator_expression_only_when_collect_consumes_it",
    )
}

/// Runs the fixture `executes_a_same_module_range_declaration_by_its_direct_call_identity`.
#[test]
fn executes_a_same_module_range_declaration_by_its_direct_call_identity() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_a_same_module_range_declaration_by_its_direct_call_identity",
    )
}

/// Runs the fixture `executes_a_source_local_async_task_and_binds_its_lifecycle_evidence`.
#[test]
fn executes_a_source_local_async_task_and_binds_its_lifecycle_evidence() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_a_source_local_async_task_and_binds_its_lifecycle_evidence",
    )
}

/// Runs the fixture `executes_identity_selected_nominal_and_fieldless_enum_match_patterns`.
#[test]
fn executes_identity_selected_nominal_and_fieldless_enum_match_patterns() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_identity_selected_nominal_and_fieldless_enum_match_patterns",
    )
}

/// Runs the fixture `executes_lazy_generator_adapters_with_local_callbacks`.
#[test]
fn executes_lazy_generator_adapters_with_local_callbacks() -> CaseResult {
    assert_fixture_holds(AREA, "executes_lazy_generator_adapters_with_local_callbacks")
}

/// Runs the fixture `executes_partial_presets_source_defaults_and_named_overrides`.
#[test]
fn executes_partial_presets_source_defaults_and_named_overrides() -> CaseResult {
    assert_fixture_holds(AREA, "executes_partial_presets_source_defaults_and_named_overrides")
}

/// Runs the fixture `executes_same_error_result_routing_and_pattern_dispatch`.
#[test]
fn executes_same_error_result_routing_and_pattern_dispatch() -> CaseResult {
    assert_fixture_holds(AREA, "executes_same_error_result_routing_and_pattern_dispatch")
}

/// Runs the fixture `executes_same_error_result_routing_and_pattern_dispatch_legacy_route`.
#[test]
fn executes_same_error_result_routing_and_pattern_dispatch_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_same_error_result_routing_and_pattern_dispatch_legacy_route",
    )
}

/// Runs the fixture `executes_source_local_fieldless_enum_values_through_a_direct_callable`.
#[test]
fn executes_source_local_fieldless_enum_values_through_a_direct_callable() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_source_local_fieldless_enum_values_through_a_direct_callable",
    )
}

/// Runs the fixture `executes_source_local_nominal_model_values_through_a_direct_callable`.
#[test]
fn executes_source_local_nominal_model_values_through_a_direct_callable() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_source_local_nominal_model_values_through_a_direct_callable",
    )
}

/// Runs the fixture `executes_source_local_value_enum_members_through_a_direct_callable`.
#[test]
fn executes_source_local_value_enum_members_through_a_direct_callable() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_source_local_value_enum_members_through_a_direct_callable",
    )
}

/// Runs the fixture `executes_source_order_async_race_ties_with_loser_cancellation`.
#[test]
fn executes_source_order_async_race_ties_with_loser_cancellation() -> CaseResult {
    assert_fixture_holds(AREA, "executes_source_order_async_race_ties_with_loser_cancellation")
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_bool`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_bool() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_bool",
    )
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_bool_2`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_bool_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_bool_2",
    )
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_float`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_float() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_float",
    )
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_int`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_int() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_int",
    )
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_int_2`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_int_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_int_2",
    )
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_str`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_str() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_str",
    )
}

/// Runs the fixture `executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_str_2`.
#[test]
fn executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_str_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_true_and_false_checks_for_the_bounded_primitive_target_set_is_str_2",
    )
}

/// Runs the fixture `facade_chain_shares_one_declaration`.
#[test]
fn facade_chain_shares_one_declaration() -> CaseResult {
    assert_fixture_holds(AREA, "facade_chain_shares_one_declaration")
}

/// Runs the fixture `fixed_case_executes_every_admitted_target_with_exact_streams`.
#[test]
fn fixed_case_executes_every_admitted_target_with_exact_streams() -> CaseResult {
    assert_fixture_holds(AREA, "fixed_case_executes_every_admitted_target_with_exact_streams")
}

/// Runs the fixture `keeps_an_unconsumed_generator_expression_deferred`.
#[test]
fn keeps_an_unconsumed_generator_expression_deferred() -> CaseResult {
    assert_fixture_holds(AREA, "keeps_an_unconsumed_generator_expression_deferred")
}

/// Runs the fixture `keeps_an_unconsumed_generator_function_out_of_execution_evidence`.
#[test]
fn keeps_an_unconsumed_generator_function_out_of_execution_evidence() -> CaseResult {
    assert_fixture_holds(AREA, "keeps_an_unconsumed_generator_function_out_of_execution_evidence")
}

/// Runs the fixture `malformed_isinstance_in_a_reachable_callee_refuses_before_entrypoint_e`.
#[test]
fn malformed_isinstance_in_a_reachable_callee_refuses_before_entrypoint_e() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "malformed_isinstance_in_a_reachable_callee_refuses_before_entrypoint_e",
    )
}

/// Runs the fixture `module_qualified_call`.
#[test]
fn module_qualified_call() -> CaseResult {
    assert_fixture_holds(AREA, "module_qualified_call")
}

/// Runs the fixture `module_qualified_call_through_an_alias`.
#[test]
fn module_qualified_call_through_an_alias() -> CaseResult {
    assert_fixture_holds(AREA, "module_qualified_call_through_an_alias")
}

/// Runs the fixture `non_scalar_checked_value_types_refuse_before_effects`.
#[test]
fn non_scalar_checked_value_types_refuse_before_effects() -> CaseResult {
    assert_fixture_holds(AREA, "non_scalar_checked_value_types_refuse_before_effects")
}

/// Runs the fixture `primitive_targets_with_different_runtime_tags_do_not_coerce_probe`.
#[test]
fn primitive_targets_with_different_runtime_tags_do_not_coerce_probe() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "primitive_targets_with_different_runtime_tags_do_not_coerce_probe",
    )
}

/// Runs the fixture `primitive_targets_with_different_runtime_tags_do_not_coerce_probe_2`.
#[test]
fn primitive_targets_with_different_runtime_tags_do_not_coerce_probe_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "primitive_targets_with_different_runtime_tags_do_not_coerce_probe_2",
    )
}

/// Runs the fixture `propagates_async_task_failure_at_the_child_statement_span`.
#[test]
fn propagates_async_task_failure_at_the_child_statement_span() -> CaseResult {
    assert_fixture_holds(AREA, "propagates_async_task_failure_at_the_child_statement_span")
}

/// Runs the fixture `propagates_async_task_failure_at_the_child_statement_span_legacy_route`.
#[test]
fn propagates_async_task_failure_at_the_child_statement_span_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "propagates_async_task_failure_at_the_child_statement_span_legacy_route",
    )
}

/// Runs the fixture `race_failure_preserves_the_first_arm_span_and_cancels_constructed_lose`.
#[test]
fn race_failure_preserves_the_first_arm_span_and_cancels_constructed_lose() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "race_failure_preserves_the_first_arm_span_and_cancels_constructed_lose",
    )
}

/// Runs the fixture `race_failure_preserves_the_first_arm_span_and_cancels_constructed_lose_legacy_route`.
#[test]
fn race_failure_preserves_the_first_arm_span_and_cancels_constructed_lose_legacy_route() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "race_failure_preserves_the_first_arm_span_and_cancels_constructed_lose_legacy_route",
    )
}

/// Runs the fixture `race_ready_ties_follow_source_order_and_cancel_unpolled_losers`.
#[test]
fn race_ready_ties_follow_source_order_and_cancel_unpolled_losers() -> CaseResult {
    assert_fixture_holds(AREA, "race_ready_ties_follow_source_order_and_cancel_unpolled_losers")
}

/// Runs the fixture `records_construct_only_task_lifecycle_evidence`.
#[test]
fn records_construct_only_task_lifecycle_evidence() -> CaseResult {
    assert_fixture_holds(AREA, "records_construct_only_task_lifecycle_evidence")
}

/// Runs the fixture `refuses_a_fieldless_enum_member_without_its_retained_identity_at_its_o`.
#[test]
fn refuses_a_fieldless_enum_member_without_its_retained_identity_at_its_o() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_a_fieldless_enum_member_without_its_retained_identity_at_its_o",
    )
}

/// Runs the fixture `refuses_a_foreign_named_call_identity_at_its_original_source_span`.
#[test]
fn refuses_a_foreign_named_call_identity_at_its_original_source_span() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_a_foreign_named_call_identity_at_its_original_source_span",
    )
}

/// Runs the fixture `refuses_a_nominal_pattern_after_its_exact_target_identity_is_removed`.
#[test]
fn refuses_a_nominal_pattern_after_its_exact_target_identity_is_removed() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_a_nominal_pattern_after_its_exact_target_identity_is_removed",
    )
}

/// Runs the fixture `refuses_a_range_aggregate_before_evaluating_its_bounds`.
#[test]
fn refuses_a_range_aggregate_before_evaluating_its_bounds() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_a_range_aggregate_before_evaluating_its_bounds")
}

/// Runs the fixture `refuses_a_reordered_nominal_declaration_layout_at_the_original_constru`.
#[test]
fn refuses_a_reordered_nominal_declaration_layout_at_the_original_constru() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_a_reordered_nominal_declaration_layout_at_the_original_constru",
    )
}

/// Runs the fixture `refuses_a_value_enum_member_without_its_retained_identity_at_its_origi`.
#[test]
fn refuses_a_value_enum_member_without_its_retained_identity_at_its_origi() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_a_value_enum_member_without_its_retained_identity_at_its_origi",
    )
}

/// Runs the fixture `refuses_an_idless_nominal_constructor_at_its_original_source_span`.
#[test]
fn refuses_an_idless_nominal_constructor_at_its_original_source_span() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_an_idless_nominal_constructor_at_its_original_source_span",
    )
}

/// Runs the fixture `refuses_an_omitted_nominal_field_default_at_the_constructor_span`.
#[test]
fn refuses_an_omitted_nominal_field_default_at_the_constructor_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_an_omitted_nominal_field_default_at_the_constructor_span")
}

/// Runs the fixture `refuses_an_unsupported_callable_default_at_its_original_span`.
#[test]
fn refuses_an_unsupported_callable_default_at_its_original_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_an_unsupported_callable_default_at_its_original_span")
}

/// Runs the fixture `refuses_an_unsupported_sibling_body_at_its_original_span`.
#[test]
fn refuses_an_unsupported_sibling_body_at_its_original_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_an_unsupported_sibling_body_at_its_original_span")
}

/// Runs the fixture `refuses_enum_targets_whose_canonical_member_disagrees_with_the_physica`.
#[test]
fn refuses_enum_targets_whose_canonical_member_disagrees_with_the_physica() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_enum_targets_whose_canonical_member_disagrees_with_the_physica",
    )
}

/// Runs the fixture `refuses_enum_targets_whose_canonical_member_disagrees_with_the_physica_2`.
#[test]
fn refuses_enum_targets_whose_canonical_member_disagrees_with_the_physica_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_enum_targets_whose_canonical_member_disagrees_with_the_physica_2",
    )
}

/// Runs the fixture `refuses_nominal_field_assignment_at_the_original_source_span`.
#[test]
fn refuses_nominal_field_assignment_at_the_original_source_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_nominal_field_assignment_at_the_original_source_span")
}

/// Runs the fixture `refuses_typed_empty_non_structural_default_inside_a_partial_closure`.
#[test]
fn refuses_typed_empty_non_structural_default_inside_a_partial_closure() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_typed_empty_non_structural_default_inside_a_partial_closure",
    )
}

/// Runs the fixture `refuses_unsupported_or_malformed_targets_at_a_trusted_span_before_effe`.
#[test]
fn refuses_unsupported_or_malformed_targets_at_a_trusted_span_before_effe() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_unsupported_or_malformed_targets_at_a_trusted_span_before_effe",
    )
}

/// Runs the fixture `result_routing_through_try_and_match`.
#[test]
fn result_routing_through_try_and_match() -> CaseResult {
    assert_fixture_holds(AREA, "result_routing_through_try_and_match")
}

/// Runs the fixture `resumes_a_generator_function_without_replaying_its_prefix`.
#[test]
fn resumes_a_generator_function_without_replaying_its_prefix() -> CaseResult {
    assert_fixture_holds(AREA, "resumes_a_generator_function_without_replaying_its_prefix")
}

/// Runs the fixture `source_defined_isinstance_keeps_its_direct_callable_identity_explicit_probe`.
#[test]
fn source_defined_isinstance_keeps_its_direct_callable_identity_explicit_probe() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "source_defined_isinstance_keeps_its_direct_callable_identity_explicit_probe",
    )
}

/// Runs the fixture `source_defined_isinstance_keeps_its_direct_callable_identity_explicit_probe_2`.
#[test]
fn source_defined_isinstance_keeps_its_direct_callable_identity_explicit_probe_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "source_defined_isinstance_keeps_its_direct_callable_identity_explicit_probe_2",
    )
}

/// Runs the fixture `source_defined_isinstance_keeps_its_direct_callable_identity_probe`.
#[test]
fn source_defined_isinstance_keeps_its_direct_callable_identity_probe() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "source_defined_isinstance_keeps_its_direct_callable_identity_probe",
    )
}

/// Runs the fixture `static_method_calls_with_named_arguments`.
#[test]
fn static_method_calls_with_named_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "static_method_calls_with_named_arguments")
}

/// Runs the fixture `typed_list_in_a_callee_module`.
#[test]
fn typed_list_in_a_callee_module() -> CaseResult {
    assert_fixture_holds(AREA, "typed_list_in_a_callee_module")
}

/// Runs the fixture `typed_numeric_call_into_its_declaring_module`.
#[test]
fn typed_numeric_call_into_its_declaring_module() -> CaseResult {
    assert_fixture_holds(AREA, "typed_numeric_call_into_its_declaring_module")
}
