//! @generated by `make behavior-roots` from the behavior-fixture area `harness`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/harness/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "harness";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `contained_lines_in_any_order`.
#[test]
fn contained_lines_in_any_order() -> CaseResult {
    assert_fixture_holds(AREA, "contained_lines_in_any_order")
}

/// Runs the fixture `exit_code_from_failing_main`.
#[test]
fn exit_code_from_failing_main() -> CaseResult {
    assert_fixture_holds(AREA, "exit_code_from_failing_main")
}

/// Runs the fixture `exit_code_only`.
#[test]
fn exit_code_only() -> CaseResult {
    assert_fixture_holds(AREA, "exit_code_only")
}

/// Runs the fixture `modules`.
#[test]
fn modules() -> CaseResult {
    assert_fixture_holds(AREA, "modules")
}

/// Runs the fixture `prints_nothing`.
#[test]
fn prints_nothing() -> CaseResult {
    assert_fixture_holds(AREA, "prints_nothing")
}

/// Runs the fixture `project`.
#[test]
fn project() -> CaseResult {
    assert_fixture_holds(AREA, "project")
}

/// Runs the fixture `refused_undefined_name`.
#[test]
fn refused_undefined_name() -> CaseResult {
    assert_fixture_holds(AREA, "refused_undefined_name")
}

/// Runs the fixture `refused_with_two_codes`.
#[test]
fn refused_with_two_codes() -> CaseResult {
    assert_fixture_holds(AREA, "refused_with_two_codes")
}
