//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_traits_and_generics`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_traits_and_generics/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_traits_and_generics";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `automatic_and_implied_derives`.
#[test]
fn automatic_and_implied_derives() -> CaseResult {
    assert_fixture_holds(AREA, "automatic_and_implied_derives")
}

/// Runs the fixture `callable_bound_closure_and_model`.
#[test]
fn callable_bound_closure_and_model() -> CaseResult {
    assert_fixture_holds(AREA, "callable_bound_closure_and_model")
}

/// Runs the fixture `derived_default_takes_declared_field_defaults`.
#[test]
fn derived_default_takes_declared_field_defaults() -> CaseResult {
    assert_fixture_holds(AREA, "derived_default_takes_declared_field_defaults")
}

/// Runs the fixture `derived_display_prints_the_value_structure`.
#[test]
fn derived_display_prints_the_value_structure() -> CaseResult {
    assert_fixture_holds(AREA, "derived_display_prints_the_value_structure")
}

/// Runs the fixture `enum_eq_dunder_and_display_derive`.
#[test]
fn enum_eq_dunder_and_display_derive() -> CaseResult {
    assert_fixture_holds(AREA, "enum_eq_dunder_and_display_derive")
}

/// Runs the fixture `explicit_call_site_generics`.
#[test]
fn explicit_call_site_generics() -> CaseResult {
    assert_fixture_holds(AREA, "explicit_call_site_generics")
}

/// Runs the fixture `fallible_iteration_protocol`.
#[test]
fn fallible_iteration_protocol() -> CaseResult {
    assert_fixture_holds(AREA, "fallible_iteration_protocol")
}

/// Runs the fixture `fallible_iterator_adapter_chain`.
#[test]
fn fallible_iterator_adapter_chain() -> CaseResult {
    assert_fixture_holds(AREA, "fallible_iterator_adapter_chain")
}

/// Runs the fixture `generic_bounds_return_type`.
#[test]
fn generic_bounds_return_type() -> CaseResult {
    assert_fixture_holds(AREA, "generic_bounds_return_type")
}

/// Runs the fixture `generic_fallible_iterator_consumer`.
#[test]
fn generic_fallible_iterator_consumer() -> CaseResult {
    assert_fixture_holds(AREA, "generic_fallible_iterator_consumer")
}

/// Runs the fixture `generic_method_defaults`.
#[test]
fn generic_method_defaults() -> CaseResult {
    assert_fixture_holds(AREA, "generic_method_defaults")
}

/// Runs the fixture `generic_methods`.
#[test]
fn generic_methods() -> CaseResult {
    assert_fixture_holds(AREA, "generic_methods")
}

/// Runs the fixture `iterator_flat_map_draws_expansions_lazily`.
#[test]
fn iterator_flat_map_draws_expansions_lazily() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_flat_map_draws_expansions_lazily")
}

/// Runs the fixture `iterator_flat_map_over_iterables`.
#[test]
fn iterator_flat_map_over_iterables() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_flat_map_over_iterables")
}

/// Runs the fixture `method_type_param_clone_bound`.
#[test]
fn method_type_param_clone_bound() -> CaseResult {
    assert_fixture_holds(AREA, "method_type_param_clone_bound")
}

/// Runs the fixture `multi_instantiation_trait_methods`.
#[test]
fn multi_instantiation_trait_methods() -> CaseResult {
    assert_fixture_holds(AREA, "multi_instantiation_trait_methods")
}

/// Runs the fixture `newtype_trait_targets`.
#[test]
fn newtype_trait_targets() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_trait_targets")
}

/// Runs the fixture `protocol_hooks`.
#[test]
fn protocol_hooks() -> CaseResult {
    assert_fixture_holds(AREA, "protocol_hooks")
}

/// Runs the fixture `refused_copy_derive_over_str_field`.
#[test]
fn refused_copy_derive_over_str_field() -> CaseResult {
    assert_fixture_holds(AREA, "refused_copy_derive_over_str_field")
}

/// Runs the fixture `refused_eq_dunder_beside_eq_derive`.
#[test]
fn refused_eq_dunder_beside_eq_derive() -> CaseResult {
    assert_fixture_holds(AREA, "refused_eq_dunder_beside_eq_derive")
}

/// Runs the fixture `refused_equality_without_eq`.
#[test]
fn refused_equality_without_eq() -> CaseResult {
    assert_fixture_holds(AREA, "refused_equality_without_eq")
}

/// Runs the fixture `refused_hash_method_without_hash_derive`.
#[test]
fn refused_hash_method_without_hash_derive() -> CaseResult {
    assert_fixture_holds(AREA, "refused_hash_method_without_hash_derive")
}

/// Runs the fixture `refused_staticmethod_with_self_receiver`.
#[test]
fn refused_staticmethod_with_self_receiver() -> CaseResult {
    assert_fixture_holds(AREA, "refused_staticmethod_with_self_receiver")
}

/// Runs the fixture `sorted_list_of_ordered_types`.
#[test]
fn sorted_list_of_ordered_types() -> CaseResult {
    assert_fixture_holds(AREA, "sorted_list_of_ordered_types")
}

/// Runs the fixture `std_fallible_adapter_loop`.
#[test]
fn std_fallible_adapter_loop() -> CaseResult {
    assert_fixture_holds(AREA, "std_fallible_adapter_loop")
}

/// Runs the fixture `std_fallible_iterator_loop`.
#[test]
fn std_fallible_iterator_loop() -> CaseResult {
    assert_fixture_holds(AREA, "std_fallible_iterator_loop")
}

/// Runs the fixture `std_rust_capability_bounds`.
#[test]
fn std_rust_capability_bounds() -> CaseResult {
    assert_fixture_holds(AREA, "std_rust_capability_bounds")
}

/// Runs the fixture `std_traits_convert_usage`.
#[test]
fn std_traits_convert_usage() -> CaseResult {
    assert_fixture_holds(AREA, "std_traits_convert_usage")
}

/// Runs the fixture `structural_coercion`.
#[test]
fn structural_coercion() -> CaseResult {
    assert_fixture_holds(AREA, "structural_coercion")
}

/// Runs the fixture `trait_bound_default`.
#[test]
fn trait_bound_default() -> CaseResult {
    assert_fixture_holds(AREA, "trait_bound_default")
}

/// Runs the fixture `trait_bound_explicit`.
#[test]
fn trait_bound_explicit() -> CaseResult {
    assert_fixture_holds(AREA, "trait_bound_explicit")
}

/// Runs the fixture `trait_bound_inference`.
#[test]
fn trait_bound_inference() -> CaseResult {
    assert_fixture_holds(AREA, "trait_bound_inference")
}

/// Runs the fixture `trait_supertrait_assignability`.
#[test]
fn trait_supertrait_assignability() -> CaseResult {
    assert_fixture_holds(AREA, "trait_supertrait_assignability")
}

/// Runs the fixture `trait_supertraits`.
#[test]
fn trait_supertraits() -> CaseResult {
    assert_fixture_holds(AREA, "trait_supertraits")
}

/// Runs the fixture `traits`.
#[test]
fn traits() -> CaseResult {
    assert_fixture_holds(AREA, "traits")
}
