//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_enums_and_matching`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_enums_and_matching/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_enums_and_matching";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `cross_module_union`.
#[test]
fn cross_module_union() -> CaseResult {
    assert_fixture_holds(AREA, "cross_module_union")
}

/// Runs the fixture `enum_constructor_match`.
#[test]
fn enum_constructor_match() -> CaseResult {
    assert_fixture_holds(AREA, "enum_constructor_match")
}

/// Runs the fixture `enum_methods_and_traits`.
#[test]
fn enum_methods_and_traits() -> CaseResult {
    assert_fixture_holds(AREA, "enum_methods_and_traits")
}

/// Runs the fixture `enums`.
#[test]
fn enums() -> CaseResult {
    assert_fixture_holds(AREA, "enums")
}

/// Runs the fixture `for_in_list_enum_equality`.
#[test]
fn for_in_list_enum_equality() -> CaseResult {
    assert_fixture_holds(AREA, "for_in_list_enum_equality")
}

/// Runs the fixture `if_let_while_let`.
#[test]
fn if_let_while_let() -> CaseResult {
    assert_fixture_holds(AREA, "if_let_while_let")
}

/// Runs the fixture `imported_enum_loop_ownership`.
#[test]
fn imported_enum_loop_ownership() -> CaseResult {
    assert_fixture_holds(AREA, "imported_enum_loop_ownership")
}

/// Runs the fixture `isinstance_explicit_builtin_and_aliases`.
#[test]
fn isinstance_explicit_builtin_and_aliases() -> CaseResult {
    assert_fixture_holds(AREA, "isinstance_explicit_builtin_and_aliases")
}

/// Runs the fixture `match_statements`.
#[test]
fn match_statements() -> CaseResult {
    assert_fixture_holds(AREA, "match_statements")
}

/// Runs the fixture `newtype_union_isinstance`.
#[test]
fn newtype_union_isinstance() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_union_isinstance")
}

/// Runs the fixture `option_union_payloads`.
#[test]
fn option_union_payloads() -> CaseResult {
    assert_fixture_holds(AREA, "option_union_payloads")
}

/// Runs the fixture `pattern_alternation`.
#[test]
fn pattern_alternation() -> CaseResult {
    assert_fixture_holds(AREA, "pattern_alternation")
}

/// Runs the fixture `patterns`.
#[test]
fn patterns() -> CaseResult {
    assert_fixture_holds(AREA, "patterns")
}

/// Runs the fixture `trailing_match_expression`.
#[test]
fn trailing_match_expression() -> CaseResult {
    assert_fixture_holds(AREA, "trailing_match_expression")
}

/// Runs the fixture `tuple_pattern_bindings`.
#[test]
fn tuple_pattern_bindings() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_pattern_bindings")
}

/// Runs the fixture `tuple_str_literal_pattern`.
#[test]
fn tuple_str_literal_pattern() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_str_literal_pattern")
}

/// Runs the fixture `union_types`.
#[test]
fn union_types() -> CaseResult {
    assert_fixture_holds(AREA, "union_types")
}

/// Runs the fixture `unqualified_and_aliased_variant_patterns`.
#[test]
fn unqualified_and_aliased_variant_patterns() -> CaseResult {
    assert_fixture_holds(AREA, "unqualified_and_aliased_variant_patterns")
}

/// Runs the fixture `value_enums`.
#[test]
fn value_enums() -> CaseResult {
    assert_fixture_holds(AREA, "value_enums")
}
