//! @generated by `make behavior-roots` from the behavior-fixture area `emit_declarations_and_modules`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/emit_declarations_and_modules/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "emit_declarations_and_modules";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `callable_trait_accepts_functions_and_closures`.
#[test]
fn callable_trait_accepts_functions_and_closures() -> CaseResult {
    assert_fixture_holds(AREA, "callable_trait_accepts_functions_and_closures")
}

/// Runs the fixture `constructor_arguments_name_field_types_the_module_does_not_import`.
#[test]
fn constructor_arguments_name_field_types_the_module_does_not_import() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "constructor_arguments_name_field_types_the_module_does_not_import",
    )
}

/// Runs the fixture `default_argument_calls_sibling_module`.
#[test]
fn default_argument_calls_sibling_module() -> CaseResult {
    assert_fixture_holds(AREA, "default_argument_calls_sibling_module")
}

/// Runs the fixture `dependency_model_generic_method_string_args`.
#[test]
fn dependency_model_generic_method_string_args() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_model_generic_method_string_args")
}

/// Runs the fixture `imported_model_constructor_default_fill`.
#[test]
fn imported_model_constructor_default_fill() -> CaseResult {
    assert_fixture_holds(AREA, "imported_model_constructor_default_fill")
}

/// Runs the fixture `local_bindings_mutation`.
#[test]
fn local_bindings_mutation() -> CaseResult {
    assert_fixture_holds(AREA, "local_bindings_mutation")
}

/// Runs the fixture `module_qualified_field_chains_and_calls`.
#[test]
fn module_qualified_field_chains_and_calls() -> CaseResult {
    assert_fixture_holds(AREA, "module_qualified_field_chains_and_calls")
}

/// Runs the fixture `nested_module_union_enum_and_none_patterns`.
#[test]
fn nested_module_union_enum_and_none_patterns() -> CaseResult {
    assert_fixture_holds(AREA, "nested_module_union_enum_and_none_patterns")
}

/// Runs the fixture `private_default_fields_across_modules`.
#[test]
fn private_default_fields_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "private_default_fields_across_modules")
}

/// Runs the fixture `refused_colliding_static_import_aliases`.
#[test]
fn refused_colliding_static_import_aliases() -> CaseResult {
    assert_fixture_holds(AREA, "refused_colliding_static_import_aliases")
}

/// Runs the fixture `refused_required_private_field_from_another_module`.
#[test]
fn refused_required_private_field_from_another_module() -> CaseResult {
    assert_fixture_holds(AREA, "refused_required_private_field_from_another_module")
}

/// Runs the fixture `refused_value_enum_payload_variant`.
#[test]
fn refused_value_enum_payload_variant() -> CaseResult {
    assert_fixture_holds(AREA, "refused_value_enum_payload_variant")
}

/// Runs the fixture `static_collection_method_mutations`.
#[test]
fn static_collection_method_mutations() -> CaseResult {
    assert_fixture_holds(AREA, "static_collection_method_mutations")
}

/// Runs the fixture `static_list_storage_mutation`.
#[test]
fn static_list_storage_mutation() -> CaseResult {
    assert_fixture_holds(AREA, "static_list_storage_mutation")
}

/// Runs the fixture `union_debug_delegates_to_members`.
#[test]
fn union_debug_delegates_to_members() -> CaseResult {
    assert_fixture_holds(AREA, "union_debug_delegates_to_members")
}

/// Runs the fixture `user_trait_named_like_stdlib_callable`.
#[test]
fn user_trait_named_like_stdlib_callable() -> CaseResult {
    assert_fixture_holds(AREA, "user_trait_named_like_stdlib_callable")
}

/// Runs the fixture `value_enum_display_message_and_lookup`.
#[test]
fn value_enum_display_message_and_lookup() -> CaseResult {
    assert_fixture_holds(AREA, "value_enum_display_message_and_lookup")
}

/// Runs the fixture `value_enum_serde_raw_values`.
#[test]
fn value_enum_serde_raw_values() -> CaseResult {
    assert_fixture_holds(AREA, "value_enum_serde_raw_values")
}
