//! @generated by `make behavior-roots` from the behavior-fixture area `driver`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/driver/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "driver";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `module_named_like_host_keyword`.
#[test]
fn module_named_like_host_keyword() -> CaseResult {
    assert_fixture_holds(AREA, "module_named_like_host_keyword")
}

/// Runs the fixture `module_named_like_host_root_file`.
#[test]
fn module_named_like_host_root_file() -> CaseResult {
    assert_fixture_holds(AREA, "module_named_like_host_root_file")
}

/// Runs the fixture `println_multi_argument`.
#[test]
fn println_multi_argument() -> CaseResult {
    assert_fixture_holds(AREA, "println_multi_argument")
}
