//! @generated by `make behavior-roots` from the behavior-fixture area `ownership_values_and_fields`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/ownership_values_and_fields/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "ownership_values_and_fields";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `comprehension_binding_shadowing_a_parameter`.
#[test]
fn comprehension_binding_shadowing_a_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "comprehension_binding_shadowing_a_parameter")
}

/// Runs the fixture `comprehensions_changing_their_items`.
#[test]
fn comprehensions_changing_their_items() -> CaseResult {
    assert_fixture_holds(AREA, "comprehensions_changing_their_items")
}

/// Runs the fixture `dict_values_changed_in_place`.
#[test]
fn dict_values_changed_in_place() -> CaseResult {
    assert_fixture_holds(AREA, "dict_values_changed_in_place")
}

/// Runs the fixture `field_assigned_into_a_reassigned_local`.
#[test]
fn field_assigned_into_a_reassigned_local() -> CaseResult {
    assert_fixture_holds(AREA, "field_assigned_into_a_reassigned_local")
}

/// Runs the fixture `field_read_out_of_a_local`.
#[test]
fn field_read_out_of_a_local() -> CaseResult {
    assert_fixture_holds(AREA, "field_read_out_of_a_local")
}

/// Runs the fixture `generator_sources_consumed_and_reused`.
#[test]
fn generator_sources_consumed_and_reused() -> CaseResult {
    assert_fixture_holds(AREA, "generator_sources_consumed_and_reused")
}

/// Runs the fixture `loop_binding_stored_into_a_result`.
#[test]
fn loop_binding_stored_into_a_result() -> CaseResult {
    assert_fixture_holds(AREA, "loop_binding_stored_into_a_result")
}

/// Runs the fixture `loop_over_a_list_field_of_an_element`.
#[test]
fn loop_over_a_list_field_of_an_element() -> CaseResult {
    assert_fixture_holds(AREA, "loop_over_a_list_field_of_an_element")
}

/// Runs the fixture `model_value_passed_then_used_again`.
#[test]
fn model_value_passed_then_used_again() -> CaseResult {
    assert_fixture_holds(AREA, "model_value_passed_then_used_again")
}

/// Runs the fixture `mut_self_call_on_a_collection_element`.
#[test]
fn mut_self_call_on_a_collection_element() -> CaseResult {
    assert_fixture_holds(AREA, "mut_self_call_on_a_collection_element")
}

/// Runs the fixture `string_list_passed_at_last_use_and_empty_literal`.
#[test]
fn string_list_passed_at_last_use_and_empty_literal() -> CaseResult {
    assert_fixture_holds(AREA, "string_list_passed_at_last_use_and_empty_literal")
}

/// Runs the fixture `tuple_elements_changed_in_place`.
#[test]
fn tuple_elements_changed_in_place() -> CaseResult {
    assert_fixture_holds(AREA, "tuple_elements_changed_in_place")
}

/// Runs the fixture `web_extractor_field_read_at_three_sinks`.
#[test]
fn web_extractor_field_read_at_three_sinks() -> CaseResult {
    assert_fixture_holds(AREA, "web_extractor_field_read_at_three_sinks")
}
