//! @generated by `make behavior-roots` from the behavior-fixture area `lowering_expressions`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/lowering_expressions/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "lowering_expressions";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `callable_trait_local_versus_std`.
#[test]
fn callable_trait_local_versus_std() -> CaseResult {
    assert_fixture_holds(AREA, "callable_trait_local_versus_std")
}

/// Runs the fixture `clone_dispatch_with_std_import`.
#[test]
fn clone_dispatch_with_std_import() -> CaseResult {
    assert_fixture_holds(AREA, "clone_dispatch_with_std_import")
}

/// Runs the fixture `decorator_declared_surface_issue1453`.
#[test]
fn decorator_declared_surface_issue1453() -> CaseResult {
    assert_fixture_holds(AREA, "decorator_declared_surface_issue1453")
}

/// Runs the fixture `empty_list_argument_takes_instantiated_element_type`.
#[test]
fn empty_list_argument_takes_instantiated_element_type() -> CaseResult {
    assert_fixture_holds(AREA, "empty_list_argument_takes_instantiated_element_type")
}

/// Runs the fixture `integer_literal_takes_float_type_in_more_slots`.
#[test]
fn integer_literal_takes_float_type_in_more_slots() -> CaseResult {
    assert_fixture_holds(AREA, "integer_literal_takes_float_type_in_more_slots")
}

/// Runs the fixture `integer_literal_written_to_float_element`.
#[test]
fn integer_literal_written_to_float_element() -> CaseResult {
    assert_fixture_holds(AREA, "integer_literal_written_to_float_element")
}

/// Runs the fixture `iterator_adapter_surface`.
#[test]
fn iterator_adapter_surface() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_adapter_surface")
}

/// Runs the fixture `json_protocol_dispatch`.
#[test]
fn json_protocol_dispatch() -> CaseResult {
    assert_fixture_holds(AREA, "json_protocol_dispatch")
}

/// Runs the fixture `method_partial_mutating_receiver`.
#[test]
fn method_partial_mutating_receiver() -> CaseResult {
    assert_fixture_holds(AREA, "method_partial_mutating_receiver")
}

/// Runs the fixture `native_clone_on_union_and_option_fields`.
#[test]
fn native_clone_on_union_and_option_fields() -> CaseResult {
    assert_fixture_holds(AREA, "native_clone_on_union_and_option_fields")
}

/// Runs the fixture `option_str_unwrap_or_with_str_binding`.
#[test]
fn option_str_unwrap_or_with_str_binding() -> CaseResult {
    assert_fixture_holds(AREA, "option_str_unwrap_or_with_str_binding")
}

/// Runs the fixture `overloaded_stdlib_call_selection`.
#[test]
fn overloaded_stdlib_call_selection() -> CaseResult {
    assert_fixture_holds(AREA, "overloaded_stdlib_call_selection")
}

/// Runs the fixture `receiver_aware_method_kinds_issue1668`.
#[test]
fn receiver_aware_method_kinds_issue1668() -> CaseResult {
    assert_fixture_holds(AREA, "receiver_aware_method_kinds_issue1668")
}

/// Runs the fixture `refused_empty_list_argument_leaving_type_parameter_open`.
#[test]
fn refused_empty_list_argument_leaving_type_parameter_open() -> CaseResult {
    assert_fixture_holds(AREA, "refused_empty_list_argument_leaving_type_parameter_open")
}

/// Runs the fixture `refused_function_named_like_a_decorated_original`.
#[test]
fn refused_function_named_like_a_decorated_original() -> CaseResult {
    assert_fixture_holds(AREA, "refused_function_named_like_a_decorated_original")
}

/// Runs the fixture `result_method_surface`.
#[test]
fn result_method_surface() -> CaseResult {
    assert_fixture_holds(AREA, "result_method_surface")
}

/// Runs the fixture `source_partial_keeps_declaration_defaults_issue701`.
#[test]
fn source_partial_keeps_declaration_defaults_issue701() -> CaseResult {
    assert_fixture_holds(AREA, "source_partial_keeps_declaration_defaults_issue701")
}

/// Runs the fixture `stdlib_trait_dispatch_across_package`.
#[test]
fn stdlib_trait_dispatch_across_package() -> CaseResult {
    assert_fixture_holds(AREA, "stdlib_trait_dispatch_across_package")
}

/// Runs the fixture `trait_dispatch_receiver_shapes`.
#[test]
fn trait_dispatch_receiver_shapes() -> CaseResult {
    assert_fixture_holds(AREA, "trait_dispatch_receiver_shapes")
}

/// Runs the fixture `trait_typed_receivers`.
#[test]
fn trait_typed_receivers() -> CaseResult {
    assert_fixture_holds(AREA, "trait_typed_receivers")
}

/// Runs the fixture `user_methods_named_like_builtins`.
#[test]
fn user_methods_named_like_builtins() -> CaseResult {
    assert_fixture_holds(AREA, "user_methods_named_like_builtins")
}

/// Runs the fixture `value_assigned_to_nested_option_binding`.
#[test]
fn value_assigned_to_nested_option_binding() -> CaseResult {
    assert_fixture_holds(AREA, "value_assigned_to_nested_option_binding")
}

/// Runs the fixture `value_written_to_option_place_is_wrapped`.
#[test]
fn value_written_to_option_place_is_wrapped() -> CaseResult {
    assert_fixture_holds(AREA, "value_written_to_option_place_is_wrapped")
}
