//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_newtypes_and_serde`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_newtypes_and_serde/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_newtypes_and_serde";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `bare_json_protocol_bounds`.
#[test]
fn bare_json_protocol_bounds() -> CaseResult {
    assert_fixture_holds(AREA, "bare_json_protocol_bounds")
}

/// Runs the fixture `constrained_newtype_validation`.
#[test]
fn constrained_newtype_validation() -> CaseResult {
    assert_fixture_holds(AREA, "constrained_newtype_validation")
}

/// Runs the fixture `direct_json_trait_import_across_modules`.
#[test]
fn direct_json_trait_import_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "direct_json_trait_import_across_modules")
}

/// Runs the fixture `facade_reexported_serde_traits`.
#[test]
fn facade_reexported_serde_traits() -> CaseResult {
    assert_fixture_holds(AREA, "facade_reexported_serde_traits")
}

/// Runs the fixture `index_trait_adoption`.
#[test]
fn index_trait_adoption() -> CaseResult {
    assert_fixture_holds(AREA, "index_trait_adoption")
}

/// Runs the fixture `json_protocol_supertraits`.
#[test]
fn json_protocol_supertraits() -> CaseResult {
    assert_fixture_holds(AREA, "json_protocol_supertraits")
}

/// Runs the fixture `json_value_indexing`.
#[test]
fn json_value_indexing() -> CaseResult {
    assert_fixture_holds(AREA, "json_value_indexing")
}

/// Runs the fixture `local_serde_named_marker_traits`.
#[test]
fn local_serde_named_marker_traits() -> CaseResult {
    assert_fixture_holds(AREA, "local_serde_named_marker_traits")
}

/// Runs the fixture `newtype_builder_methods`.
#[test]
fn newtype_builder_methods() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_builder_methods")
}

/// Runs the fixture `newtype_checked_construction`.
#[test]
fn newtype_checked_construction() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_checked_construction")
}

/// Runs the fixture `newtype_generic`.
#[test]
fn newtype_generic() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_generic")
}

/// Runs the fixture `newtype_implicit_coercion`.
#[test]
fn newtype_implicit_coercion() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_implicit_coercion")
}

/// Runs the fixture `newtype_json_validation`.
#[test]
fn newtype_json_validation() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_json_validation")
}

/// Runs the fixture `newtype_with_serialize_trait`.
#[test]
fn newtype_with_serialize_trait() -> CaseResult {
    assert_fixture_holds(AREA, "newtype_with_serialize_trait")
}

/// Runs the fixture `partial_alias_derive`.
#[test]
fn partial_alias_derive() -> CaseResult {
    assert_fixture_holds(AREA, "partial_alias_derive")
}

/// Runs the fixture `qualified_json_derives`.
#[test]
fn qualified_json_derives() -> CaseResult {
    assert_fixture_holds(AREA, "qualified_json_derives")
}

/// Runs the fixture `qualified_json_trait_dispatch`.
#[test]
fn qualified_json_trait_dispatch() -> CaseResult {
    assert_fixture_holds(AREA, "qualified_json_trait_dispatch")
}

/// Runs the fixture `serde_module_qualified_json_traits`.
#[test]
fn serde_module_qualified_json_traits() -> CaseResult {
    assert_fixture_holds(AREA, "serde_module_qualified_json_traits")
}

/// Runs the fixture `serialize_trait_adoption`.
#[test]
fn serialize_trait_adoption() -> CaseResult {
    assert_fixture_holds(AREA, "serialize_trait_adoption")
}

/// Runs the fixture `user_module_derivables`.
#[test]
fn user_module_derivables() -> CaseResult {
    assert_fixture_holds(AREA, "user_module_derivables")
}
