//! @generated by `make behavior-roots` from the behavior-fixture area `execution_collections`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/execution_collections/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::{assert_fixture_holds, assert_pending_fixtures_still_wait};

/// The area every case of this root runs a fixture of.
const AREA: &str = "execution_collections";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `canonical_sorted_evaluates_its_operand_once`.
#[test]
fn canonical_sorted_evaluates_its_operand_once() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_sorted_evaluates_its_operand_once")
}

/// Runs the fixture `canonical_sorted_returns_a_fresh_ordered_integer_list`.
#[test]
fn canonical_sorted_returns_a_fresh_ordered_integer_list() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_sorted_returns_a_fresh_ordered_integer_list")
}

/// Runs the fixture `cli_executes_enumerate_and_zip_without_fallback`.
#[test]
fn cli_executes_enumerate_and_zip_without_fallback() -> CaseResult {
    assert_fixture_holds(AREA, "cli_executes_enumerate_and_zip_without_fallback")
}

/// Runs the fixture `cli_refuses_nonlist_enumerate_without_a_successful_receipt`.
#[test]
fn cli_refuses_nonlist_enumerate_without_a_successful_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "cli_refuses_nonlist_enumerate_without_a_successful_receipt")
}

/// Runs the fixture `collection_len_cli_publishes_its_result_and_receipt`.
#[test]
fn collection_len_cli_publishes_its_result_and_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "collection_len_cli_publishes_its_result_and_receipt")
}

/// Runs the fixture `collection_len_evaluates_its_operand_once`.
#[test]
fn collection_len_evaluates_its_operand_once() -> CaseResult {
    assert_fixture_holds(AREA, "collection_len_evaluates_its_operand_once")
}

/// Runs the fixture `collection_len_matches_the_receipt_backed_native_route`.
#[test]
fn collection_len_matches_the_receipt_backed_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "collection_len_matches_the_receipt_backed_native_route")
}

/// Runs the fixture `concrete_unit_set_keys_execute`.
#[test]
fn concrete_unit_set_keys_execute() -> CaseResult {
    assert_fixture_holds(AREA, "concrete_unit_set_keys_execute")
}

/// Runs the fixture `empty_sorted_list_remains_an_original_call_span_refusal`.
#[test]
fn empty_sorted_list_remains_an_original_call_span_refusal() -> CaseResult {
    assert_fixture_holds(AREA, "empty_sorted_list_remains_an_original_call_span_refusal")
}

/// Runs the fixture `enumerate_and_zip_follow_bare_local_aliases`.
#[test]
fn enumerate_and_zip_follow_bare_local_aliases() -> CaseResult {
    assert_fixture_holds(AREA, "enumerate_and_zip_follow_bare_local_aliases")
}

/// Runs the fixture `enumerate_lists_are_zero_based_and_preserve_tuple_forms`.
#[test]
fn enumerate_lists_are_zero_based_and_preserve_tuple_forms() -> CaseResult {
    assert_fixture_holds(AREA, "enumerate_lists_are_zero_based_and_preserve_tuple_forms")
}

/// Runs the fixture `executes_a_closure_that_captures_canonical_zip`.
#[test]
fn executes_a_closure_that_captures_canonical_zip() -> CaseResult {
    assert_fixture_holds(AREA, "executes_a_closure_that_captures_canonical_zip")
}

/// Runs the fixture `executes_both_set_membership_forms`.
#[test]
fn executes_both_set_membership_forms() -> CaseResult {
    assert_fixture_holds(AREA, "executes_both_set_membership_forms")
}

/// Runs the fixture `executes_deferred_enumerate_and_zip_frames_with_distinct_bindings`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn executes_deferred_enumerate_and_zip_frames_with_distinct_bindings() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_deferred_enumerate_and_zip_frames_with_distinct_bindings",
    )
}

/// Runs the fixture `executes_explicit_builtin_namespace_enumerate`.
#[test]
fn executes_explicit_builtin_namespace_enumerate() -> CaseResult {
    assert_fixture_holds(AREA, "executes_explicit_builtin_namespace_enumerate")
}

/// Runs the fixture `executes_later_generator_clauses_over_captured_enumerate_and_zip`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn executes_later_generator_clauses_over_captured_enumerate_and_zip() -> CaseResult {
    assert_fixture_holds(AREA, "executes_later_generator_clauses_over_captured_enumerate_and_zip")
}

/// Runs the fixture `executes_scalar_tuple_collection_destructuring_with_a_replacement_rece`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn executes_scalar_tuple_collection_destructuring_with_a_replacement_rece() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_scalar_tuple_collection_destructuring_with_a_replacement_rece",
    )
}

/// Runs the fixture `executes_zip_with_recursively_structural_nested_lists_and_tuples`.
#[test]
fn executes_zip_with_recursively_structural_nested_lists_and_tuples() -> CaseResult {
    assert_fixture_holds(AREA, "executes_zip_with_recursively_structural_nested_lists_and_tuples")
}

/// Runs the fixture `hashed_construction_preserves_source_side_effect_order`.
#[test]
fn hashed_construction_preserves_source_side_effect_order() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_construction_preserves_source_side_effect_order")
}

/// Runs the fixture `hashed_container_equality_remains_an_original_span_refusal`.
#[test]
fn hashed_container_equality_remains_an_original_span_refusal() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_container_equality_remains_an_original_span_refusal")
}

/// Runs the fixture `hashed_container_equality_remains_an_original_span_refusal_2`.
#[test]
fn hashed_container_equality_remains_an_original_span_refusal_2() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_container_equality_remains_an_original_span_refusal_2")
}

/// Runs the fixture `hashed_membership_matches_the_receipt_backed_native_route`.
#[test]
fn hashed_membership_matches_the_receipt_backed_native_route() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_membership_matches_the_receipt_backed_native_route")
}

/// Runs the fixture `hashed_membership_publishes_a_replacement_receipt`.
#[test]
fn hashed_membership_publishes_a_replacement_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_membership_publishes_a_replacement_receipt")
}

/// Runs the fixture `hashed_non_membership_operations_remain_refused`.
#[test]
fn hashed_non_membership_operations_remain_refused() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_non_membership_operations_remain_refused")
}

/// Runs the fixture `hashed_non_membership_operations_remain_refused_2`.
#[test]
fn hashed_non_membership_operations_remain_refused_2() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_non_membership_operations_remain_refused_2")
}

/// Runs the fixture `hashed_non_membership_operations_remain_refused_3`.
#[test]
fn hashed_non_membership_operations_remain_refused_3() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_non_membership_operations_remain_refused_3")
}

/// Runs the fixture `hashed_non_membership_operations_remain_refused_4`.
#[test]
fn hashed_non_membership_operations_remain_refused_4() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_non_membership_operations_remain_refused_4")
}

/// Runs the fixture `hashed_non_membership_operations_remain_refused_5`.
#[test]
fn hashed_non_membership_operations_remain_refused_5() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_non_membership_operations_remain_refused_5")
}

/// Runs the fixture `hashed_non_membership_operations_remain_refused_6`.
#[test]
fn hashed_non_membership_operations_remain_refused_6() -> CaseResult {
    assert_fixture_holds(AREA, "hashed_non_membership_operations_remain_refused_6")
}

/// Runs the fixture `list_argument_order_and_iterator_aliases_match_native`.
#[test]
fn list_argument_order_and_iterator_aliases_match_native() -> CaseResult {
    assert_fixture_holds(AREA, "list_argument_order_and_iterator_aliases_match_native")
}

/// Runs the fixture `missing_sorted_identity_refuses_instead_of_guessing_from_its_name`.
#[test]
fn missing_sorted_identity_refuses_instead_of_guessing_from_its_name() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "missing_sorted_identity_refuses_instead_of_guessing_from_its_name",
    )
}

/// Runs the fixture `non_scalar_hashed_key_types_refuse_at_construction`.
#[test]
fn non_scalar_hashed_key_types_refuse_at_construction() -> CaseResult {
    assert_fixture_holds(AREA, "non_scalar_hashed_key_types_refuse_at_construction")
}

/// Runs the fixture `non_scalar_hashed_key_types_refuse_at_construction_2`.
#[test]
fn non_scalar_hashed_key_types_refuse_at_construction_2() -> CaseResult {
    assert_fixture_holds(AREA, "non_scalar_hashed_key_types_refuse_at_construction_2")
}

/// Runs the fixture `preserves_same_spelled_source_enumerate_and_zip_functions`.
#[test]
fn preserves_same_spelled_source_enumerate_and_zip_functions() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_same_spelled_source_enumerate_and_zip_functions")
}

/// Runs the fixture `preserves_source_defined_zip_over_the_global_builtin_spelling`.
#[test]
fn preserves_source_defined_zip_over_the_global_builtin_spelling() -> CaseResult {
    assert_fixture_holds(AREA, "preserves_source_defined_zip_over_the_global_builtin_spelling")
}

/// Runs the fixture `projected_nested_structural_lists_match_native`.
#[test]
fn projected_nested_structural_lists_match_native() -> CaseResult {
    assert_fixture_holds(AREA, "projected_nested_structural_lists_match_native")
}

/// Runs the fixture `refuses_a_zip_alias_with_a_corrupted_checked_iterator_type`.
#[test]
fn refuses_a_zip_alias_with_a_corrupted_checked_iterator_type() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_a_zip_alias_with_a_corrupted_checked_iterator_type")
}

/// Runs the fixture `refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de`.
#[test]
fn refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de",
    )
}

/// Runs the fixture `refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_2`.
#[test]
fn refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_2",
    )
}

/// Runs the fixture `refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_3`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_3",
    )
}

/// Runs the fixture `refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_4`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_4() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_4",
    )
}

/// Runs the fixture `refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_5`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_5() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_corrupted_enumerate_iter_next_destinations_in_top_level_and_de_5",
    )
}

/// Runs the fixture `refuses_corrupted_zip_operand_and_nominal_iterator_destination`.
#[test]
fn refuses_corrupted_zip_operand_and_nominal_iterator_destination() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_corrupted_zip_operand_and_nominal_iterator_destination")
}

/// Runs the fixture `refuses_enumerate_spread_at_the_original_call_span`.
#[test]
fn refuses_enumerate_spread_at_the_original_call_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_enumerate_spread_at_the_original_call_span")
}

/// Runs the fixture `refuses_enumerate_without_its_checked_builtin_identity`.
#[test]
fn refuses_enumerate_without_its_checked_builtin_identity() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_enumerate_without_its_checked_builtin_identity")
}

/// Runs the fixture `refuses_malformed_enumerate_arity_without_a_successful_execution`.
#[test]
fn refuses_malformed_enumerate_arity_without_a_successful_execution() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_malformed_enumerate_arity_without_a_successful_execution")
}

/// Runs the fixture `refuses_malformed_enumerate_arity_without_a_successful_execution_2`.
#[test]
fn refuses_malformed_enumerate_arity_without_a_successful_execution_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_malformed_enumerate_arity_without_a_successful_execution_2",
    )
}

/// Runs the fixture `refuses_nonlist_enumerate_at_the_original_call_span`.
#[test]
fn refuses_nonlist_enumerate_at_the_original_call_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_nonlist_enumerate_at_the_original_call_span")
}

/// Runs the fixture `refuses_zip_shape_boundaries_at_the_original_source_span`.
#[test]
fn refuses_zip_shape_boundaries_at_the_original_source_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_shape_boundaries_at_the_original_source_span")
}

/// Runs the fixture `refuses_zip_shape_boundaries_at_the_original_source_span_2`.
#[test]
fn refuses_zip_shape_boundaries_at_the_original_source_span_2() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_shape_boundaries_at_the_original_source_span_2")
}

/// Runs the fixture `refuses_zip_shape_boundaries_at_the_original_source_span_2_2`.
#[test]
fn refuses_zip_shape_boundaries_at_the_original_source_span_2_2() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_shape_boundaries_at_the_original_source_span_2_2")
}

/// Runs the fixture `refuses_zip_shape_boundaries_at_the_original_source_span_3`.
#[test]
fn refuses_zip_shape_boundaries_at_the_original_source_span_3() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_shape_boundaries_at_the_original_source_span_3")
}

/// Runs the fixture `refuses_zip_shape_boundaries_at_the_original_source_span_3_2`.
#[test]
fn refuses_zip_shape_boundaries_at_the_original_source_span_3_2() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_shape_boundaries_at_the_original_source_span_3_2")
}

/// Runs the fixture `refuses_zip_shape_boundaries_at_the_original_source_span_4`.
#[test]
fn refuses_zip_shape_boundaries_at_the_original_source_span_4() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_shape_boundaries_at_the_original_source_span_4")
}

/// Runs the fixture `refuses_zip_without_its_checked_builtin_identity`.
#[test]
fn refuses_zip_without_its_checked_builtin_identity() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_zip_without_its_checked_builtin_identity")
}

/// Runs the fixture `scalar_set_key_kinds_execute`.
#[test]
fn scalar_set_key_kinds_execute() -> CaseResult {
    assert_fixture_holds(AREA, "scalar_set_key_kinds_execute")
}

/// Runs the fixture `scalar_set_key_kinds_execute_2`.
#[test]
fn scalar_set_key_kinds_execute_2() -> CaseResult {
    assert_fixture_holds(AREA, "scalar_set_key_kinds_execute_2")
}

/// Runs the fixture `scalar_set_key_kinds_execute_3`.
#[test]
fn scalar_set_key_kinds_execute_3() -> CaseResult {
    assert_fixture_holds(AREA, "scalar_set_key_kinds_execute_3")
}

/// Runs the fixture `selected_enumerate_and_zip_match_through_the_staged_legacy_route`.
#[test]
fn selected_enumerate_and_zip_match_through_the_staged_legacy_route() -> CaseResult {
    assert_fixture_holds(AREA, "selected_enumerate_and_zip_match_through_the_staged_legacy_route")
}

/// Runs the fixture `set_and_dict_len_execute_from_canonical_builtin_identity`.
#[test]
fn set_and_dict_len_execute_from_canonical_builtin_identity() -> CaseResult {
    assert_fixture_holds(AREA, "set_and_dict_len_execute_from_canonical_builtin_identity")
}

/// Runs the fixture `set_and_dict_membership_execute_from_retained_helper_calls`.
#[test]
fn set_and_dict_membership_execute_from_retained_helper_calls() -> CaseResult {
    assert_fixture_holds(AREA, "set_and_dict_membership_execute_from_retained_helper_calls")
}

/// Runs the fixture `sorted_int_list_cli_publishes_its_result_and_receipt`.
#[test]
fn sorted_int_list_cli_publishes_its_result_and_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "sorted_int_list_cli_publishes_its_result_and_receipt")
}

/// Runs the fixture `source_local_sorted_keeps_its_declaration_identity`.
#[test]
fn source_local_sorted_keeps_its_declaration_identity() -> CaseResult {
    assert_fixture_holds(AREA, "source_local_sorted_keeps_its_declaration_identity")
}

/// Runs the fixture `string_sorted_list_remains_an_original_call_span_refusal`.
#[test]
fn string_sorted_list_remains_an_original_call_span_refusal() -> CaseResult {
    assert_fixture_holds(AREA, "string_sorted_list_remains_an_original_call_span_refusal")
}

/// Runs the fixture `typed_empty_dict_constructor_membership_executes`.
#[test]
fn typed_empty_dict_constructor_membership_executes() -> CaseResult {
    assert_fixture_holds(AREA, "typed_empty_dict_constructor_membership_executes")
}

/// Runs the fixture `typed_empty_dict_membership_executes`.
#[test]
fn typed_empty_dict_membership_executes() -> CaseResult {
    assert_fixture_holds(AREA, "typed_empty_dict_membership_executes")
}

/// Runs the fixture `typed_empty_set_membership_executes`.
#[test]
fn typed_empty_set_membership_executes() -> CaseResult {
    assert_fixture_holds(AREA, "typed_empty_set_membership_executes")
}

/// Runs the fixture `zip_alias_and_original_each_match_native`.
#[test]
fn zip_alias_and_original_each_match_native() -> CaseResult {
    assert_fixture_holds(AREA, "zip_alias_and_original_each_match_native")
}

/// Runs the fixture `zip_alias_and_original_each_match_native_2`.
#[test]
fn zip_alias_and_original_each_match_native_2() -> CaseResult {
    assert_fixture_holds(AREA, "zip_alias_and_original_each_match_native_2")
}

/// Runs the fixture `zip_alias_assignment_preserves_both_source_values`.
#[test]
fn zip_alias_assignment_preserves_both_source_values() -> CaseResult {
    assert_fixture_holds(AREA, "zip_alias_assignment_preserves_both_source_values")
}

/// Runs the fixture `zip_alias_assignment_preserves_both_source_values_2`.
#[test]
fn zip_alias_assignment_preserves_both_source_values_2() -> CaseResult {
    assert_fixture_holds(AREA, "zip_alias_assignment_preserves_both_source_values_2")
}

/// Runs the fixture `zip_equal_unequal_and_empty_lists_match_native`.
#[test]
fn zip_equal_unequal_and_empty_lists_match_native() -> CaseResult {
    assert_fixture_holds(AREA, "zip_equal_unequal_and_empty_lists_match_native")
}

/// Runs the fixture `zip_evaluates_list_returning_sibling_arguments_in_written_order`.
#[test]
fn zip_evaluates_list_returning_sibling_arguments_in_written_order() -> CaseResult {
    assert_fixture_holds(AREA, "zip_evaluates_list_returning_sibling_arguments_in_written_order")
}

/// Runs the fixture `zip_lists_cover_equal_unequal_and_empty_inputs`.
#[test]
fn zip_lists_cover_equal_unequal_and_empty_inputs() -> CaseResult {
    assert_fixture_holds(AREA, "zip_lists_cover_equal_unequal_and_empty_inputs")
}

/// Runs the fixture `zip_repeated_binding_retains_source_consumption_error`.
#[test]
fn zip_repeated_binding_retains_source_consumption_error() -> CaseResult {
    assert_fixture_holds(AREA, "zip_repeated_binding_retains_source_consumption_error")
}

/// Runs the fixture `zip_repeated_binding_retains_source_consumption_error_2`.
#[test]
fn zip_repeated_binding_retains_source_consumption_error_2() -> CaseResult {
    assert_fixture_holds(AREA, "zip_repeated_binding_retains_source_consumption_error_2")
}

/// Every `pending:` fixture of the area still does not show what it declares.
#[test]
fn pending_fixtures_still_wait() -> CaseResult {
    assert_pending_fixtures_still_wait(AREA)
}
