//! @generated by `make behavior-roots` from the behavior-fixture area `codegen_functions_and_aliases`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/codegen_functions_and_aliases/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "codegen_functions_and_aliases";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `callable_aliases`.
#[test]
fn callable_aliases() -> CaseResult {
    assert_fixture_holds(AREA, "callable_aliases")
}

/// Runs the fixture `closure_shapes_call_local_functions`.
#[test]
fn closure_shapes_call_local_functions() -> CaseResult {
    assert_fixture_holds(AREA, "closure_shapes_call_local_functions")
}

/// Runs the fixture `decorator_generated_name_collisions`.
#[test]
fn decorator_generated_name_collisions() -> CaseResult {
    assert_fixture_holds(AREA, "decorator_generated_name_collisions")
}

/// Runs the fixture `eq_magic_method`.
#[test]
fn eq_magic_method() -> CaseResult {
    assert_fixture_holds(AREA, "eq_magic_method")
}

/// Runs the fixture `explicit_type_arguments`.
#[test]
fn explicit_type_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "explicit_type_arguments")
}

/// Runs the fixture `local_partials_of_methods_of_values`.
#[test]
fn local_partials_of_methods_of_values() -> CaseResult {
    assert_fixture_holds(AREA, "local_partials_of_methods_of_values")
}

/// Runs the fixture `overloaded_functions`.
#[test]
fn overloaded_functions() -> CaseResult {
    assert_fixture_holds(AREA, "overloaded_functions")
}

/// Runs the fixture `partial_function_presets`.
#[test]
fn partial_function_presets() -> CaseResult {
    assert_fixture_holds(AREA, "partial_function_presets")
}

/// Runs the fixture `partial_methods`.
#[test]
fn partial_methods() -> CaseResult {
    assert_fixture_holds(AREA, "partial_methods")
}

/// Runs the fixture `partial_model_constructor`.
#[test]
fn partial_model_constructor() -> CaseResult {
    assert_fixture_holds(AREA, "partial_model_constructor")
}

/// Runs the fixture `result_map_err_closures`.
#[test]
fn result_map_err_closures() -> CaseResult {
    assert_fixture_holds(AREA, "result_map_err_closures")
}

/// Runs the fixture `static_binding_shadowed_by_local`.
#[test]
fn static_binding_shadowed_by_local() -> CaseResult {
    assert_fixture_holds(AREA, "static_binding_shadowed_by_local")
}

/// Runs the fixture `static_counter_projection`.
#[test]
fn static_counter_projection() -> CaseResult {
    assert_fixture_holds(AREA, "static_counter_projection")
}

/// Runs the fixture `trait_method_alias_adopts_required_method`.
#[test]
fn trait_method_alias_adopts_required_method() -> CaseResult {
    assert_fixture_holds(AREA, "trait_method_alias_adopts_required_method")
}

/// Runs the fixture `unused_declarations_run`.
#[test]
fn unused_declarations_run() -> CaseResult {
    assert_fixture_holds(AREA, "unused_declarations_run")
}
