//! @generated by `make behavior-roots` from the behavior-fixture area `execution_scalars_and_bodies`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/execution_scalars_and_bodies/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::{assert_fixture_holds, assert_pending_fixtures_still_wait};

/// The area every case of this root runs a fixture of.
const AREA: &str = "execution_scalars_and_bodies";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `a_model_with_a_float_field`.
#[test]
fn a_model_with_a_float_field() -> CaseResult {
    assert_fixture_holds(AREA, "a_model_with_a_float_field")
}

/// Runs the fixture `a_program_activating_std_async_under_an_alias`.
#[test]
fn a_program_activating_std_async_under_an_alias() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_activating_std_async_under_an_alias")
}

/// Runs the fixture `a_program_binding_a_rust_module`.
#[test]
fn a_program_binding_a_rust_module() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_binding_a_rust_module")
}

/// Runs the fixture `a_program_declaring_a_class`.
#[test]
fn a_program_declaring_a_class() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_declaring_a_class")
}

/// Runs the fixture `a_program_declaring_a_field_alias`.
#[test]
fn a_program_declaring_a_field_alias() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_declaring_a_field_alias")
}

/// Runs the fixture `a_program_declaring_a_generic_model`.
#[test]
fn a_program_declaring_a_generic_model() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_declaring_a_generic_model")
}

/// Runs the fixture `a_program_declaring_a_model_method`.
#[test]
fn a_program_declaring_a_model_method() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_declaring_a_model_method")
}

/// Runs the fixture `a_program_declaring_a_model_property`.
#[test]
fn a_program_declaring_a_model_property() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_declaring_a_model_property")
}

/// Runs the fixture `a_program_declaring_a_payload_enum`.
#[test]
fn a_program_declaring_a_payload_enum() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_declaring_a_payload_enum")
}

/// Runs the fixture `a_program_importing_a_rust_crate`.
#[test]
fn a_program_importing_a_rust_crate() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_importing_a_rust_crate")
}

/// Runs the fixture `a_program_importing_a_rust_item`.
#[test]
fn a_program_importing_a_rust_item() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_importing_a_rust_item")
}

/// Runs the fixture `a_program_importing_from_std_async_time`.
#[test]
fn a_program_importing_from_std_async_time() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_importing_from_std_async_time")
}

/// Runs the fixture `a_program_importing_std_io`.
#[test]
fn a_program_importing_std_io() -> CaseResult {
    assert_fixture_holds(AREA, "a_program_importing_std_io")
}

/// Runs the fixture `a_range_argument_for_a_list_parameter`.
#[test]
#[ignore = "pending: the checker types `range(..)` as `List[int]` and the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn a_range_argument_for_a_list_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "a_range_argument_for_a_list_parameter")
}

/// Runs the fixture `a_scalar_profile_compares_program_streams_and_typed_result`.
#[test]
fn a_scalar_profile_compares_program_streams_and_typed_result() -> CaseResult {
    assert_fixture_holds(AREA, "a_scalar_profile_compares_program_streams_and_typed_result")
}

/// Runs the fixture `a_source_outside_the_replacement_profile_stays_unavailable`.
#[test]
fn a_source_outside_the_replacement_profile_stays_unavailable() -> CaseResult {
    assert_fixture_holds(AREA, "a_source_outside_the_replacement_profile_stays_unavailable")
}

/// Runs the fixture `a_string_profile_retains_its_exact_typed_value`.
#[test]
fn a_string_profile_retains_its_exact_typed_value() -> CaseResult {
    assert_fixture_holds(AREA, "a_string_profile_retains_its_exact_typed_value")
}

/// Runs the fixture `abs_and_sum_overflow_are_always_checked`.
#[test]
fn abs_and_sum_overflow_are_always_checked() -> CaseResult {
    assert_fixture_holds(AREA, "abs_and_sum_overflow_are_always_checked")
}

/// Runs the fixture `abs_and_sum_overflow_are_always_checked_2`.
#[test]
fn abs_and_sum_overflow_are_always_checked_2() -> CaseResult {
    assert_fixture_holds(AREA, "abs_and_sum_overflow_are_always_checked_2")
}

/// Runs the fixture `abs_and_sum_overflow_are_always_checked_2_2`.
#[test]
fn abs_and_sum_overflow_are_always_checked_2_2() -> CaseResult {
    assert_fixture_holds(AREA, "abs_and_sum_overflow_are_always_checked_2_2")
}

/// Runs the fixture `abs_and_sum_overflow_are_always_checked_3`.
#[test]
fn abs_and_sum_overflow_are_always_checked_3() -> CaseResult {
    assert_fixture_holds(AREA, "abs_and_sum_overflow_are_always_checked_3")
}

/// Runs the fixture `abs_and_sum_safe_values_execute_normally`.
#[test]
fn abs_and_sum_safe_values_execute_normally() -> CaseResult {
    assert_fixture_holds(AREA, "abs_and_sum_safe_values_execute_normally")
}

/// Runs the fixture `assertion_failure_preserves_prior_stdout_and_reports_stderr_divergence`.
#[test]
fn assertion_failure_preserves_prior_stdout_and_reports_stderr_divergence() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "assertion_failure_preserves_prior_stdout_and_reports_stderr_divergence",
    )
}

/// Runs the fixture `assertion_failure_preserves_prior_stdout_and_reports_stderr_divergence_2`.
#[test]
fn assertion_failure_preserves_prior_stdout_and_reports_stderr_divergence_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "assertion_failure_preserves_prior_stdout_and_reports_stderr_divergence_2",
    )
}

/// Runs the fixture `bool_truthiness_cli_publishes_its_result_and_receipt`.
#[test]
fn bool_truthiness_cli_publishes_its_result_and_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "bool_truthiness_cli_publishes_its_result_and_receipt")
}

/// Runs the fixture `canonical_bool_evaluates_its_operand_once`.
#[test]
fn canonical_bool_evaluates_its_operand_once() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_bool_evaluates_its_operand_once")
}

/// Runs the fixture `canonical_bool_executes_bounded_scalar_and_structural_truthiness`.
#[test]
fn canonical_bool_executes_bounded_scalar_and_structural_truthiness() -> CaseResult {
    assert_fixture_holds(AREA, "canonical_bool_executes_bounded_scalar_and_structural_truthiness")
}

/// Runs the fixture `cli_release_contract_still_reports_checked_sum_overflow`.
#[test]
fn cli_release_contract_still_reports_checked_sum_overflow() -> CaseResult {
    assert_fixture_holds(AREA, "cli_release_contract_still_reports_checked_sum_overflow")
}

/// Runs the fixture `division_failure_preserves_prior_stdout_and_reports_stderr_divergence`.
#[test]
fn division_failure_preserves_prior_stdout_and_reports_stderr_divergence() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "division_failure_preserves_prior_stdout_and_reports_stderr_divergence",
    )
}

/// Runs the fixture `division_failure_preserves_prior_stdout_and_reports_stderr_divergence_2`.
#[test]
fn division_failure_preserves_prior_stdout_and_reports_stderr_divergence_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "division_failure_preserves_prior_stdout_and_reports_stderr_divergence_2",
    )
}

/// Runs the fixture `entrypoint_requires_one_canonical_free_function`.
#[test]
fn entrypoint_requires_one_canonical_free_function() -> CaseResult {
    assert_fixture_holds(AREA, "entrypoint_requires_one_canonical_free_function")
}

/// Runs the fixture `executes_core_body_and_binds_a_real_receipt`.
#[test]
fn executes_core_body_and_binds_a_real_receipt() -> CaseResult {
    assert_fixture_holds(AREA, "executes_core_body_and_binds_a_real_receipt")
}

/// Runs the fixture `executes_let_shadowing_by_local_identity`.
#[test]
fn executes_let_shadowing_by_local_identity() -> CaseResult {
    assert_fixture_holds(AREA, "executes_let_shadowing_by_local_identity")
}

/// Runs the fixture `executes_mut_shadowing_by_local_identity`.
#[test]
fn executes_mut_shadowing_by_local_identity() -> CaseResult {
    assert_fixture_holds(AREA, "executes_mut_shadowing_by_local_identity")
}

/// Runs the fixture `executes_plain_collection_index_projection`.
#[test]
fn executes_plain_collection_index_projection() -> CaseResult {
    assert_fixture_holds(AREA, "executes_plain_collection_index_projection")
}

/// Runs the fixture `executes_plain_scalar_tuple_collection_loop`.
#[test]
fn executes_plain_scalar_tuple_collection_loop() -> CaseResult {
    assert_fixture_holds(AREA, "executes_plain_scalar_tuple_collection_loop")
}

/// Runs the fixture `executes_reassignment_without_a_repeated_user_binding_name`.
#[test]
fn executes_reassignment_without_a_repeated_user_binding_name() -> CaseResult {
    assert_fixture_holds(AREA, "executes_reassignment_without_a_repeated_user_binding_name")
}

/// Runs the fixture `executes_source_local_tuple_list_index_and_mutation_through_a_direct_c`.
#[test]
fn executes_source_local_tuple_list_index_and_mutation_through_a_direct_c() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_source_local_tuple_list_index_and_mutation_through_a_direct_c",
    )
}

/// Runs the fixture `executes_standalone_tuple_projection`.
#[test]
fn executes_standalone_tuple_projection() -> CaseResult {
    assert_fixture_holds(AREA, "executes_standalone_tuple_projection")
}

/// Runs the fixture `executes_the_exact_same_module_overload_selected_by_the_typechecker`.
#[test]
fn executes_the_exact_same_module_overload_selected_by_the_typechecker() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_exact_same_module_overload_selected_by_the_typechecker",
    )
}

/// Runs the fixture `executes_the_selected_string_ownership_control_flow_and_assertion_case`.
#[test]
fn executes_the_selected_string_ownership_control_flow_and_assertion_case() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_selected_string_ownership_control_flow_and_assertion_case",
    )
}

/// Runs the fixture `executes_the_selected_string_ownership_control_flow_and_assertion_case_2`.
#[test]
fn executes_the_selected_string_ownership_control_flow_and_assertion_case_2() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_selected_string_ownership_control_flow_and_assertion_case_2",
    )
}

/// Runs the fixture `executes_the_selected_string_ownership_control_flow_and_assertion_case_3`.
#[test]
fn executes_the_selected_string_ownership_control_flow_and_assertion_case_3() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_selected_string_ownership_control_flow_and_assertion_case_3",
    )
}

/// Runs the fixture `executes_the_selected_string_ownership_control_flow_and_assertion_case_4`.
#[test]
fn executes_the_selected_string_ownership_control_flow_and_assertion_case_4() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_selected_string_ownership_control_flow_and_assertion_case_4",
    )
}

/// Runs the fixture `executes_the_selected_string_ownership_control_flow_and_assertion_case_5`.
#[test]
fn executes_the_selected_string_ownership_control_flow_and_assertion_case_5() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_selected_string_ownership_control_flow_and_assertion_case_5",
    )
}

/// Runs the fixture `executes_the_selected_string_ownership_control_flow_and_assertion_case_6`.
#[test]
fn executes_the_selected_string_ownership_control_flow_and_assertion_case_6() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "executes_the_selected_string_ownership_control_flow_and_assertion_case_6",
    )
}

/// Runs the fixture `float_bool_remains_an_original_call_span_refusal`.
#[test]
fn float_bool_remains_an_original_call_span_refusal() -> CaseResult {
    assert_fixture_holds(AREA, "float_bool_remains_an_original_call_span_refusal")
}

/// Runs the fixture `indexing_a_list_field_of_a_model`.
#[test]
fn indexing_a_list_field_of_a_model() -> CaseResult {
    assert_fixture_holds(AREA, "indexing_a_list_field_of_a_model")
}

/// Runs the fixture `integer_power`.
#[test]
fn integer_power() -> CaseResult {
    assert_fixture_holds(AREA, "integer_power")
}

/// Runs the fixture `len_of_an_int_is_refused`.
#[test]
#[ignore = "pending: the checker accepts `len(1)` instead of refusing it"]
fn len_of_an_int_is_refused() -> CaseResult {
    assert_fixture_holds(AREA, "len_of_an_int_is_refused")
}

/// Runs the fixture `missing_bool_identity_refuses_instead_of_guessing_from_its_name`.
#[test]
fn missing_bool_identity_refuses_instead_of_guessing_from_its_name() -> CaseResult {
    assert_fixture_holds(AREA, "missing_bool_identity_refuses_instead_of_guessing_from_its_name")
}

/// Runs the fixture `nested_frames_keep_the_checked_contract`.
#[test]
fn nested_frames_keep_the_checked_contract() -> CaseResult {
    assert_fixture_holds(AREA, "nested_frames_keep_the_checked_contract")
}

/// Runs the fixture `nested_frames_keep_the_checked_contract_2`.
#[test]
fn nested_frames_keep_the_checked_contract_2() -> CaseResult {
    assert_fixture_holds(AREA, "nested_frames_keep_the_checked_contract_2")
}

/// Runs the fixture `nested_frames_keep_the_checked_contract_2_2`.
#[test]
fn nested_frames_keep_the_checked_contract_2_2() -> CaseResult {
    assert_fixture_holds(AREA, "nested_frames_keep_the_checked_contract_2_2")
}

/// Runs the fixture `nested_frames_keep_the_checked_contract_3`.
#[test]
fn nested_frames_keep_the_checked_contract_3() -> CaseResult {
    assert_fixture_holds(AREA, "nested_frames_keep_the_checked_contract_3")
}

/// Runs the fixture `parity_add_two_int_parameters`.
#[test]
fn parity_add_two_int_parameters() -> CaseResult {
    assert_fixture_holds(AREA, "parity_add_two_int_parameters")
}

/// Runs the fixture `parity_assert_then_floor_divide`.
#[test]
fn parity_assert_then_floor_divide() -> CaseResult {
    assert_fixture_holds(AREA, "parity_assert_then_floor_divide")
}

/// Runs the fixture `parity_chained_comparison_is_refused`.
#[test]
fn parity_chained_comparison_is_refused() -> CaseResult {
    assert_fixture_holds(AREA, "parity_chained_comparison_is_refused")
}

/// Runs the fixture `parity_continue_and_a_loop_that_never_runs`.
#[test]
fn parity_continue_and_a_loop_that_never_runs() -> CaseResult {
    assert_fixture_holds(AREA, "parity_continue_and_a_loop_that_never_runs")
}

/// Runs the fixture `parity_let_shadows_inside_a_block`.
#[test]
fn parity_let_shadows_inside_a_block() -> CaseResult {
    assert_fixture_holds(AREA, "parity_let_shadows_inside_a_block")
}

/// Runs the fixture `parity_mut_shadows_inside_a_block`.
#[test]
fn parity_mut_shadows_inside_a_block() -> CaseResult {
    assert_fixture_holds(AREA, "parity_mut_shadows_inside_a_block")
}

/// Runs the fixture `parity_nested_loop_statements_with_break_and_continue`.
#[test]
fn parity_nested_loop_statements_with_break_and_continue() -> CaseResult {
    assert_fixture_holds(AREA, "parity_nested_loop_statements_with_break_and_continue")
}

/// Runs the fixture `parity_return_from_a_tuple_destructuring_loop`.
#[test]
fn parity_return_from_a_tuple_destructuring_loop() -> CaseResult {
    assert_fixture_holds(AREA, "parity_return_from_a_tuple_destructuring_loop")
}

/// Runs the fixture `parity_statements_after_return_are_never_run`.
#[test]
fn parity_statements_after_return_are_never_run() -> CaseResult {
    assert_fixture_holds(AREA, "parity_statements_after_return_are_never_run")
}

/// Runs the fixture `parity_tuple_unpack_of_an_int_is_refused`.
#[test]
fn parity_tuple_unpack_of_an_int_is_refused() -> CaseResult {
    assert_fixture_holds(AREA, "parity_tuple_unpack_of_an_int_is_refused")
}

/// Runs the fixture `parity_unsafe_region_assigns_a_call_result`.
#[test]
fn parity_unsafe_region_assigns_a_call_result() -> CaseResult {
    assert_fixture_holds(AREA, "parity_unsafe_region_assigns_a_call_result")
}

/// Runs the fixture `refuses_a_missing_required_callable_argument_at_the_declaration_body_s`.
#[test]
fn refuses_a_missing_required_callable_argument_at_the_declaration_body_s() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_a_missing_required_callable_argument_at_the_declaration_body_s",
    )
}

/// Runs the fixture `refuses_collection_index_projection_with_the_original_source_span`.
#[test]
fn refuses_collection_index_projection_with_the_original_source_span() -> CaseResult {
    assert_fixture_holds(
        AREA,
        "refuses_collection_index_projection_with_the_original_source_span",
    )
}

/// Runs the fixture `refuses_structural_aggregate_return_values`.
#[test]
fn refuses_structural_aggregate_return_values() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_structural_aggregate_return_values")
}

/// Runs the fixture `refuses_to_run_a_rust_extern_placeholder`.
#[test]
fn refuses_to_run_a_rust_extern_placeholder() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_to_run_a_rust_extern_placeholder")
}

/// Runs the fixture `refuses_unsupported_body_ir_with_the_original_source_span`.
#[test]
fn refuses_unsupported_body_ir_with_the_original_source_span() -> CaseResult {
    assert_fixture_holds(AREA, "refuses_unsupported_body_ir_with_the_original_source_span")
}

/// Runs the fixture `rejects_a_source_declaration_that_redefines_immutable_print`.
#[test]
fn rejects_a_source_declaration_that_redefines_immutable_print() -> CaseResult {
    assert_fixture_holds(AREA, "rejects_a_source_declaration_that_redefines_immutable_print")
}

/// Runs the fixture `returns_a_value_returning_functions_trailing_expression`.
#[test]
#[ignore = "pending: the legacy route emits Rust that rustc rejects; the direct route (#1337 stage 4)"]
fn returns_a_value_returning_functions_trailing_expression() -> CaseResult {
    assert_fixture_holds(AREA, "returns_a_value_returning_functions_trailing_expression")
}

/// Runs the fixture `slicing_a_list`.
#[test]
fn slicing_a_list() -> CaseResult {
    assert_fixture_holds(AREA, "slicing_a_list")
}

/// Runs the fixture `slicing_a_list_field_of_a_model`.
#[test]
fn slicing_a_list_field_of_a_model() -> CaseResult {
    assert_fixture_holds(AREA, "slicing_a_list_field_of_a_model")
}

/// Runs the fixture `source_local_bool_keeps_its_declaration_identity`.
#[test]
fn source_local_bool_keeps_its_declaration_identity() -> CaseResult {
    assert_fixture_holds(AREA, "source_local_bool_keeps_its_declaration_identity")
}

/// Runs the fixture `substring_non_membership`.
#[test]
fn substring_non_membership() -> CaseResult {
    assert_fixture_holds(AREA, "substring_non_membership")
}

/// Runs the fixture `uses_python_signed_floor_division_and_modulo`.
#[test]
fn uses_python_signed_floor_division_and_modulo() -> CaseResult {
    assert_fixture_holds(AREA, "uses_python_signed_floor_division_and_modulo")
}

/// Runs the fixture `uses_python_signed_floor_division_and_modulo_2`.
#[test]
fn uses_python_signed_floor_division_and_modulo_2() -> CaseResult {
    assert_fixture_holds(AREA, "uses_python_signed_floor_division_and_modulo_2")
}

/// Runs the fixture `writes_a_mut_list_parameter_back_to_the_caller`.
#[test]
fn writes_a_mut_list_parameter_back_to_the_caller() -> CaseResult {
    assert_fixture_holds(AREA, "writes_a_mut_list_parameter_back_to_the_caller")
}

/// Every `pending:` fixture of the area still does not show what it declares.
#[test]
fn pending_fixtures_still_wait() -> CaseResult {
    assert_pending_fixtures_still_wait(AREA)
}
