//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_collections_and_strings`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_collections_and_strings/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_collections_and_strings";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `builtin_len_shadowing`.
#[test]
fn builtin_len_shadowing() -> CaseResult {
    assert_fixture_holds(AREA, "builtin_len_shadowing")
}

/// Runs the fixture `builtin_zip_only`.
#[test]
fn builtin_zip_only() -> CaseResult {
    assert_fixture_holds(AREA, "builtin_zip_only")
}

/// Runs the fixture `builtins`.
#[test]
fn builtins() -> CaseResult {
    assert_fixture_holds(AREA, "builtins")
}

/// Runs the fixture `collection_literal_spread`.
#[test]
fn collection_literal_spread() -> CaseResult {
    assert_fixture_holds(AREA, "collection_literal_spread")
}

/// Runs the fixture `collection_method_literal_arguments`.
#[test]
fn collection_method_literal_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "collection_method_literal_arguments")
}

/// Runs the fixture `collections`.
#[test]
fn collections() -> CaseResult {
    assert_fixture_holds(AREA, "collections")
}

/// Runs the fixture `const_frozen_collection_membership_and_iteration`.
#[test]
fn const_frozen_collection_membership_and_iteration() -> CaseResult {
    assert_fixture_holds(AREA, "const_frozen_collection_membership_and_iteration")
}

/// Runs the fixture `dict_contains_key_and_mut_dict_params`.
#[test]
fn dict_contains_key_and_mut_dict_params() -> CaseResult {
    assert_fixture_holds(AREA, "dict_contains_key_and_mut_dict_params")
}

/// Runs the fixture `dict_get_with_default`.
#[test]
fn dict_get_with_default() -> CaseResult {
    assert_fixture_holds(AREA, "dict_get_with_default")
}

/// Runs the fixture `dict_keys_and_values_outside_comprehensions`.
#[test]
fn dict_keys_and_values_outside_comprehensions() -> CaseResult {
    assert_fixture_holds(AREA, "dict_keys_and_values_outside_comprehensions")
}

/// Runs the fixture `dict_operations`.
#[test]
fn dict_operations() -> CaseResult {
    assert_fixture_holds(AREA, "dict_operations")
}

/// Runs the fixture `empty_list_equality`.
#[test]
fn empty_list_equality() -> CaseResult {
    assert_fixture_holds(AREA, "empty_list_equality")
}

/// Runs the fixture `empty_list_string_arg`.
#[test]
fn empty_list_string_arg() -> CaseResult {
    assert_fixture_holds(AREA, "empty_list_string_arg")
}

/// Runs the fixture `enumerate_tuple_unpack`.
#[test]
fn enumerate_tuple_unpack() -> CaseResult {
    assert_fixture_holds(AREA, "enumerate_tuple_unpack")
}

/// Runs the fixture `filtered_comprehensions`.
#[test]
fn filtered_comprehensions() -> CaseResult {
    assert_fixture_holds(AREA, "filtered_comprehensions")
}

/// Runs the fixture `frozen_collection_value_constructor_refused`.
#[test]
fn frozen_collection_value_constructor_refused() -> CaseResult {
    assert_fixture_holds(AREA, "frozen_collection_value_constructor_refused")
}

/// Runs the fixture `generator_expression_and_yield`.
#[test]
fn generator_expression_and_yield() -> CaseResult {
    assert_fixture_holds(AREA, "generator_expression_and_yield")
}

/// Runs the fixture `imported_stdlib_value_fragment`.
#[test]
fn imported_stdlib_value_fragment() -> CaseResult {
    assert_fixture_holds(AREA, "imported_stdlib_value_fragment")
}

/// Runs the fixture `iterator_adapter_sources`.
#[test]
fn iterator_adapter_sources() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_adapter_sources")
}

/// Runs the fixture `iterator_adapters`.
#[test]
fn iterator_adapters() -> CaseResult {
    assert_fixture_holds(AREA, "iterator_adapters")
}

/// Runs the fixture `json_stringify_builtin`.
#[test]
fn json_stringify_builtin() -> CaseResult {
    assert_fixture_holds(AREA, "json_stringify_builtin")
}

/// Runs the fixture `len_comparison`.
#[test]
fn len_comparison() -> CaseResult {
    assert_fixture_holds(AREA, "len_comparison")
}

/// Runs the fixture `list_and_comprehension_over_generator`.
#[test]
fn list_and_comprehension_over_generator() -> CaseResult {
    assert_fixture_holds(AREA, "list_and_comprehension_over_generator")
}

/// Runs the fixture `list_append_takes_a_fresh_task_handle`.
#[test]
fn list_append_takes_a_fresh_task_handle() -> CaseResult {
    assert_fixture_holds(AREA, "list_append_takes_a_fresh_task_handle")
}

/// Runs the fixture `list_repeat`.
#[test]
fn list_repeat() -> CaseResult {
    assert_fixture_holds(AREA, "list_repeat")
}

/// Runs the fixture `list_str_append_literal`.
#[test]
fn list_str_append_literal() -> CaseResult {
    assert_fixture_holds(AREA, "list_str_append_literal")
}

/// Runs the fixture `loop_variable_returned_owned`.
#[test]
fn loop_variable_returned_owned() -> CaseResult {
    assert_fixture_holds(AREA, "loop_variable_returned_owned")
}

/// Runs the fixture `map_err_string_literal_closure`.
#[test]
fn map_err_string_literal_closure() -> CaseResult {
    assert_fixture_holds(AREA, "map_err_string_literal_closure")
}

/// Runs the fixture `mut_str_match_arm`.
#[test]
fn mut_str_match_arm() -> CaseResult {
    assert_fixture_holds(AREA, "mut_str_match_arm")
}

/// Runs the fixture `ordinal_key_builtin_impls`.
#[test]
fn ordinal_key_builtin_impls() -> CaseResult {
    assert_fixture_holds(AREA, "ordinal_key_builtin_impls")
}

/// Runs the fixture `ordinal_map_str_lookup`.
#[test]
fn ordinal_map_str_lookup() -> CaseResult {
    assert_fixture_holds(AREA, "ordinal_map_str_lookup")
}

/// Runs the fixture `owned_iterator_sources`.
#[test]
fn owned_iterator_sources() -> CaseResult {
    assert_fixture_holds(AREA, "owned_iterator_sources")
}

/// Runs the fixture `question_mark_in_list_comprehension`.
#[test]
fn question_mark_in_list_comprehension() -> CaseResult {
    assert_fixture_holds(AREA, "question_mark_in_list_comprehension")
}

/// Runs the fixture `recursive_mut_list_and_mut_str_params`.
#[test]
fn recursive_mut_list_and_mut_str_params() -> CaseResult {
    assert_fixture_holds(AREA, "recursive_mut_list_and_mut_str_params")
}

/// Runs the fixture `result_ok_string_literal`.
#[test]
fn result_ok_string_literal() -> CaseResult {
    assert_fixture_holds(AREA, "result_ok_string_literal")
}

/// Runs the fixture `set_add_and_shadowing`.
#[test]
fn set_add_and_shadowing() -> CaseResult {
    assert_fixture_holds(AREA, "set_add_and_shadowing")
}

/// Runs the fixture `set_constructor`.
#[test]
fn set_constructor() -> CaseResult {
    assert_fixture_holds(AREA, "set_constructor")
}

/// Runs the fixture `shared_string_list_helpers`.
#[test]
fn shared_string_list_helpers() -> CaseResult {
    assert_fixture_holds(AREA, "shared_string_list_helpers")
}

/// Runs the fixture `storable_sha256_hasher`.
#[test]
fn storable_sha256_hasher() -> CaseResult {
    assert_fixture_holds(AREA, "storable_sha256_hasher")
}

/// Runs the fixture `str_encode_bytes_decode`.
#[test]
fn str_encode_bytes_decode() -> CaseResult {
    assert_fixture_holds(AREA, "str_encode_bytes_decode")
}

/// Runs the fixture `str_over_arithmetic_expression`.
#[test]
fn str_over_arithmetic_expression() -> CaseResult {
    assert_fixture_holds(AREA, "str_over_arithmetic_expression")
}

/// Runs the fixture `string_operations`.
#[test]
fn string_operations() -> CaseResult {
    assert_fixture_holds(AREA, "string_operations")
}
