//! @generated by `make behavior-roots` from the behavior-fixture area `ownership_string_boundaries`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/ownership_string_boundaries/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "ownership_string_boundaries";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `const_and_static_strings_to_parameters`.
#[test]
fn const_and_static_strings_to_parameters() -> CaseResult {
    assert_fixture_holds(AREA, "const_and_static_strings_to_parameters")
}

/// Runs the fixture `frozen_strings_at_parameters_fields_and_collections`.
#[test]
fn frozen_strings_at_parameters_fields_and_collections() -> CaseResult {
    assert_fixture_holds(AREA, "frozen_strings_at_parameters_fields_and_collections")
}

/// Runs the fixture `model_fields_from_literals_and_variables`.
#[test]
fn model_fields_from_literals_and_variables() -> CaseResult {
    assert_fixture_holds(AREA, "model_fields_from_literals_and_variables")
}

/// Runs the fixture `model_value_refused_at_a_str_parameter`.
#[test]
fn model_value_refused_at_a_str_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "model_value_refused_at_a_str_parameter")
}

/// Runs the fixture `primitives_and_literals_as_arguments`.
#[test]
fn primitives_and_literals_as_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "primitives_and_literals_as_arguments")
}

/// Runs the fixture `string_literal_and_variable_to_str_parameter`.
#[test]
fn string_literal_and_variable_to_str_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "string_literal_and_variable_to_str_parameter")
}

/// Runs the fixture `strings_and_ints_returned_and_assigned`.
#[test]
fn strings_and_ints_returned_and_assigned() -> CaseResult {
    assert_fixture_holds(AREA, "strings_and_ints_returned_and_assigned")
}
