//! @generated by `make behavior-roots` from the behavior-fixture area `emit_dependency_unions_and_surfaces`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/emit_dependency_unions_and_surfaces/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "emit_dependency_unions_and_surfaces";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `dependency_constructor_surfaces`.
#[test]
fn dependency_constructor_surfaces() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_constructor_surfaces")
}

/// Runs the fixture `dependency_declaration_kinds`.
#[test]
fn dependency_declaration_kinds() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_declaration_kinds")
}

/// Runs the fixture `dependency_unions_across_the_package_boundary`.
#[test]
fn dependency_unions_across_the_package_boundary() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_unions_across_the_package_boundary")
}
