//! @generated by `make behavior-roots` from the behavior-fixture area `codegen_models_and_collections`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/codegen_models_and_collections/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "codegen_models_and_collections";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `bytes_io_and_io_error_defaults`.
#[test]
fn bytes_io_and_io_error_defaults() -> CaseResult {
    assert_fixture_holds(AREA, "bytes_io_and_io_error_defaults")
}

/// Runs the fixture `compression_auto_decode`.
#[test]
fn compression_auto_decode() -> CaseResult {
    assert_fixture_holds(AREA, "compression_auto_decode")
}

/// Runs the fixture `deque_append_literal`.
#[test]
fn deque_append_literal() -> CaseResult {
    assert_fixture_holds(AREA, "deque_append_literal")
}

/// Runs the fixture `empty_list_comparison_operands`.
#[test]
fn empty_list_comparison_operands() -> CaseResult {
    assert_fixture_holds(AREA, "empty_list_comparison_operands")
}

/// Runs the fixture `empty_list_uses_expected_constructor_argument`.
#[test]
fn empty_list_uses_expected_constructor_argument() -> CaseResult {
    assert_fixture_holds(AREA, "empty_list_uses_expected_constructor_argument")
}

/// Runs the fixture `empty_literal_type_arguments_in_generic_constructors`.
#[test]
fn empty_literal_type_arguments_in_generic_constructors() -> CaseResult {
    assert_fixture_holds(AREA, "empty_literal_type_arguments_in_generic_constructors")
}

/// Runs the fixture `enum_variant_payload_type_arguments`.
#[test]
fn enum_variant_payload_type_arguments() -> CaseResult {
    assert_fixture_holds(AREA, "enum_variant_payload_type_arguments")
}

/// Runs the fixture `enumerate_stored_and_direct`.
#[test]
fn enumerate_stored_and_direct() -> CaseResult {
    assert_fixture_holds(AREA, "enumerate_stored_and_direct")
}

/// Runs the fixture `environ_get_as_composed_newtype`.
#[test]
fn environ_get_as_composed_newtype() -> CaseResult {
    assert_fixture_holds(AREA, "environ_get_as_composed_newtype")
}

/// Runs the fixture `fallible_entrypoint_runtime_diagnostic`.
#[test]
fn fallible_entrypoint_runtime_diagnostic() -> CaseResult {
    assert_fixture_holds(AREA, "fallible_entrypoint_runtime_diagnostic")
}

/// Runs the fixture `field_value_reflection`.
#[test]
fn field_value_reflection() -> CaseResult {
    assert_fixture_holds(AREA, "field_value_reflection")
}

/// Runs the fixture `generic_value_aliases_keep_both_bindings`.
#[test]
fn generic_value_aliases_keep_both_bindings() -> CaseResult {
    assert_fixture_holds(AREA, "generic_value_aliases_keep_both_bindings")
}

/// Runs the fixture `json_serialization_positions`.
#[test]
fn json_serialization_positions() -> CaseResult {
    assert_fixture_holds(AREA, "json_serialization_positions")
}

/// Runs the fixture `match_arm_ownership`.
#[test]
fn match_arm_ownership() -> CaseResult {
    assert_fixture_holds(AREA, "match_arm_ownership")
}

/// Runs the fixture `membership_probe_owned_and_literal`.
#[test]
fn membership_probe_owned_and_literal() -> CaseResult {
    assert_fixture_holds(AREA, "membership_probe_owned_and_literal")
}

/// Runs the fixture `nested_empty_list_holes`.
#[test]
fn nested_empty_list_holes() -> CaseResult {
    assert_fixture_holds(AREA, "nested_empty_list_holes")
}

/// Runs the fixture `same_named_std_helpers`.
#[test]
fn same_named_std_helpers() -> CaseResult {
    assert_fixture_holds(AREA, "same_named_std_helpers")
}

/// Runs the fixture `split_without_separator`.
#[test]
fn split_without_separator() -> CaseResult {
    assert_fixture_holds(AREA, "split_without_separator")
}

/// Runs the fixture `std_async_prelude_surface`.
#[test]
fn std_async_prelude_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_async_prelude_surface")
}

/// Runs the fixture `std_datetime_prelude_surface`.
#[test]
fn std_datetime_prelude_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_datetime_prelude_surface")
}

/// Runs the fixture `std_encoding_prelude_surface`.
#[test]
fn std_encoding_prelude_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_encoding_prelude_surface")
}

/// Runs the fixture `std_prelude_surface`.
#[test]
fn std_prelude_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_prelude_surface")
}

/// Runs the fixture `std_serde_prelude_surface`.
#[test]
fn std_serde_prelude_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_serde_prelude_surface")
}

/// Runs the fixture `std_telemetry_prelude_surface`.
#[test]
fn std_telemetry_prelude_surface() -> CaseResult {
    assert_fixture_holds(AREA, "std_telemetry_prelude_surface")
}

/// Runs the fixture `string_length_counts_scalars`.
#[test]
fn string_length_counts_scalars() -> CaseResult {
    assert_fixture_holds(AREA, "string_length_counts_scalars")
}

/// Runs the fixture `user_declarations_named_like_derive_helpers`.
#[test]
fn user_declarations_named_like_derive_helpers() -> CaseResult {
    assert_fixture_holds(AREA, "user_declarations_named_like_derive_helpers")
}

/// Runs the fixture `zip_value_aliases`.
#[test]
fn zip_value_aliases() -> CaseResult {
    assert_fixture_holds(AREA, "zip_value_aliases")
}
