//! @generated by `make behavior-roots` from the behavior-fixture area `lowering_dependencies`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/lowering_dependencies/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "lowering_dependencies";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `dependency_partial_and_function_value`.
#[test]
fn dependency_partial_and_function_value() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_partial_and_function_value")
}

/// Runs the fixture `fallible_iterator_through_public_library`.
#[test]
fn fallible_iterator_through_public_library() -> CaseResult {
    assert_fixture_holds(AREA, "fallible_iterator_through_public_library")
}

/// Runs the fixture `identity_graph_alias_signature`.
#[test]
fn identity_graph_alias_signature() -> CaseResult {
    assert_fixture_holds(AREA, "identity_graph_alias_signature")
}

/// Runs the fixture `package_inherent_methods_issue1174`.
#[test]
fn package_inherent_methods_issue1174() -> CaseResult {
    assert_fixture_holds(AREA, "package_inherent_methods_issue1174")
}

/// Runs the fixture `parent_namespace_and_qualified_partial_issue948`.
#[test]
fn parent_namespace_and_qualified_partial_issue948() -> CaseResult {
    assert_fixture_holds(AREA, "parent_namespace_and_qualified_partial_issue948")
}

/// Runs the fixture `provider_nominal_types_and_unions_issue892`.
#[test]
fn provider_nominal_types_and_unions_issue892() -> CaseResult {
    assert_fixture_holds(AREA, "provider_nominal_types_and_unions_issue892")
}
