//! @generated by `make behavior-roots` from the behavior-fixture area `ownership_parameters_and_receivers`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/ownership_parameters_and_receivers/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "ownership_parameters_and_receivers";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `bytes_io_read_through_a_guard`.
#[test]
fn bytes_io_read_through_a_guard() -> CaseResult {
    assert_fixture_holds(AREA, "bytes_io_read_through_a_guard")
}

/// Runs the fixture `channel_ends_unpacked_and_sent_through_a_wrapper`.
#[test]
fn channel_ends_unpacked_and_sent_through_a_wrapper() -> CaseResult {
    assert_fixture_holds(AREA, "channel_ends_unpacked_and_sent_through_a_wrapper")
}

/// Runs the fixture `comprehensions_and_list_constructor_sources`.
#[test]
fn comprehensions_and_list_constructor_sources() -> CaseResult {
    assert_fixture_holds(AREA, "comprehensions_and_list_constructor_sources")
}

/// Runs the fixture `dict_lookups_through_a_mutable_parameter`.
#[test]
fn dict_lookups_through_a_mutable_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "dict_lookups_through_a_mutable_parameter")
}

/// Runs the fixture `for_loops_over_strings_bytes_and_enum_lists`.
#[test]
fn for_loops_over_strings_bytes_and_enum_lists() -> CaseResult {
    assert_fixture_holds(AREA, "for_loops_over_strings_bytes_and_enum_lists")
}

/// Runs the fixture `generic_list_comprehension_consumes_parameter`.
#[test]
fn generic_list_comprehension_consumes_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "generic_list_comprehension_consumes_parameter")
}

/// Runs the fixture `mut_self_call_on_a_loop_item_inside_an_expression`.
#[test]
fn mut_self_call_on_a_loop_item_inside_an_expression() -> CaseResult {
    assert_fixture_holds(AREA, "mut_self_call_on_a_loop_item_inside_an_expression")
}

/// Runs the fixture `mut_tuple_parameter_elements_changed_in_place`.
#[test]
fn mut_tuple_parameter_elements_changed_in_place() -> CaseResult {
    assert_fixture_holds(AREA, "mut_tuple_parameter_elements_changed_in_place")
}

/// Runs the fixture `mutable_list_parameter_changes_reach_the_caller`.
#[test]
fn mutable_list_parameter_changes_reach_the_caller() -> CaseResult {
    assert_fixture_holds(AREA, "mutable_list_parameter_changes_reach_the_caller")
}

/// Runs the fixture `mutable_string_parameter_from_literal_and_variable`.
#[test]
fn mutable_string_parameter_from_literal_and_variable() -> CaseResult {
    assert_fixture_holds(AREA, "mutable_string_parameter_from_literal_and_variable")
}

/// Runs the fixture `refused_reused_unbounded_generic_comprehension_source`.
#[test]
fn refused_reused_unbounded_generic_comprehension_source() -> CaseResult {
    assert_fixture_holds(AREA, "refused_reused_unbounded_generic_comprehension_source")
}

/// Runs the fixture `result_methods_leave_their_receiver_usable`.
#[test]
fn result_methods_leave_their_receiver_usable() -> CaseResult {
    assert_fixture_holds(AREA, "result_methods_leave_their_receiver_usable")
}

/// Runs the fixture `self_and_wrapped_fields_returned_as_values`.
#[test]
fn self_and_wrapped_fields_returned_as_values() -> CaseResult {
    assert_fixture_holds(AREA, "self_and_wrapped_fields_returned_as_values")
}

/// Runs the fixture `unwrap_or_keeps_its_receiver_and_default`.
#[test]
fn unwrap_or_keeps_its_receiver_and_default() -> CaseResult {
    assert_fixture_holds(AREA, "unwrap_or_keeps_its_receiver_and_default")
}

/// Runs the fixture `zip_loop_changing_one_operand_in_place`.
#[test]
fn zip_loop_changing_one_operand_in_place() -> CaseResult {
    assert_fixture_holds(AREA, "zip_loop_changing_one_operand_in_place")
}
