//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_models_and_classes`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_models_and_classes/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_models_and_classes";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `class_field_visibility`.
#[test]
fn class_field_visibility() -> CaseResult {
    assert_fixture_holds(AREA, "class_field_visibility")
}

/// Runs the fixture `classes`.
#[test]
fn classes() -> CaseResult {
    assert_fixture_holds(AREA, "classes")
}

/// Runs the fixture `clone_self_string_field`.
#[test]
fn clone_self_string_field() -> CaseResult {
    assert_fixture_holds(AREA, "clone_self_string_field")
}

/// Runs the fixture `computed_properties`.
#[test]
fn computed_properties() -> CaseResult {
    assert_fixture_holds(AREA, "computed_properties")
}

/// Runs the fixture `constructor_field_defaults`.
#[test]
fn constructor_field_defaults() -> CaseResult {
    assert_fixture_holds(AREA, "constructor_field_defaults")
}

/// Runs the fixture `field_backed_method_arg`.
#[test]
fn field_backed_method_arg() -> CaseResult {
    assert_fixture_holds(AREA, "field_backed_method_arg")
}

/// Runs the fixture `generic_model_field_access`.
#[test]
fn generic_model_field_access() -> CaseResult {
    assert_fixture_holds(AREA, "generic_model_field_access")
}

/// Runs the fixture `imported_helper_named_like_builtin`.
#[test]
fn imported_helper_named_like_builtin() -> CaseResult {
    assert_fixture_holds(AREA, "imported_helper_named_like_builtin")
}

/// Runs the fixture `imported_private_source_class_constructor`.
#[test]
fn imported_private_source_class_constructor() -> CaseResult {
    assert_fixture_holds(AREA, "imported_private_source_class_constructor")
}

/// Runs the fixture `imported_private_source_model_constructor`.
#[test]
fn imported_private_source_model_constructor() -> CaseResult {
    assert_fixture_holds(AREA, "imported_private_source_model_constructor")
}

/// Runs the fixture `list_pop_and_clone_of_models`.
#[test]
fn list_pop_and_clone_of_models() -> CaseResult {
    assert_fixture_holds(AREA, "list_pop_and_clone_of_models")
}

/// Runs the fixture `lowercase_types`.
#[test]
fn lowercase_types() -> CaseResult {
    assert_fixture_holds(AREA, "lowercase_types")
}

/// Runs the fixture `model_alias_expressions`.
#[test]
fn model_alias_expressions() -> CaseResult {
    assert_fixture_holds(AREA, "model_alias_expressions")
}

/// Runs the fixture `model_struct`.
#[test]
fn model_struct() -> CaseResult {
    assert_fixture_holds(AREA, "model_struct")
}

/// Runs the fixture `model_with_alias`.
#[test]
fn model_with_alias() -> CaseResult {
    assert_fixture_holds(AREA, "model_with_alias")
}

/// Runs the fixture `model_with_serde_alias`.
#[test]
fn model_with_serde_alias() -> CaseResult {
    assert_fixture_holds(AREA, "model_with_serde_alias")
}

/// Runs the fixture `models`.
#[test]
fn models() -> CaseResult {
    assert_fixture_holds(AREA, "models")
}

/// Runs the fixture `named_constructor_evaluation_order`.
#[test]
fn named_constructor_evaluation_order() -> CaseResult {
    assert_fixture_holds(AREA, "named_constructor_evaluation_order")
}

/// Runs the fixture `partial_constructor_pattern`.
#[test]
fn partial_constructor_pattern() -> CaseResult {
    assert_fixture_holds(AREA, "partial_constructor_pattern")
}

/// Runs the fixture `phantom_type_param`.
#[test]
fn phantom_type_param() -> CaseResult {
    assert_fixture_holds(AREA, "phantom_type_param")
}

/// Runs the fixture `uppercase_var_field_access`.
#[test]
fn uppercase_var_field_access() -> CaseResult {
    assert_fixture_holds(AREA, "uppercase_var_field_access")
}
