//! @generated by `make behavior-roots` from the behavior-fixture area `smoke`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/smoke/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "smoke";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `enum_variants`.
#[test]
fn enum_variants() -> CaseResult {
    assert_fixture_holds(AREA, "enum_variants")
}

/// Runs the fixture `fstring_greeting`.
#[test]
fn fstring_greeting() -> CaseResult {
    assert_fixture_holds(AREA, "fstring_greeting")
}

/// Runs the fixture `membership_loop_binding`.
#[test]
fn membership_loop_binding() -> CaseResult {
    assert_fixture_holds(AREA, "membership_loop_binding")
}

/// Runs the fixture `model_fields`.
#[test]
fn model_fields() -> CaseResult {
    assert_fixture_holds(AREA, "model_fields")
}

/// Runs the fixture `simple_function_add`.
#[test]
fn simple_function_add() -> CaseResult {
    assert_fixture_holds(AREA, "simple_function_add")
}
