//! @generated by `make behavior-roots` from the behavior-fixture area `ownership_numerics_and_bounds`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/ownership_numerics_and_bounds/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "ownership_numerics_and_bounds";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `exact_float_arithmetic_keeps_its_width`.
#[test]
fn exact_float_arithmetic_keeps_its_width() -> CaseResult {
    assert_fixture_holds(AREA, "exact_float_arithmetic_keeps_its_width")
}

/// Runs the fixture `generic_functions_hash_through_dict_and_set_types`.
#[test]
fn generic_functions_hash_through_dict_and_set_types() -> CaseResult {
    assert_fixture_holds(AREA, "generic_functions_hash_through_dict_and_set_types")
}

/// Runs the fixture `generic_functions_reuse_callables_models_and_payloads`.
#[test]
fn generic_functions_reuse_callables_models_and_payloads() -> CaseResult {
    assert_fixture_holds(AREA, "generic_functions_reuse_callables_models_and_payloads")
}

/// Runs the fixture `generic_model_method_formats_its_type_parameter`.
#[test]
fn generic_model_method_formats_its_type_parameter() -> CaseResult {
    assert_fixture_holds(AREA, "generic_model_method_formats_its_type_parameter")
}

/// Runs the fixture `generic_values_reused_across_calls`.
#[test]
fn generic_values_reused_across_calls() -> CaseResult {
    assert_fixture_holds(AREA, "generic_values_reused_across_calls")
}

/// Runs the fixture `integer_overflow_helpers_and_explicit_resizes`.
#[test]
fn integer_overflow_helpers_and_explicit_resizes() -> CaseResult {
    assert_fixture_holds(AREA, "integer_overflow_helpers_and_explicit_resizes")
}

/// Runs the fixture `local_function_named_like_a_generic_in_another_module`.
#[test]
fn local_function_named_like_a_generic_in_another_module() -> CaseResult {
    assert_fixture_holds(AREA, "local_function_named_like_a_generic_in_another_module")
}

/// Runs the fixture `non_finite_exact_float_is_refused_at_runtime`.
#[test]
fn non_finite_exact_float_is_refused_at_runtime() -> CaseResult {
    assert_fixture_holds(AREA, "non_finite_exact_float_is_refused_at_runtime")
}

/// Runs the fixture `reflection_over_a_generic_value`.
#[test]
fn reflection_over_a_generic_value() -> CaseResult {
    assert_fixture_holds(AREA, "reflection_over_a_generic_value")
}
