//! @generated by `make behavior-roots` from the behavior-fixture area `codegen_modules_and_imports`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/codegen_modules_and_imports/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "codegen_modules_and_imports";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `dependency_module_public_items`.
#[test]
fn dependency_module_public_items() -> CaseResult {
    assert_fixture_holds(AREA, "dependency_module_public_items")
}

/// Runs the fixture `derive_bundle_through_module_alias`.
#[test]
fn derive_bundle_through_module_alias() -> CaseResult {
    assert_fixture_holds(AREA, "derive_bundle_through_module_alias")
}

/// Runs the fixture `facade_reexported_serde_trait`.
#[test]
fn facade_reexported_serde_trait() -> CaseResult {
    assert_fixture_holds(AREA, "facade_reexported_serde_trait")
}

/// Runs the fixture `field_alias_across_modules`.
#[test]
fn field_alias_across_modules() -> CaseResult {
    assert_fixture_holds(AREA, "field_alias_across_modules")
}

/// Runs the fixture `flat_module_import`.
#[test]
fn flat_module_import() -> CaseResult {
    assert_fixture_holds(AREA, "flat_module_import")
}

/// Runs the fixture `module_derive_through_import_binding`.
#[test]
fn module_derive_through_import_binding() -> CaseResult {
    assert_fixture_holds(AREA, "module_derive_through_import_binding")
}

/// Runs the fixture `module_item_import_spellings`.
#[test]
fn module_item_import_spellings() -> CaseResult {
    assert_fixture_holds(AREA, "module_item_import_spellings")
}

/// Runs the fixture `nested_decorated_generic_reflection`.
#[test]
fn nested_decorated_generic_reflection() -> CaseResult {
    assert_fixture_holds(AREA, "nested_decorated_generic_reflection")
}

/// Runs the fixture `nested_module_import_spellings`.
#[test]
fn nested_module_import_spellings() -> CaseResult {
    assert_fixture_holds(AREA, "nested_module_import_spellings")
}

/// Runs the fixture `qualified_type_annotations`.
#[test]
fn qualified_type_annotations() -> CaseResult {
    assert_fixture_holds(AREA, "qualified_type_annotations")
}

/// Runs the fixture `reexported_partial_and_static`.
#[test]
fn reexported_partial_and_static() -> CaseResult {
    assert_fixture_holds(AREA, "reexported_partial_and_static")
}

/// Runs the fixture `std_root_module_import`.
#[test]
fn std_root_module_import() -> CaseResult {
    assert_fixture_holds(AREA, "std_root_module_import")
}

/// Runs the fixture `std_submodule_single_import`.
#[test]
fn std_submodule_single_import() -> CaseResult {
    assert_fixture_holds(AREA, "std_submodule_single_import")
}

/// Runs the fixture `std_toml_derive_through_root_import`.
#[test]
fn std_toml_derive_through_root_import() -> CaseResult {
    assert_fixture_holds(AREA, "std_toml_derive_through_root_import")
}

/// Runs the fixture `subtrait_bound_calls_unimported_supertrait_method`.
#[test]
fn subtrait_bound_calls_unimported_supertrait_method() -> CaseResult {
    assert_fixture_holds(AREA, "subtrait_bound_calls_unimported_supertrait_method")
}

/// Runs the fixture `unprovable_qualified_type_refused`.
#[test]
fn unprovable_qualified_type_refused() -> CaseResult {
    assert_fixture_holds(AREA, "unprovable_qualified_type_refused")
}

/// Runs the fixture `user_types_named_like_stdlib_types`.
#[test]
fn user_types_named_like_stdlib_types() -> CaseResult {
    assert_fixture_holds(AREA, "user_types_named_like_stdlib_types")
}
