//! @generated by `make behavior-roots` from the behavior-fixture area `codegen_dependencies`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/codegen_dependencies/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "codegen_dependencies";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `implied_generic_supertrait_adoption`.
#[test]
fn implied_generic_supertrait_adoption() -> CaseResult {
    assert_fixture_holds(AREA, "implied_generic_supertrait_adoption")
}

/// Runs the fixture `pub_widgets_imports`.
#[test]
fn pub_widgets_imports() -> CaseResult {
    assert_fixture_holds(AREA, "pub_widgets_imports")
}
