//! @generated by `make behavior-roots` from the behavior-fixture area `snapshots_values_and_control_flow`.
//!
//! Fixtures: `loaves/compiler/incan_test_support/fixtures/behavior/snapshots_values_and_control_flow/`.
//! One case per fixture; a `pending:` fixture's case is ignored with its reason.
//! Do not edit: change the area and run `make behavior-roots`.

use incan_test_support::behavior_fixtures::assert_fixture_holds;

/// The area every case of this root runs a fixture of.
const AREA: &str = "snapshots_values_and_control_flow";

/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.
type CaseResult = Result<(), Box<dyn std::error::Error>>;

/// Runs the fixture `assignments`.
#[test]
fn assignments() -> CaseResult {
    assert_fixture_holds(AREA, "assignments")
}

/// Runs the fixture `const_str_chain_and_bytes`.
#[test]
fn const_str_chain_and_bytes() -> CaseResult {
    assert_fixture_holds(AREA, "const_str_chain_and_bytes")
}

/// Runs the fixture `consts_and_statics`.
#[test]
fn consts_and_statics() -> CaseResult {
    assert_fixture_holds(AREA, "consts_and_statics")
}

/// Runs the fixture `control_flow`.
#[test]
fn control_flow() -> CaseResult {
    assert_fixture_holds(AREA, "control_flow")
}

/// Runs the fixture `descriptor_const_with_empty_frozen_list`.
#[test]
fn descriptor_const_with_empty_frozen_list() -> CaseResult {
    assert_fixture_holds(AREA, "descriptor_const_with_empty_frozen_list")
}

/// Runs the fixture `exact_float_finite_guards`.
#[test]
fn exact_float_finite_guards() -> CaseResult {
    assert_fixture_holds(AREA, "exact_float_finite_guards")
}

/// Runs the fixture `exact_float_ingress_and_aggregates`.
#[test]
fn exact_float_ingress_and_aggregates() -> CaseResult {
    assert_fixture_holds(AREA, "exact_float_ingress_and_aggregates")
}

/// Runs the fixture `inferred_reassign`.
#[test]
fn inferred_reassign() -> CaseResult {
    assert_fixture_holds(AREA, "inferred_reassign")
}

/// Runs the fixture `literals`.
#[test]
fn literals() -> CaseResult {
    assert_fixture_holds(AREA, "literals")
}

/// Runs the fixture `loop_expressions`.
#[test]
fn loop_expressions() -> CaseResult {
    assert_fixture_holds(AREA, "loop_expressions")
}

/// Runs the fixture `loops`.
#[test]
fn loops() -> CaseResult {
    assert_fixture_holds(AREA, "loops")
}

/// Runs the fixture `mixed_f32_arithmetic`.
#[test]
fn mixed_f32_arithmetic() -> CaseResult {
    assert_fixture_holds(AREA, "mixed_f32_arithmetic")
}

/// Runs the fixture `mixed_numeric_and_float_display`.
#[test]
fn mixed_numeric_and_float_display() -> CaseResult {
    assert_fixture_holds(AREA, "mixed_numeric_and_float_display")
}

/// Runs the fixture `module_static_storage`.
#[test]
fn module_static_storage() -> CaseResult {
    assert_fixture_holds(AREA, "module_static_storage")
}

/// Runs the fixture `operators`.
#[test]
fn operators() -> CaseResult {
    assert_fixture_holds(AREA, "operators")
}

/// Runs the fixture `type_annotations`.
#[test]
fn type_annotations() -> CaseResult {
    assert_fixture_holds(AREA, "type_annotations")
}

/// Runs the fixture `user_defined_operators`.
#[test]
fn user_defined_operators() -> CaseResult {
    assert_fixture_holds(AREA, "user_defined_operators")
}
