#![allow(dead_code)] // Split test binaries intentionally use different parts of shared support fragments.

//! Workspace scope and fan-out, canonical lock publication, and locked/frozen build refusals.
//!
//! One of nine roots split out of the former `tests/cli_integration.rs`. The shared command surface lives in
//! `incan_test_support::cli_project`.

include!("support/cli_workspace_and_lock_tests_root.rs");

use std::process::Output;

#[test]
fn lock_generates_lockfile_for_manifest_project() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_lock_project", "")?;

    let output = run_incan(
        tmp.path(),
        &["lock", main_path.to_str().ok_or("main path was not valid UTF-8")?],
    )?;

    assert_success(&output, "incan lock");
    let lock = fs::read_to_string(tmp.path().join("oven.lock"))?;
    assert!(lock.contains("# Auto-generated by Incan - do not edit manually"));
    assert!(lock.contains("[incan]"));
    assert!(
        !lock.contains("generated ="),
        "oven.lock must not include volatile generation timestamps"
    );
    assert!(lock.contains("deps-fingerprint = \"sha256:"));
    assert!(lock.contains("[cargo]"));
    let parsed = oven_model::lock::IncanLock::load(&tmp.path().join("oven.lock"))?;
    assert_eq!(
        parsed.cargo_lock_payload, "version = 4\n",
        "normal `incan lock` records semantic Incan state, not a generated Cargo resolution"
    );

    let second_output = run_incan(
        tmp.path(),
        &["lock", main_path.to_str().ok_or("main path was not valid UTF-8")?],
    )?;
    assert_success(&second_output, "second incan lock");
    let second_lock = fs::read_to_string(tmp.path().join("oven.lock"))?;
    assert_eq!(lock, second_lock, "relocking unchanged inputs must be deterministic");
    Ok(())
}

#[cfg(unix)]
#[test]
fn lock_generates_semantic_state_without_starting_cargo() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_guarded_lock_project", "")?;
    let marker = tmp.path().join("cargo-was-started");

    let output = run_incan_with_failing_cargo_guard(
        tmp.path(),
        &["lock", main_path.to_str().ok_or("main path was not valid UTF-8")?],
        &tmp.path().join("cargo-guard"),
        &marker,
    )?;

    assert_success(&output, "Cargo-guarded incan lock");
    assert!(
        !marker.exists(),
        "normal incan lock must not launch Cargo; stderr:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let lock = oven_model::lock::IncanLock::load(&tmp.path().join("oven.lock"))?;
    assert_eq!(lock.cargo_lock_payload, "version = 4\n");
    Ok(())
}

#[test]
fn semantic_lock_records_registry_dependency_input_changes() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(
        tmp.path(),
        "registry_resolution_lock",
        r#"
[rust-dependencies]
bitflags = "=1.3.2"
"#,
    )?;
    fs::write(
        &main_path,
        "rust.module(\"bitflags\")\n\n\ndef main() -> None:\n  pass\n",
    )?;

    let first_output = run_incan_with_env(tmp.path(), &["lock"], &[("INCAN_LOCK_PREHEAT", "0")])?;
    assert_success(&first_output, "canonical lock with bitflags 1.3.2");
    let first_bytes = fs::read(tmp.path().join("oven.lock"))?;
    let first = oven_model::lock::IncanLock::load(&tmp.path().join("oven.lock"))?;
    assert_eq!(
        first.cargo_lock_payload, "version = 4\n",
        "normal lock generation must not resolve a Cargo package graph"
    );

    let manifest_path = tmp.path().join("loaf.toml");
    let first_manifest = fs::read_to_string(&manifest_path)?;
    fs::write(&manifest_path, first_manifest.replace("=1.3.2", "=2.11.0"))?;
    let second_output = run_incan_with_env(tmp.path(), &["lock"], &[("INCAN_LOCK_PREHEAT", "0")])?;
    assert_success(&second_output, "canonical lock with bitflags 2.11.0");
    let second_bytes = fs::read(tmp.path().join("oven.lock"))?;
    let second = oven_model::lock::IncanLock::load(&tmp.path().join("oven.lock"))?;
    assert_eq!(second.cargo_lock_payload, "version = 4\n");
    assert_ne!(
        first.deps_fingerprint, second.deps_fingerprint,
        "the semantic dependency fingerprint must change with the declared registry input"
    );
    assert_ne!(
        first_bytes, second_bytes,
        "the published canonical lock must change byte-for-byte"
    );
    Ok(())
}

#[test]
fn build_lib_reuses_canonical_lock_when_manifest_dependency_is_unused() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let _main_path = write_minimal_project(
        tmp.path(),
        "cli_library_unused_manifest_dependency",
        r#"
[rust-dependencies]
serde_json = "1"
"#,
    )?;
    fs::write(
        tmp.path().join("src").join("lib.incn"),
        "pub def exported_value() -> int:\n  return 7\n",
    )?;

    let build = run_incan(tmp.path(), &["build", "--lib"])?;
    assert_success(&build, "incan build --lib with an unused manifest Rust dependency");
    let generated_manifest = fs::read_to_string(tmp.path().join("target/lib/Cargo.toml"))?;
    assert!(
        !generated_manifest.contains("serde_json"),
        "unused manifest dependencies must not expand the generated library beyond the canonical reachable graph:\n\
         {generated_manifest}"
    );
    Ok(())
}

#[test]
fn default_build_and_test_leave_stale_lockfile_unchanged() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_default_stale_lock_project", "")?;
    let tests_dir = tmp.path().join("tests");
    fs::create_dir_all(&tests_dir)?;
    fs::write(
        tests_dir.join("test_main.incn"),
        r#"from std.testing import assert_eq

def test_smoke() -> None:
  assert_eq(1, 1)
"#,
    )?;

    let lock_output = run_incan(
        tmp.path(),
        &["lock", main_path.to_str().ok_or("main path was not valid UTF-8")?],
    )?;
    assert_success(&lock_output, "incan lock before default build");
    let stale_lock = stale_lockfile_without_changing_cargo_payload(tmp.path())?;

    let build_output = run_incan(
        tmp.path(),
        &["build", main_path.to_str().ok_or("main path was not valid UTF-8")?],
    )?;

    assert_success(&build_output, "incan build with stale lockfile by default");
    assert_eq!(
        fs::read_to_string(tmp.path().join("oven.lock"))?,
        stale_lock,
        "default build must not rewrite an existing stale oven.lock"
    );

    let test_output = run_incan(tmp.path(), &["test"])?;
    assert_success(&test_output, "incan test with stale lockfile by default");
    assert_eq!(
        fs::read_to_string(tmp.path().join("oven.lock"))?,
        stale_lock,
        "default test must not rewrite an existing stale oven.lock"
    );
    Ok(())
}

#[test]
fn multi_entrypoint_lock_covers_project_scripts_and_tests_issue505() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(
        tmp.path(),
        "cli_multi_entry_lock_freshness_project",
        r#"
extra = "src/extra.incn"

[rust-dependencies]
tiny_helper = { path = "rust/tiny_helper" }
"#,
    )?;
    fs::write(
        &main_path,
        r#"pub def value() -> int:
  return 1

def main() -> None:
  println(value())
"#,
    )?;
    let extra_path = tmp.path().join("src").join("extra.incn");
    fs::write(
        &extra_path,
        r#"from rust::tiny_helper import plus_one

def main() -> None:
  println(plus_one(1))
"#,
    )?;

    let tests_dir = tmp.path().join("tests");
    fs::create_dir_all(&tests_dir)?;
    fs::write(
        tests_dir.join("test_main.incn"),
        r#"from std.serde.json import Serialize
from std.testing import assert_eq
from crate.main import value

model Event with Serialize:
  id: int

def test_value() -> None:
  event = Event(id=1)
  assert_eq(event.to_json(), "{\"id\":1}")
  assert_eq(value(), 1)
"#,
    )?;

    let helper_src = tmp.path().join("rust").join("tiny_helper").join("src");
    fs::create_dir_all(&helper_src)?;
    fs::write(
        helper_src
            .parent()
            .ok_or("helper src has no parent")?
            .join("Cargo.toml"),
        r#"[package]
name = "tiny_helper"
version = "0.1.0"
edition = "2021"
"#,
    )?;
    fs::write(
        helper_src.join("lib.rs"),
        "pub fn plus_one(value: i64) -> i64 { value + 1 }\n",
    )?;

    let assert_no_stale_warning = |output: &Output, context: &str| {
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            !stderr.contains("oven.lock is out of date"),
            "{context} should not warn that oven.lock is stale, got:\n{stderr}"
        );
    };

    let default_lock_output = run_incan(tmp.path(), &["lock"])?;
    assert_success(&default_lock_output, "default incan lock");
    let bake_output = run_explicit_oven_bake(tmp.path())?;
    assert_success(&bake_output, "explicit Oven bake for all declared project entrypoints");

    let main_after_default_lock = run_incan(
        tmp.path(),
        &[
            "run",
            "--locked",
            main_path.to_str().ok_or("main path was not valid UTF-8")?,
        ],
    )?;
    assert_success(&main_after_default_lock, "incan run --locked main after default lock");
    assert_no_stale_warning(&main_after_default_lock, "incan run --locked main after default lock");
    assert_eq!(
        String::from_utf8_lossy(&main_after_default_lock.stdout).trim(),
        "1",
        "the conventional main target must replay its own sealed executable"
    );

    let locked_test_after_default_lock = run_incan(tmp.path(), &["test", "--locked"])?;
    assert_success(
        &locked_test_after_default_lock,
        "incan test --locked after default lock",
    );
    assert_no_stale_warning(
        &locked_test_after_default_lock,
        "incan test --locked after default lock",
    );

    let extra_after_default_lock = run_incan(
        tmp.path(),
        &[
            "run",
            "--locked",
            extra_path.to_str().ok_or("extra path was not valid UTF-8")?,
        ],
    )?;
    assert_success(&extra_after_default_lock, "incan run --locked extra after default lock");
    assert_no_stale_warning(&extra_after_default_lock, "incan run --locked extra after default lock");
    assert_eq!(
        String::from_utf8_lossy(&extra_after_default_lock.stdout).trim(),
        "2",
        "the declared extra target must replay its own sealed executable"
    );

    let main_report_output = run_incan(
        tmp.path(),
        &[
            "build",
            "--locked",
            "--report",
            "json",
            main_path.to_str().ok_or("main path was not valid UTF-8")?,
        ],
    )?;
    assert_success(&main_report_output, "sealed main build report after one explicit bake");
    let main_report = parse_json_stdout(&main_report_output)?;
    let extra_report_output = run_incan(
        tmp.path(),
        &[
            "build",
            "--locked",
            "--report",
            "json",
            extra_path.to_str().ok_or("extra path was not valid UTF-8")?,
        ],
    )?;
    assert_success(
        &extra_report_output,
        "sealed extra build report after one explicit bake",
    );
    let extra_report = parse_json_stdout(&extra_report_output)?;
    assert_eq!(
        main_report["entrypoint"],
        serde_json::json!(main_path.to_string_lossy()),
        "main replay report selected the wrong entrypoint"
    );
    assert_eq!(
        extra_report["entrypoint"],
        serde_json::json!(extra_path.to_string_lossy()),
        "extra replay report selected the wrong entrypoint"
    );
    let binary_path = |report: &serde_json::Value| {
        report["artifacts"]
            .as_array()
            .and_then(|artifacts| artifacts.iter().find(|artifact| artifact["kind"] == "binary"))
            .and_then(|artifact| artifact["path"].as_str())
            .map(str::to_string)
    };
    let main_binary = binary_path(&main_report).ok_or("main report had no binary artifact")?;
    let extra_binary = binary_path(&extra_report).ok_or("extra report had no binary artifact")?;
    assert_ne!(
        main_binary, extra_binary,
        "distinct declared scripts must retain distinct caller-visible native outputs"
    );

    let extra_lock_output = run_incan(
        tmp.path(),
        &["lock", extra_path.to_str().ok_or("extra path was not valid UTF-8")?],
    )?;
    assert_success(&extra_lock_output, "incan lock extra");

    let test_after_extra_lock = run_incan(tmp.path(), &["test", "--locked"])?;
    assert_success(&test_after_extra_lock, "incan test --locked after extra lock");
    assert_no_stale_warning(&test_after_extra_lock, "incan test --locked after extra lock");

    Ok(())
}

#[test]
fn build_locked_rejects_stale_lockfile() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_locked_project", "")?;

    let lock_output = run_incan(
        tmp.path(),
        &["lock", main_path.to_str().ok_or("main path was not valid UTF-8")?],
    )?;
    assert_success(&lock_output, "incan lock before locked build");

    fs::write(
        tmp.path().join("loaf.toml"),
        r#"[project]
name = "cli_locked_project"
version = "0.1.0"

[project.scripts]
main = "src/main.incn"

[rust-dependencies.serde]
version = "1.0"
"#,
    )?;
    fs::write(
        &main_path,
        r#"from rust::serde import Serialize

def main() -> None:
  println("cli lifecycle ok")
"#,
    )?;

    let build_output = run_incan(
        tmp.path(),
        &[
            "build",
            "--locked",
            main_path.to_str().ok_or("main path was not valid UTF-8")?,
        ],
    )?;

    assert_failure(&build_output, "incan build --locked with stale lockfile");
    let stderr = String::from_utf8_lossy(&build_output.stderr);
    assert!(
        stderr.contains("oven.lock is out of date"),
        "locked build should report stale lockfile, got:\n{stderr}"
    );
    assert!(
        stderr.contains("incan lock"),
        "locked build should tell users how to refresh the lockfile"
    );
    Ok(())
}

#[test]
fn build_frozen_rejects_missing_lockfile() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_frozen_project", "")?;

    let build_output = run_incan(
        tmp.path(),
        &[
            "build",
            "--frozen",
            main_path.to_str().ok_or("main path was not valid UTF-8")?,
        ],
    )?;

    assert_failure(&build_output, "incan build --frozen without lockfile");
    let stderr = String::from_utf8_lossy(&build_output.stderr);
    assert!(
        stderr.contains("oven.lock is missing; run `incan lock`"),
        "frozen build should report missing lockfile, got:\n{stderr}"
    );
    assert!(
        !tmp.path().join("oven.lock").exists(),
        "frozen build must not create oven.lock after rejecting a missing lockfile"
    );
    Ok(())
}

#[test]
fn build_lock_policy_env_defaults_refuse_a_missing_lock() -> Result<(), Box<dyn std::error::Error>> {
    // `INCAN_LOCKED=1` is the `--locked` default and `INCAN_FROZEN=1` implies locked (and offline), so either one
    // refuses a project without `oven.lock` exactly as the flag would, and creates none. The environment defaults
    // are lock-policy inputs, not a Cargo surface; they survive the cutover (#1561).
    for (variable, context) in [
        ("INCAN_LOCKED", "INCAN_LOCKED=1 build"),
        ("INCAN_FROZEN", "INCAN_FROZEN=1 build"),
    ] {
        let tmp = tempfile::tempdir()?;
        let main_path = write_minimal_project(tmp.path(), "cli_lock_env_default_project", "")?;
        let main_arg = main_path.to_str().ok_or("main path was not valid UTF-8")?;

        let build_output = run_incan_with_env(tmp.path(), &["build", main_arg], &[(variable, "1")])?;

        assert_failure(&build_output, context);
        let stderr = String::from_utf8_lossy(&build_output.stderr);
        assert!(
            stderr.contains("oven.lock is missing; run `incan lock`"),
            "{context} should report the missing lockfile, got:\n{stderr}"
        );
        assert!(
            !tmp.path().join("oven.lock").exists(),
            "{context} must not create oven.lock after refusing"
        );
    }
    Ok(())
}

#[test]
fn build_no_flags_override_lock_policy_env_defaults() -> Result<(), Box<dyn std::error::Error>> {
    // `--no-locked` and `--no-frozen` negate the environment defaults on the command line, so the same project
    // without `oven.lock` builds; the negation is the last word.
    for (variable, flag, context) in [
        ("INCAN_LOCKED", "--no-locked", "INCAN_LOCKED=1 build --no-locked"),
        ("INCAN_FROZEN", "--no-frozen", "INCAN_FROZEN=1 build --no-frozen"),
    ] {
        let tmp = tempfile::tempdir()?;
        let main_path = write_minimal_project(tmp.path(), "cli_lock_env_negation_project", "")?;
        let main_arg = main_path.to_str().ok_or("main path was not valid UTF-8")?;

        let build_output = run_incan_with_env(tmp.path(), &["build", flag, main_arg], &[(variable, "1")])?;

        assert_success(&build_output, context);
    }
    Ok(())
}

#[test]
fn build_frozen_does_not_read_a_pre_rename_lock() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_pre_rename_lock_project", "")?;
    let main_arg = main_path.to_str().ok_or("main path was not valid UTF-8")?;

    // Generate a genuinely current lock, then give it the pre-rename name. RFC 117 makes `oven.lock` the sole
    // generated resolution state and says `incan.lock` is not read afterwards, so the planted file must be invisible
    // rather than read and rejected. Planting a hand-written file could not tell those two outcomes apart: a frozen
    // build would fail either way, and for the wrong reason.
    let lock_output = run_incan(tmp.path(), &["lock", main_arg])?;
    assert_success(&lock_output, "incan lock before renaming the generated lock");
    fs::rename(tmp.path().join("oven.lock"), tmp.path().join("incan.lock"))?;

    let build_output = run_incan(tmp.path(), &["build", "--frozen", main_arg])?;

    assert_failure(&build_output, "incan build --frozen with only a pre-rename lock");
    let stderr = String::from_utf8_lossy(&build_output.stderr);
    assert!(
        stderr.contains("oven.lock is missing; run `incan lock`"),
        "a project holding only the pre-rename lock must report the canonical lock missing, got:\n{stderr}"
    );
    assert!(
        tmp.path().join("incan.lock").is_file(),
        "the pre-rename lock is inert state, not something the compiler consumes or removes"
    );
    Ok(())
}

#[test]
fn build_frozen_uses_existing_lockfile_without_network() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let main_path = write_minimal_project(tmp.path(), "cli_frozen_existing_lock_project", "")?;

    let lock_output = run_incan(
        tmp.path(),
        &["lock", main_path.to_str().ok_or("main path was not valid UTF-8")?],
    )?;
    assert_success(&lock_output, "incan lock before frozen build");

    let build_output = run_incan(
        tmp.path(),
        &[
            "build",
            "--frozen",
            main_path.to_str().ok_or("main path was not valid UTF-8")?,
        ],
    )?;

    assert_success(&build_output, "incan build --frozen with existing lockfile");
    let stdout = String::from_utf8_lossy(&build_output.stdout);
    assert!(
        stdout.contains("Oven build successful"),
        "frozen build should complete with the existing lockfile, got:\n{stdout}"
    );
    Ok(())
}
