//! Focused checked-identity coverage for empty collection construction in #1247.

use incan::backend::IrCodegen;
use incan::frontend::ast;
use incan::frontend::body_ir::build_body_ir_module_v0;
use incan::frontend::symbols::ResolvedType;
use incan::frontend::typechecker::TypeChecker;
use incan::frontend::{lexer, parser};
use incan_core::lang::types::collections::CollectionTypeId;
use incan_semantics_core::{
    body_ir::{AggregateKind, Body, BodyIrModule, Rvalue, StatementKind},
    decode_incan_symbol_identity,
};

const TYPED_EMPTY_COLLECTIONS: &str = r#"
def empty_set() -> Set[int]:
  return Set()

def empty_dict() -> Dict[str, int]:
  return Dict()

def annotated_locals() -> None:
  values: set[int] = Set()
  mapping: dict[str, int] = Dict()
"#;

/// Parse and type-check a source module before Body-IR construction.
fn checked_source(source: &str) -> Result<(ast::Program, TypeChecker, Vec<String>), Box<dyn std::error::Error>> {
    let tokens = lexer::lex(source).map_err(|errors| std::io::Error::other(format!("{errors:?}")))?;
    let program = parser::parse(&tokens).map_err(|errors| std::io::Error::other(format!("{errors:?}")))?;
    let module_path = vec!["checked_empty_collections".to_string()];
    let mut checker = TypeChecker::new();
    checker.set_current_module_path(Some(module_path.clone()));
    checker
        .check_program(&program)
        .map_err(|errors| std::io::Error::other(format!("{errors:?}")))?;
    Ok((program, checker, module_path))
}

/// Normalize generated version headers so the focused aggregate-emission snapshot does not churn on releases.
fn normalize_codegen_output(code: &str) -> String {
    let compiler_header = format!(
        "// Generated by the Incan compiler v{}\n\n",
        incan::version::INCAN_VERSION
    );
    let stdlib_check = format!(
        "incan_stdlib::__incan_stdlib_version_check!(\"{}\");",
        incan::version::INCAN_VERSION
    );
    let normalized = code
        .replace(
            &compiler_header,
            "// Generated by the Incan compiler v<INCAN_VERSION>\n\n",
        )
        .replace(
            &stdlib_check,
            "incan_stdlib::__incan_stdlib_version_check!(\"<INCAN_STDLIB_VERSION>\");",
        );
    normalize_projected_symbols(&normalized)
}

/// Decode physical RFC 120 symbol projections only for source-readable assertions and snapshots.
fn normalize_projected_symbols(code: &str) -> String {
    let mut normalized = String::with_capacity(code.len());
    let mut token = String::new();
    let flush = |token: &mut String, normalized: &mut String| {
        if token.starts_with("__incan_v")
            && let Ok(Some(identity)) = decode_incan_symbol_identity(token)
        {
            normalized.push_str(&identity.declaration_name);
        } else {
            normalized.push_str(token);
        }
        token.clear();
    };

    for character in code.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            token.push(character);
        } else {
            flush(&mut token, &mut normalized);
            normalized.push(character);
        }
    }
    flush(&mut token, &mut normalized);

    let Ok(syntax) = syn::parse_file(&normalized) else {
        return normalized;
    };
    format!(
        "// Generated by the Incan compiler v<INCAN_VERSION>\n\n// __INCAN_INSERT_MODS__\n\n{}",
        prettyplease::unparse(&syntax)
    )
}

/// Return the full source span of a unique zero-argument constructor call.
fn call_span(source: &str, call: &str) -> Result<ast::Span, Box<dyn std::error::Error>> {
    let start = source
        .rfind(call)
        .ok_or_else(|| format!("fixture is missing `{call}`"))?;
    Ok(ast::Span::new(start, start + call.len()))
}

/// Return the full source span of one ordered zero-argument constructor call.
fn call_span_at(source: &str, call: &str, occurrence: usize) -> Result<ast::Span, Box<dyn std::error::Error>> {
    let start = source
        .match_indices(call)
        .nth(occurrence)
        .map(|(start, _)| start)
        .ok_or_else(|| format!("fixture is missing occurrence {occurrence} of `{call}`"))?;
    Ok(ast::Span::new(start, start + call.len()))
}

/// Return one named lowered body.
fn body_named<'module>(module: &'module BodyIrModule, name: &str) -> Result<&'module Body, Box<dyn std::error::Error>> {
    module
        .bodies
        .iter()
        .find(|body| body.name == name)
        .ok_or_else(|| format!("lowered module has no body named `{name}`").into())
}

/// Assert that the temporary assigned at `span` retains both the expected aggregate shape and checked result type.
fn assert_empty_constructor(
    body: &Body,
    span: ast::Span,
    expected_type: &ResolvedType,
    expected_kind: CollectionTypeId,
) -> Result<(), Box<dyn std::error::Error>> {
    let statement = body
        .block
        .stmts
        .iter()
        .find(|statement| statement.span.start == span.start && statement.span.end == span.end)
        .ok_or("empty constructor must lower at its own source span")?;
    let StatementKind::Assign { place, rvalue } = &statement.kind else {
        return Err("empty constructor must be an aggregate assignment, not a call".into());
    };
    match (expected_kind, rvalue) {
        (CollectionTypeId::Set, Rvalue::Aggregate(AggregateKind::Set, entries)) if entries.is_empty() => {}
        (CollectionTypeId::Dict, Rvalue::Dict(entries)) if entries.is_empty() => {}
        _ => return Err(format!("unexpected empty constructor rvalue: {rvalue:?}").into()),
    }
    let actual_type = body
        .locals
        .get(
            place
                .local_id()
                .ok_or("empty constructor destination must be local")?
                .index(),
        )
        .ok_or("empty constructor destination must be a declared temporary")?
        .ty
        .to_string();
    if actual_type != expected_type.to_string() {
        return Err(format!("expected retained result type {expected_type}, got {actual_type}").into());
    }
    Ok(())
}

/// Assert the typechecker retained the exact contextual result type rather than an unknown placeholder.
fn assert_checked_result_type(
    checker: &TypeChecker,
    span: ast::Span,
    expected_type: &ResolvedType,
) -> Result<(), Box<dyn std::error::Error>> {
    let actual_type = checker
        .type_info()
        .expr_type(span)
        .ok_or("zero-argument constructor must retain a checked result type")?;
    if actual_type != expected_type {
        return Err(format!("expected checked result type {expected_type}, got {actual_type}").into());
    }
    Ok(())
}

/// Assert an annotated source binding keeps its concrete type after the initializer is lowered.
fn assert_named_local_type(
    body: &Body,
    name: &str,
    expected_type: &ResolvedType,
) -> Result<(), Box<dyn std::error::Error>> {
    let actual_type = body
        .locals
        .iter()
        .find(|local| local.name.as_deref() == Some(name))
        .ok_or_else(|| format!("lowered body has no `{name}` binding"))?
        .ty
        .to_string();
    if actual_type != expected_type.to_string() {
        return Err(format!("expected `{name}` to retain {expected_type}, got {actual_type}").into());
    }
    Ok(())
}

/// Lower zero-argument `Set` and `Dict` only from their retained canonical constructor identities.
#[test]
fn checked_empty_collection_constructors_lower_to_existing_aggregate_shapes_issue1247()
-> Result<(), Box<dyn std::error::Error>> {
    let (program, checker, module_path) = checked_source(TYPED_EMPTY_COLLECTIONS)?;
    let return_set_span = call_span_at(TYPED_EMPTY_COLLECTIONS, "Set()", 0)?;
    let return_dict_span = call_span_at(TYPED_EMPTY_COLLECTIONS, "Dict()", 0)?;
    let local_set_span = call_span_at(TYPED_EMPTY_COLLECTIONS, "Set()", 1)?;
    let local_dict_span = call_span_at(TYPED_EMPTY_COLLECTIONS, "Dict()", 1)?;
    let set_type = ResolvedType::Generic("Set".to_string(), vec![ResolvedType::Int]);
    let dict_type = ResolvedType::Generic("Dict".to_string(), vec![ResolvedType::Str, ResolvedType::Int]);
    let type_info = checker.type_info();
    if type_info.resolved_collection_constructor(return_set_span) != Some(CollectionTypeId::Set)
        || type_info.resolved_collection_constructor(local_set_span) != Some(CollectionTypeId::Set)
    {
        return Err("zero-argument Set must retain its checked constructor identity".into());
    }
    if type_info.resolved_collection_constructor(return_dict_span) != Some(CollectionTypeId::Dict)
        || type_info.resolved_collection_constructor(local_dict_span) != Some(CollectionTypeId::Dict)
    {
        return Err("zero-argument Dict must retain its checked constructor identity".into());
    }
    assert_checked_result_type(&checker, return_set_span, &set_type)?;
    assert_checked_result_type(&checker, return_dict_span, &dict_type)?;
    assert_checked_result_type(&checker, local_set_span, &set_type)?;
    assert_checked_result_type(&checker, local_dict_span, &dict_type)?;
    let module = build_body_ir_module_v0(&program, &module_path, type_info);
    let set_body = body_named(&module, "empty_set")?;
    let dict_body = body_named(&module, "empty_dict")?;
    let locals_body = body_named(&module, "annotated_locals")?;
    assert_empty_constructor(set_body, return_set_span, &set_type, CollectionTypeId::Set)?;
    assert_empty_constructor(dict_body, return_dict_span, &dict_type, CollectionTypeId::Dict)?;
    assert_empty_constructor(locals_body, local_set_span, &set_type, CollectionTypeId::Set)?;
    assert_empty_constructor(locals_body, local_dict_span, &dict_type, CollectionTypeId::Dict)?;
    assert_named_local_type(locals_body, "values", &set_type)?;
    assert_named_local_type(locals_body, "mapping", &dict_type)?;
    for body in [set_body, dict_body, locals_body] {
        if !body.render_snapshot().contains("allocator") {
            return Err("empty collection construction must retain its allocator requirement".into());
        }
    }
    Ok(())
}

/// A nonmatching destination collection type stays a checked source error instead of supplying unrelated arguments.
#[test]
fn mismatched_typed_empty_collection_constructor_contexts_remain_errors_issue1247()
-> Result<(), Box<dyn std::error::Error>> {
    let source = r#"
def impossible() -> Dict[str, int]:
  return Set()
"#;
    let tokens = lexer::lex(source).map_err(|errors| std::io::Error::other(format!("{errors:?}")))?;
    let program = parser::parse(&tokens).map_err(|errors| std::io::Error::other(format!("{errors:?}")))?;
    let mut checker = TypeChecker::new();
    let errors = match checker.check_program(&program) {
        Ok(()) => return Err("mismatched Set return unexpectedly type-checked".into()),
        Err(errors) => errors,
    };
    if !errors.iter().any(|error| {
        error
            .message
            .contains("Return type mismatch: expected 'Dict[str, int]', found 'Set[?]'")
    }) {
        return Err(format!("expected Set/Dict return mismatch, got {errors:?}").into());
    }
    Ok(())
}

/// A source binding named like a canonical collection constructor remains an ordinary call, not aggregate construction.
#[test]
fn shadowed_collection_constructors_do_not_gain_aggregate_lowering_issue1247() -> Result<(), Box<dyn std::error::Error>>
{
    let source = r#"
def Set() -> int:
  return 1

def Dict() -> int:
  return 2

def main() -> int:
  return Set() + Dict()
"#;
    let (program, checker, module_path) = checked_source(source)?;
    let set_span = call_span(source, "Set()")?;
    let dict_span = call_span(source, "Dict()")?;
    if checker.type_info().resolved_collection_constructor(set_span).is_some()
        || checker.type_info().resolved_collection_constructor(dict_span).is_some()
    {
        return Err("a shadowed collection spelling must not retain builtin constructor identity".into());
    }
    let snapshot = build_body_ir_module_v0(&program, &module_path, checker.type_info()).render_snapshot();
    if snapshot.contains("set[]") || snapshot.contains("dict[]") {
        return Err(format!("shadowed call must not lower as an aggregate: {snapshot}").into());
    }
    Ok(())
}

/// Removing a checked fact must not make Body IR infer a collection constructor from a source name.
#[test]
fn missing_checked_collection_constructor_facts_do_not_guess_aggregate_lowering_issue1247()
-> Result<(), Box<dyn std::error::Error>> {
    let (program, checker, module_path) = checked_source(TYPED_EMPTY_COLLECTIONS)?;
    let set_spans = [
        call_span_at(TYPED_EMPTY_COLLECTIONS, "Set()", 0)?,
        call_span_at(TYPED_EMPTY_COLLECTIONS, "Set()", 1)?,
    ];
    let dict_spans = [
        call_span_at(TYPED_EMPTY_COLLECTIONS, "Dict()", 0)?,
        call_span_at(TYPED_EMPTY_COLLECTIONS, "Dict()", 1)?,
    ];
    let mut missing = checker.type_info().clone();
    for span in set_spans.into_iter().chain(dict_spans) {
        missing
            .calls
            .resolved_collection_constructors
            .remove(&(span.start, span.end));
    }
    let snapshot = build_body_ir_module_v0(&program, &module_path, &missing).render_snapshot();
    if snapshot.contains("set[]") || snapshot.contains("dict[]") {
        return Err(format!("a missing checked fact must not acquire aggregate lowering: {snapshot}").into());
    }
    Ok(())
}

/// Generate the legacy IR path for a checked typed-empty dictionary through its existing aggregate emitter.
#[test]
fn checked_typed_empty_dict_reaches_existing_aggregate_emission_issue1247() -> Result<(), Box<dyn std::error::Error>> {
    let source = "pub def empty_dict() -> Dict[str, int]:\n  return Dict()\n";
    let (program, _, _) = checked_source(source)?;
    let generated = IrCodegen::new()
        .try_generate(&program)
        .map_err(|error| std::io::Error::other(format!("typed empty Dict generation failed: {error}")))?;
    if !generated.contains("std::collections::HashMap::new()") {
        return Err(format!("typed empty Dict must use aggregate emission, got:\n{generated}").into());
    }
    insta::assert_snapshot!(
        "checked_typed_empty_dict_aggregate_emission_issue1247",
        normalize_codegen_output(&generated)
    );
    Ok(())
}

/// Keep nonempty dictionary conversion on its pre-#1247 unchecked-constructor route.
#[test]
fn nonempty_dict_conversion_does_not_gain_a_checked_constructor_fact_issue1247()
-> Result<(), Box<dyn std::error::Error>> {
    let source = "pub def copy(mapping: Dict[str, int]) -> Dict[str, int]:\n  return Dict(mapping)\n";
    let (program, checker, _) = checked_source(source)?;
    let span = call_span(source, "Dict(mapping)")?;
    if checker.type_info().resolved_collection_constructor(span).is_some() {
        return Err("nonempty Dict conversion must remain outside the typed-empty constructor path".into());
    }
    let generated = IrCodegen::new()
        .try_generate(&program)
        .map_err(|error| std::io::Error::other(format!("nonempty Dict conversion generation failed: {error}")))?;
    if !normalize_codegen_output(&generated).contains("pub fn copy") {
        return Err(format!("nonempty Dict conversion must retain code generation, got:\n{generated}").into());
    }
    Ok(())
}
