//! Regression coverage for ordinary runtime diagnostics and Zen in a Result-returning process entrypoint.

use incan::backend::IrCodegen;
use incan::frontend::{lexer, parser};

#[path = "support/canonical_projection.rs"]
mod canonical_projection;
/// Fallible entrypoints retain the same runtime panic hook and Zen ordering as unit-returning entrypoints.
#[test]
fn fallible_main_preserves_entrypoint_setup_before_the_body() -> Result<(), Box<dyn std::error::Error>> {
    let source = include_str!("codegen_snapshots/fallible_main_runtime_diagnostic.incn");
    let tokens = lexer::lex(source).map_err(|errors| format!("fixture did not lex: {errors:?}"))?;
    let program = parser::parse(&tokens).map_err(|errors| format!("fixture did not parse: {errors:?}"))?;
    let rust = IrCodegen::new().try_generate(&program)?;
    assert!(
        rust.contains("std::panic::set_hook"),
        "Result-returning main must install the same Incan runtime diagnostic hook as unit main:\n{rust}"
    );
    let hook_position = rust.find("std::panic::set_hook").ok_or("missing panic hook")?;
    let zen_position = rust.find("The Zen of Incan").ok_or("missing requested Zen output")?;
    let body_position = rust.find("before failure").ok_or("missing ordinary program output")?;
    assert!(
        hook_position < zen_position,
        "the diagnostic hook must precede Zen output"
    );
    assert!(
        zen_position < body_position,
        "Zen output must precede ordinary source statements"
    );
    let normalized = rust
        .replace(
            &format!(
                "// Generated by the Incan compiler v{}\n",
                incan::version::INCAN_VERSION
            ),
            "// Generated by the Incan compiler v<INCAN_VERSION>\n",
        )
        .replace(
            &format!(
                "incan_stdlib::__incan_stdlib_version_check!(\"{}\");",
                incan::version::INCAN_VERSION
            ),
            "incan_stdlib::__incan_stdlib_version_check!(\"<INCAN_STDLIB_VERSION>\");",
        );
    // Decode RFC 120 projections so the golden shows the entrypoint the source declared rather than an encoded
    // identifier whose payload embeds a declaration span and churns whenever a line above it moves.
    let normalized = canonical_projection::decoded_source_spellings(&normalized);
    insta::assert_snapshot!("fallible_main_runtime_diagnostic", normalized);
    Ok(())
}
