#![cfg(unix)]

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

use incan::oven::legacy_cargo::{
    OvenLegacyCargoError, OvenLegacyCargoPrepareRequest, OvenLegacyCargoPublicationKind, prepare_direct_rustc_plan,
};
use incan::oven::native_test::run_native_test_batch_all_in_directory_with_timeout;
use incan::oven::store::{OvenStore, OvenStoreLimits};
use incan::oven::{OvenGeneratedProjectRequest, receipt_generated_project};

#[test]
fn native_timeout_terminates_descendants_that_retain_output_pipes() -> Result<(), Box<dyn std::error::Error>> {
    let fixture = tempfile::tempdir()?;
    let executable = fixture.path().join("stalled-native-test");
    let descendant_pid = fixture.path().join("native-descendant-pid");
    write_executable(
        &executable,
        &format!(
            "#!/bin/sh\nfor argument in \"$@\"; do\n  if [ \"$argument\" = \"--list\" ]; then\n    exit 0\n  fi\ndone\nsleep 30 &\nprintf '%s\\n' \"$!\" > \"{}\"\nwait\n",
            descendant_pid.display(),
        ),
    )?;

    let started = Instant::now();
    let report = run_native_test_batch_all_in_directory_with_timeout(
        &executable,
        &BTreeMap::new(),
        Some(fixture.path()),
        Some(Duration::from_millis(100)),
    )?;

    assert!(report.timed_out, "stalled native test unexpectedly completed");
    assert!(!report.success, "timed-out native test was reported as successful");
    assert!(
        started.elapsed() < Duration::from_secs(5),
        "a descendant retaining output pipes held the timeout supervisor open"
    );
    assert!(descendant_pid.is_file(), "fake native-test descendant was not started");
    assert_process_stopped(read_pid(&descendant_pid)?)
}

#[test]
fn legacy_cargo_capacity_abort_terminates_descendants() -> Result<(), Box<dyn std::error::Error>> {
    let fixture = tempfile::tempdir()?;
    let project = fixture.path().join("generated-project");
    let source = project.join("src/main.rs");
    let cargo = fixture.path().join("cargo");
    let descendant_pid = fixture.path().join("cargo-descendant-pid");
    fs::create_dir_all(source.parent().ok_or("generated source has no parent")?)?;
    fs::write(
        project.join("Cargo.toml"),
        "[package]\nname = \"oven_pr_capacity_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )?;
    fs::write(
        project.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n",
    )?;
    fs::write(&source, "fn main() {}\n")?;
    write_executable(
        &cargo,
        &format!(
            "#!/bin/sh\nif [ \"$1\" = \"--version\" ]; then\n  printf '%s\\n' 'cargo oven-pr-fixture'\n  exit 0\nfi\ntarget_dir=''\nprevious=''\nfor argument in \"$@\"; do\n  if [ \"$previous\" = \"--target-dir\" ]; then\n    target_dir=$argument\n  fi\n  previous=$argument\ndone\nmkdir -p \"$target_dir\"\nsleep 30 &\nprintf '%s\\n' \"$!\" > \"{}\"\ndd if=/dev/zero of=\"$target_dir/overflow\" bs=131072 count=1 2>/dev/null\nwait\n",
            descendant_pid.display(),
        ),
    )?;
    let rustc = rustc_path()?;
    let receipt = receipt_generated_project(
        &OvenGeneratedProjectRequest::new(
            &project,
            "oven_pr_capacity_fixture",
            "0.1.0",
            rustc_host(&rustc)?,
            rustc_identity(&rustc)?,
            "debug",
            Vec::new(),
        )
        .with_generated_source("generated-root", &source),
    )?;
    let store_root = fixture.path().join("store");
    let store = OvenStore::new(&store_root, OvenStoreLimits::new(1024 * 1024, 64 * 1024, 1024 * 1024));

    let started = Instant::now();
    let result = prepare_direct_rustc_plan(&OvenLegacyCargoPrepareRequest {
        store: &store,
        receipt,
        generated_project: project,
        cargo,
        rustc,
        sdk_inventory: None,
        domain: "oven-pr-capacity".to_string(),
        publication_kind: OvenLegacyCargoPublicationKind::Executable,
        source_evidence_key: "generated-root".to_string(),
        compile_environment: BTreeMap::new(),
        compact_debug_info: false,
    });

    assert!(
        matches!(result, Err(OvenLegacyCargoError::TransientCapacityExceeded { .. })),
        "tiny transient allowance did not abort the legacy Cargo publisher: {result:?}"
    );
    assert!(
        started.elapsed() < Duration::from_secs(5),
        "capacity-aborted Cargo descendants outlived the publisher"
    );
    assert!(descendant_pid.is_file(), "fake Cargo descendant was not started");
    assert!(
        !store_root.join("legacy-cargo-staging").read_dir()?.any(|entry| {
            entry
                .ok()
                .is_some_and(|entry| entry.file_name().to_string_lossy().starts_with(".legacy-cargo-"))
        }),
        "capacity-aborted publisher staging was retained"
    );
    assert_process_stopped(read_pid(&descendant_pid)?)
}

fn write_executable(path: &Path, contents: &str) -> Result<(), Box<dyn std::error::Error>> {
    fs::write(path, contents)?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o755))?;
    Ok(())
}

fn rustc_path() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let output = Command::new("rustup").args(["which", "rustc"]).output()?;
    if !output.status.success() {
        return Err("rustup could not locate rustc".into());
    }
    let path = PathBuf::from(String::from_utf8(output.stdout)?.trim());
    if !path.is_file() {
        return Err(format!("rustup returned a non-file rustc path: {}", path.display()).into());
    }
    Ok(path)
}

fn rustc_identity(rustc: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new(rustc).arg("--version").output()?;
    if !output.status.success() {
        return Err("rustc could not report its version".into());
    }
    Ok(String::from_utf8(output.stdout)?.trim().to_string())
}

fn rustc_host(rustc: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new(rustc).arg("-vV").output()?;
    if !output.status.success() {
        return Err("rustc could not report its host target".into());
    }
    let version = String::from_utf8(output.stdout)?;
    version
        .lines()
        .find_map(|line| line.strip_prefix("host: ").map(str::to_string))
        .ok_or_else(|| "rustc verbose version omitted its host target".into())
}

fn read_pid(path: &Path) -> Result<u32, Box<dyn std::error::Error>> {
    Ok(fs::read_to_string(path)?.trim().parse()?)
}

fn assert_process_stopped(pid: u32) -> Result<(), Box<dyn std::error::Error>> {
    for _ in 0..100 {
        let status = Command::new("kill")
            .args(["-0", &pid.to_string()])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()?;
        if !status.success() {
            return Ok(());
        }
        std::thread::sleep(Duration::from_millis(10));
    }
    Err(format!("supervised descendant process {pid} remained alive").into())
}
