//! Representative generated-Rust snapshots for stdlib inventory gaps.
//!
//! This suite intentionally covers selected high-value stdlib surfaces rather than every stdlib source file. It keeps
//! direct stdlib snapshots separate from `codegen_snapshot_tests` so broad generated-Rust quality work can land without
//! conflicting with the general codegen snapshot suite.

use incan::backend::IrCodegen;
use incan::frontend::{lexer, parser};
use std::fs;

#[path = "support/builtin_stdlib.rs"]
mod builtin_stdlib_support;

type TestResult = Result<(), Box<dyn std::error::Error>>;

fn err_box(message: impl Into<String>) -> Box<dyn std::error::Error> {
    Box::new(std::io::Error::other(message.into()))
}

fn generate_rust(source: &str, context: &str) -> Result<String, Box<dyn std::error::Error>> {
    let tokens = lexer::lex(source).map_err(|errs| err_box(format!("{context} lexer failed: {errs:?}")))?;
    let ast = parser::parse(&tokens).map_err(|errs| err_box(format!("{context} parser failed: {errs:?}")))?;
    let mut codegen = IrCodegen::new();
    codegen.set_builtin_stdlib_artifact_module_paths(builtin_stdlib_support::artifact_module_paths());
    let code = codegen
        .try_generate(&ast)
        .map_err(|err| err_box(format!("{context} codegen failed: {err:?}")))?;
    Ok(normalize_codegen_output(&code))
}

fn normalize_codegen_output(code: &str) -> String {
    let from = format!(
        "// Generated by the Incan compiler v{}\n\n",
        incan::version::INCAN_VERSION
    );
    let to = "// Generated by the Incan compiler v<INCAN_VERSION>\n\n";
    code.replace(&from, to)
        .lines()
        .map(|line| {
            if line.starts_with("incan_stdlib::__incan_stdlib_version_check!(") {
                "incan_stdlib::__incan_stdlib_version_check!(\"<INCAN_STDLIB_VERSION>\");"
            } else {
                line
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn assert_stdlib_source_snapshot(snapshot_name: &str, path: &str) -> TestResult {
    let source = fs::read_to_string(path)?;
    let rust_code = generate_rust(&source, path)?;
    insta::assert_snapshot!(snapshot_name, rust_code);
    Ok(())
}

fn assert_import_snapshot(snapshot_name: &str, source: &str) -> TestResult {
    let rust_code = generate_rust(source, snapshot_name)?;
    insta::assert_snapshot!(snapshot_name, rust_code);
    Ok(())
}

#[test]
fn std_root_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_root_prelude_import",
        r#"
from std import Debug, Eq, Clone, From, Add, Error, Index, Callable1

def touch_debug(value: Debug) -> None:
    return

def touch_eq(value: Eq) -> None:
    return

def touch_clone(value: Clone) -> None:
    return

def touch_from(value: From[int]) -> None:
    return

def touch_add(value: Add[int]) -> None:
    return

def touch_error(value: Error) -> None:
    return

def touch_index(value: Index[int, str]) -> None:
    return

def touch_callable(value: Callable1[int, str]) -> None:
    return
"#,
    )
}

#[test]
fn std_async_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_async_prelude_import",
        r#"
import std.async
from std.async import sleep, spawn, JoinHandle, Mutex, RaceArm

async def work() -> int:
    await sleep(0.01)
    return 1

def touch_handle(handle: JoinHandle[int]) -> None:
    return

def touch_lock(lock: Mutex[int]) -> None:
    return

def launch() -> JoinHandle[int]:
    return spawn(work)

def touch_arm(arm_value: RaceArm[int]) -> None:
    return
"#,
    )
}

#[test]
fn std_datetime_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_datetime_prelude_import",
        r#"
from std.datetime import DateTimeError, Duration, Instant, SystemTime, TimeDelta, Date, Time, DateTime, FixedOffset

def touch_error(error: DateTimeError) -> None:
    return

def touch_duration(duration: Duration) -> None:
    return

def touch_instant(instant: Instant) -> None:
    return

def touch_system_time(time: SystemTime) -> None:
    return

def touch_delta(delta: TimeDelta) -> None:
    return

def touch_date(date: Date) -> None:
    return

def touch_time(time: Time) -> None:
    return

def touch_datetime(value: DateTime) -> None:
    return

def touch_offset(offset: FixedOffset) -> None:
    return
"#,
    )
}

#[test]
fn std_encoding_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_encoding_prelude_import",
        r#"
from std.encoding import base32, base64, hex, EncodingError

def touch_error(error: EncodingError) -> None:
    return

def encode_samples(value: bytes) -> tuple[str, str, str]:
    return (hex.b16encode(value), base32.b32encode(value), base64.b64encode(value))
"#,
    )
}

#[test]
fn std_serde_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_serde_prelude_import",
        r#"
from std.serde import json

@derive(json)
model SnapshotConfig:
    name: str
    enabled: bool

def encode_config(config: SnapshotConfig) -> str:
    return config.to_json()
"#,
    )
}

#[test]
fn std_telemetry_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_telemetry_prelude_import",
        r#"
from std.telemetry import TelemetryValue, Attributes, Resource, InstrumentationScope, SpanContext

def touch_value(value: TelemetryValue) -> str:
    return value.display_text()

def touch_attributes(attributes: Attributes) -> None:
    return

def touch_resource(resource: Resource) -> None:
    return

def touch_scope(scope: InstrumentationScope) -> None:
    return

def touch_span_context(context: SpanContext) -> None:
    return
"#,
    )
}

#[test]
fn std_web_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_web_prelude_import",
        r#"
import std.async
from std.web import App, Json, Html, Response, Query, Path, route, GET

model Search:
    q: str

@route("/snapshot/{id}", method=GET)
async def snapshot(id: Path[int], query: Query[Search]) -> Json[Search]:
    return Json(query.value)

def touch_app(app: App) -> None:
    return

def touch_response(response: Response) -> None:
    return

def render_html(value: str) -> Html:
    return Html(value)
"#,
    )
}

#[test]
fn std_result_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot("std_result_source", "crates/incan_stdlib/stdlib/result.incn")
}

#[test]
fn std_io_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot("std_io_source", "crates/incan_stdlib/stdlib/io.incn")
}

#[test]
fn std_telemetry_core_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot(
        "std_telemetry_core_source",
        "crates/incan_stdlib/stdlib/telemetry/core.incn",
    )
}

#[test]
fn std_compression_prelude_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot(
        "std_compression_prelude_source",
        "crates/incan_stdlib/stdlib/compression/prelude.incn",
    )
}

#[test]
fn std_compression_core_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot(
        "std_compression_core_source",
        "crates/incan_stdlib/stdlib/compression/_core.incn",
    )
}
