//! Regression coverage for the native call signature used by selected string helpers.

use incan::backend::IrCodegen;
use incan::frontend::{lexer, parser};
use incan_semantics_core::SemanticSourceTargetKind;

#[path = "support/canonical_projection.rs"]
mod canonical_projection;

/// An omitted separator still needs a concrete Rust type for the generic runtime parameter.
#[test]
fn omitted_split_separator_has_a_concrete_emitted_type() -> Result<(), Box<dyn std::error::Error>> {
    let source = include_str!("codegen_snapshots/string_split_default.incn");
    let tokens = lexer::lex(source).map_err(|errors| format!("{errors:?}"))?;
    let program = parser::parse(&tokens).map_err(|errors| format!("{errors:?}"))?;
    let mut codegen = IrCodegen::new();
    codegen.set_externally_reachable_items(std::collections::HashSet::from([String::from("split_default")]));
    let rust = codegen.try_generate(&program)?;
    let projection = canonical_projection::projected_name(&rust, "split_default", SemanticSourceTargetKind::Function);
    assert!(
        rust.contains(&format!("fn {projection}")) && rust.contains(&format!("use {projection} as split_default;")),
        "the regression must retain one canonical implementation and its Rust-facing entrypoint alias:\n{rust}"
    );
    assert!(
        rust.contains("None::<&str>"),
        "the omitted separator needs its generic argument type:\n{rust}"
    );
    let normalized = rust
        .replace(
            &format!(
                "// Generated by the Incan compiler v{}\n",
                incan::version::INCAN_VERSION
            ),
            "// Generated by the Incan compiler v<INCAN_VERSION>\n",
        )
        .replace(
            &format!(
                "incan_stdlib::__incan_stdlib_version_check!(\"{}\");",
                incan::version::INCAN_VERSION
            ),
            "incan_stdlib::__incan_stdlib_version_check!(\"<INCAN_STDLIB_VERSION>\");",
        );
    insta::assert_snapshot!("omitted_string_split_separator", normalized);
    Ok(())
}
