[project]
name = "incan_stdlib_web"
version = "0.5.0"
license = "Apache-2.0"
private = true

[sdk]
profile = "minimal"
components = ["stdlib-data", "stdlib-async"]

[rust-dependencies]
incan_web_macros = { path = "../derive/incan_web_macros" }
