[project]
name = "incan_stdlib_web"
version = "0.5.0"
license = "Apache-2.0"
private = true

[rust]
name = "incan_std_web"
type = "lib"
edition = "2024"

[rust.source]
root = "rust"

[sdk]
profile = "minimal"
components = ["stdlib-data", "stdlib-async"]

[dependencies]
axum = { loaf = "crates-io/axum", version = "0.8", features = [], default-features = true }
inventory = { loaf = "crates-io/inventory", version = "0.3", features = [], default-features = true }
tokio = { loaf = "crates-io/tokio", version = "1", features = ["net", "rt-multi-thread"], default-features = true }
incan_web_macros = { loaf = "incan_web_macros", path = "../derive/incan_web_macros" }
