//! The generated behavior roots: one libtest root per behavior-fixture area, one case per fixture.
//!
//! Each area declared under `fixture_roots` in `scripts/test_inventory/dispositions.json` has a root
//! `loaves/toolchain/incan-cli/tests/behavior_<area>_tests.rs` whose cases are exactly the area's fixtures, each
//! calling [`assert_fixture_holds`](crate::behavior_fixtures::assert_fixture_holds). The roots are rendered from the
//! areas and checked in, because the compiler suite plans roots from Cargo's unit graph with no build-script unit,
//! so a root generated at build time would have no place to be generated. One case per fixture is what lets the suite
//! schedule, slice and time fixtures individually and attribute a failure to its fixture by name.
//!
//! [`behavior_roots_match_their_areas`](tests) keeps the checked-in roots equal to the rendering: a fixture added,
//! renamed, removed or marked `pending:` fails it until `make behavior-roots` regenerates the roots, and so does a
//! behavior root left behind by an area that no longer exists.

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use crate::behavior_fixtures::{BEHAVIOR_FIXTURES_ROOT, BehaviorFixture, area_dir, discover};

/// The inventory record whose `fixture_roots` declare the behavior areas.
const DISPOSITIONS: &str = "scripts/test_inventory/dispositions.json";

/// The directory the generated roots live in, beside the CLI's other integration roots.
const ROOTS_DIR: &str = "loaves/toolchain/incan-cli/tests";

/// The case a root adds when its area has `pending:` fixtures; no fixture may take this name.
const PENDING_CASE: &str = "pending_fixtures_still_wait";

/// rustfmt's `fn_call_width` under the checkout's `max_width = 120` (60% of it): a call whose arguments are wider is
/// laid out one argument per line. The roots are rendered the way `make fmt` leaves them, so formatting the checkout
/// never makes them drift.
const RUSTFMT_CALL_WIDTH: usize = 72;

/// The first line of every generated root, which marks it as generated for readers and for [`stale_roots`].
const GENERATED_MARKER: &str = "//! @generated by `make behavior-roots` from the behavior-fixture area";

/// The behavior areas the inventory declares, by area name, in name order.
///
/// An area is a `fixture_roots` key directly under the behavior-fixture directory. The inventory is the one list of
/// areas: the collector counts their fixtures from it, and the roots are generated from it.
pub fn declared_areas() -> Result<Vec<String>, Box<dyn Error>> {
    let text = fs::read_to_string(crate::repo_root().join(DISPOSITIONS))?;
    let record: serde_json::Value = serde_json::from_str(&text)?;
    let roots = record
        .get("fixture_roots")
        .and_then(serde_json::Value::as_object)
        .ok_or_else(|| format!("{DISPOSITIONS} has no `fixture_roots` object"))?;
    let prefix = format!("loaves/compiler/incan_test_support/fixtures/{BEHAVIOR_FIXTURES_ROOT}/");
    let mut areas: Vec<String> = roots
        .keys()
        .filter_map(|key| key.strip_prefix(&prefix))
        .map(str::to_string)
        .collect();
    areas.sort();
    Ok(areas)
}

/// The checked-in root of one area.
pub fn root_path(area: &str) -> PathBuf {
    crate::repo_root().join(ROOTS_DIR).join(root_file_name(area))
}

/// The file name of an area's root: `behavior_<area>_tests.rs`.
fn root_file_name(area: &str) -> String {
    format!("behavior_{area}_tests.rs")
}

/// Render the root of one area from its fixtures, as `make fmt` leaves it.
///
/// A fixture's name becomes its case's name, so it must be a Rust identifier in the area's naming style: lowercase
/// ASCII letters, digits and underscores, starting with a letter, not a Rust keyword and not the name of the
/// pending check. A name that is not is refused rather than rewritten, because a rewritten name would make the case
/// and the fixture disagree on what the fixture is called.
pub fn render_root(area: &str) -> Result<String, Box<dyn Error>> {
    let fixtures = discover(&area_dir(area))?;
    for fixture in &fixtures {
        check_case_name(fixture)?;
    }
    Ok(render_root_from(area, &fixtures))
}

/// [`render_root`] over already-discovered fixtures, so the layout is testable without an area on disk.
fn render_root_from(area: &str, fixtures: &[BehaviorFixture]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push_str(&format!(" `{area}`.\n"));
    out.push_str("//!\n");
    out.push_str(&format!(
        "//! Fixtures: `loaves/compiler/incan_test_support/fixtures/{BEHAVIOR_FIXTURES_ROOT}/{area}/`.\n"
    ));
    out.push_str("//! One case per fixture; a `pending:` fixture's case is ignored with its reason.\n");
    out.push_str("//! Do not edit: change the area and run `make behavior-roots`.\n");
    out.push('\n');
    let has_pending = fixtures.iter().any(|fixture| fixture.header.pending.is_some());
    if has_pending {
        out.push_str(
            "use incan_test_support::behavior_fixtures::{assert_fixture_holds, assert_pending_fixtures_still_wait};\n",
        );
    } else {
        out.push_str("use incan_test_support::behavior_fixtures::assert_fixture_holds;\n");
    }
    out.push('\n');
    out.push_str("/// The area every case of this root runs a fixture of.\n");
    out.push_str(&format!("const AREA: &str = \"{area}\";\n"));
    out.push('\n');
    out.push_str("/// What every case returns: a harness error, or `Ok` once its fixture showed what it declares.\n");
    out.push_str("type CaseResult = Result<(), Box<dyn std::error::Error>>;\n");
    for fixture in fixtures {
        out.push('\n');
        out.push_str(&format!("/// Runs the fixture `{}`.\n", fixture.name));
        out.push_str("#[test]\n");
        if let Some(reason) = &fixture.header.pending {
            out.push_str(&format!("#[ignore = \"pending: {}\"]\n", escape(reason)));
        }
        out.push_str(&format!("fn {}() -> CaseResult {{\n", fixture.name));
        let arguments = format!("AREA, \"{}\"", fixture.name);
        if arguments.len() > RUSTFMT_CALL_WIDTH {
            out.push_str(&format!(
                "    assert_fixture_holds(\n        AREA,\n        \"{}\",\n    )\n",
                fixture.name
            ));
        } else {
            out.push_str(&format!("    assert_fixture_holds({arguments})\n"));
        }
        out.push_str("}\n");
    }
    if has_pending {
        out.push('\n');
        out.push_str("/// Every `pending:` fixture of the area still does not show what it declares.\n");
        out.push_str("#[test]\n");
        out.push_str(&format!("fn {PENDING_CASE}() -> CaseResult {{\n"));
        out.push_str("    assert_pending_fixtures_still_wait(AREA)\n");
        out.push_str("}\n");
    }
    out
}

/// Escape a header value for a Rust string literal.
fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Refuse a fixture name that cannot be its case's name; see [`render_root`].
fn check_case_name(fixture: &BehaviorFixture) -> Result<(), String> {
    let name = fixture.name.as_str();
    let shaped = name.chars().next().is_some_and(|first| first.is_ascii_lowercase())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    if !shaped || RUST_KEYWORDS.contains(&name) || name == PENDING_CASE {
        return Err(format!(
            "{}: the fixture name `{name}` cannot name its case; use lowercase letters, digits and underscores, starting with a letter, and neither a Rust keyword nor `{PENDING_CASE}`",
            fixture.display_path()
        ));
    }
    Ok(())
}

/// Rust's strict and reserved keywords, which a case name cannot be without a raw identifier.
const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate", "do", "dyn", "else",
    "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "macro", "match", "mod",
    "move", "mut", "override", "priv", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true",
    "try", "type", "typeof", "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

/// Generated behavior roots whose area is no longer declared: they would run fixtures of an area that is gone.
fn stale_roots(areas: &[String]) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let dir = crate::repo_root().join(ROOTS_DIR);
    let mut stale = Vec::new();
    for entry in fs::read_dir(&dir)? {
        let path = entry?.path();
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        let Some(area) = name
            .strip_prefix("behavior_")
            .and_then(|rest| rest.strip_suffix("_tests.rs"))
        else {
            continue;
        };
        if !areas.iter().any(|declared| declared == area) {
            stale.push(path);
        }
    }
    stale.sort();
    Ok(stale)
}

/// Compare every area's checked-in root with its rendering and list each difference; with `write`, rewrite the
/// roots that differ and remove the stale ones instead, and list what was changed.
///
/// A stale root is removed only when it carries [`GENERATED_MARKER`]; a hand-written `behavior_*_tests.rs` is
/// reported, never deleted.
pub fn sync_roots(write: bool) -> Result<Vec<String>, Box<dyn Error>> {
    let areas = declared_areas()?;
    let mut changes = Vec::new();
    for area in &areas {
        let path = root_path(area);
        let rendered = render_root(area)?;
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() == Some(rendered.as_str()) {
            continue;
        }
        let shown = display(&path);
        if write {
            fs::write(&path, rendered)?;
            changes.push(format!("wrote {shown}"));
        } else if current.is_none() {
            changes.push(format!("{shown} is missing"));
        } else {
            changes.push(format!("{shown} differs from its area"));
        }
    }
    for path in stale_roots(&areas)? {
        let shown = display(&path);
        let generated = fs::read_to_string(&path)?.starts_with(GENERATED_MARKER);
        if write && generated {
            fs::remove_file(&path)?;
            changes.push(format!("removed {shown}"));
        } else {
            changes.push(format!("{shown} runs no declared behavior area"));
        }
    }
    Ok(changes)
}

/// A path relative to the checkout, for messages.
fn display(path: &Path) -> String {
    path.strip_prefix(crate::repo_root())
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::behavior_fixtures::parse_fixture;

    type TestResult = Result<(), Box<dyn Error>>;

    /// The checked-in roots are exactly the rendering of the declared areas. `INCAN_WRITE_BEHAVIOR_ROOTS=1` (what
    /// `make behavior-roots` sets) rewrites them instead of failing.
    #[test]
    fn behavior_roots_match_their_areas() -> TestResult {
        let write = std::env::var_os("INCAN_WRITE_BEHAVIOR_ROOTS").is_some_and(|value| value == "1");
        let changes = sync_roots(write)?;
        if write {
            for change in &changes {
                eprintln!("{change}");
            }
            return Ok(());
        }
        assert!(
            changes.is_empty(),
            "the behavior roots do not match their areas; run `make behavior-roots`:\n  {}",
            changes.join("\n  ")
        );
        Ok(())
    }

    /// A root names its area once, gives each fixture a case, ignores a pending one with its reason, and adds the
    /// pending check only when the area has a pending fixture.
    #[test]
    fn a_root_has_one_case_per_fixture() -> TestResult {
        let tmp = tempfile::tempdir()?;
        fs::write(tmp.path().join("plain.incn"), "# behavior: b\n# expect-exit: 0\n")?;
        fs::write(
            tmp.path().join("red.incn"),
            "# behavior: b\n# pending: the \"direct\" route\n# expect-exit: 0\n",
        )?;
        let plain = parse_fixture(&tmp.path().join("plain.incn"))?;
        let red = parse_fixture(&tmp.path().join("red.incn"))?;

        let green_only = render_root_from("demo", std::slice::from_ref(&plain));
        assert!(green_only.starts_with(GENERATED_MARKER));
        assert!(green_only.contains("const AREA: &str = \"demo\";\n"));
        assert!(
            green_only.contains("#[test]\nfn plain() -> CaseResult {\n    assert_fixture_holds(AREA, \"plain\")\n}\n")
        );
        assert!(!green_only.contains(PENDING_CASE));
        assert!(green_only.contains("use incan_test_support::behavior_fixtures::assert_fixture_holds;\n"));

        let with_pending = render_root_from("demo", &[plain, red]);
        assert!(
            with_pending
                .contains("#[test]\n#[ignore = \"pending: the \\\"direct\\\" route\"]\nfn red() -> CaseResult {\n")
        );
        assert!(with_pending.contains(&format!(
            "fn {PENDING_CASE}() -> CaseResult {{\n    assert_pending_fixtures_still_wait(AREA)\n}}\n"
        )));
        Ok(())
    }

    /// A fixture whose name cannot be a case name is refused, not rewritten.
    #[test]
    fn a_fixture_name_must_be_a_case_name() -> TestResult {
        let tmp = tempfile::tempdir()?;
        for (name, accepted) in [
            ("ok_name_2", true),
            ("match", false),
            ("Upper", false),
            ("2nd", false),
            (PENDING_CASE, false),
        ] {
            let path = tmp.path().join(format!("{name}.incn"));
            fs::write(&path, "# behavior: b\n# expect-exit: 0\n")?;
            let checked = check_case_name(&parse_fixture(&path)?);
            assert_eq!(checked.is_ok(), accepted, "{name}: {checked:?}");
        }
        Ok(())
    }
}
