[project]
name = "incan_lang"
version = "0.6.0-dev.6"
license = "Apache-2.0"
private = true

[rust]
name = "incan_lang"
type = "lib"
edition = "2024"

[dependencies]
serde = { loaf = "crates-io/serde", version = "1", features = ["derive"], default-features = true }
