//! Read-only current producer-input validation for ordinary rooted native reuse (#1337, #1698).

use std::path::Path;

use super::{Error, PreparedUnit, SdkLockedUnit, Seed, environment, fact_out_files, index_fact, validate_seed};
use crate::native_loaf::{NativeLoafOrigin, NativeLoafRecord};

pub(crate) use super::local::{LocalDependencyCandidate, local_dependency_demands, select_local_dependency};
pub(crate) use super::native::NativeToolOwners;

/// Read a genuinely unselected registry candidate's source manifest without acquiring its native owner.
pub(crate) fn registry_source_manifest(blobs: &Path, binding: &SdkLockedUnit) -> Result<toml::Value, Error> {
    let hex = binding
        .archive_digest
        .strip_prefix("sha256:")
        .ok_or("invalid current candidate archive digest")?;
    if hex.len() != 64 || !hex.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err("invalid current candidate archive digest".into());
    }
    let archive = oven_store::source_archive::VerifiedLoafArchive::read(
        &blobs.join(format!("{hex}.tar")),
        &binding.archive_digest,
    )?;
    let manifest: toml::Value = toml::from_str(std::str::from_utf8(archive.manifest()?)?)?;
    if manifest
        .get("project")
        .and_then(|project| project.get("name"))
        .and_then(toml::Value::as_str)
        != Some(&binding.loaf)
        || manifest
            .get("project")
            .and_then(|project| project.get("version"))
            .and_then(toml::Value::as_str)
            != Some(&binding.version)
    {
        return Err("current candidate archive differs from its resolution binding".into());
    }
    Ok(manifest)
}

/// Parse and validate the exact resolution contract shared with native preparation, without preparing units.
pub(crate) fn read_resolution(path: &Path) -> Result<Seed, Error> {
    read_resolution_bytes(&std::fs::read(path)?)
}

/// Validate the same exact bytes whose digest keys a prepared-consumer hint.
pub(crate) fn read_resolution_bytes(bytes: &[u8]) -> Result<Seed, Error> {
    let seed = serde_json::from_slice(bytes)?;
    validate_seed(&seed)?;
    Ok(seed)
}

/// Read current adoption metadata only for the rooted registry bindings, using the original pinned event projection.
pub(crate) fn selected_about(
    index: &Path,
    commit: &str,
    bindings: &[SdkLockedUnit],
) -> Result<std::collections::BTreeMap<String, serde_json::Value>, Error> {
    environment::adopted_about(index, commit, bindings)
}

/// Reproduce current fact/environment/codegen inputs without source staging, generated writes or native preparation.
pub(crate) fn matches_current_recipe(
    record: &NativeLoafRecord,
    manifest: &toml::Value,
    origin: NativeLoafOrigin,
    seed: &Seed,
    index: &Path,
    commit: &str,
    about: &serde_json::Value,
    tools: &mut NativeToolOwners,
) -> Result<bool, Error> {
    let binding: SdkLockedUnit = serde_json::from_value(serde_json::to_value(&record.source)?)?;
    let fact = if origin == NativeLoafOrigin::Registry {
        index_fact(
            index,
            commit,
            &binding,
            &record.recipe.intent.target,
            &record.recipe.intent.toolchain,
            &record.recipe.intent.profile,
        )?
    } else {
        None
    };
    let fact_input = fact.as_ref().map(serde_json::to_string).transpose()?;
    if record.recipe.sources.build_unit_inputs.get("sdk-build-fact") != fact_input.as_ref() {
        return Ok(false);
    }
    if let Some(fact) = &fact {
        if !fact.tool.is_empty() {
            return Err("exact fact requires retained publisher tool assets".into());
        }
        // Verify current pinned generated bytes against their declared identities, without materializing them.
        let _ = fact_out_files(index, commit, &binding, fact)?;
        tools.verify(fact)?;
    }
    let codegen = if origin == NativeLoafOrigin::Registry {
        seed.unit_codegen
            .iter()
            .find(|selection| {
                selection.loaf == binding.loaf
                    && selection.version == binding.version
                    && selection.domain == binding.domain
            })
            .map(|selection| serde_json::to_string(&selection.options))
            .transpose()?
    } else {
        None
    };
    if record.recipe.sources.build_unit_inputs.get("sdk-codegen-options") != codegen.as_ref() {
        return Ok(false);
    }
    let values = current_environment(&binding, manifest, origin, about, fact.as_ref())?;
    Ok(
        record.recipe.sources.build_unit_inputs.get("sdk-compile-environment")
            == Some(&serde_json::to_string(&values)?),
    )
}

/// Reproduce the producer's current package/fact environment through its original shared projection.
pub(crate) fn current_environment(
    binding: &SdkLockedUnit,
    manifest: &toml::Value,
    origin: NativeLoafOrigin,
    about: &serde_json::Value,
    fact: Option<&oven_model::manifest::RustFactRecord>,
) -> Result<std::collections::BTreeMap<String, String>, Error> {
    let primary = origin == NativeLoafOrigin::Local;
    let root = environment::stable_source_root(binding, about, primary, fact)?;
    let unit = PreparedUnit {
        binding: binding.clone(),
        source_origin: origin,
        about: about.clone(),
        primary,
        _source_lease: None,
        root,
        manifest: manifest.clone(),
        build_script: false,
        fact: fact.cloned(),
        fact_out: Vec::new(),
    };
    let mut values = environment::package_environment(&unit)?;
    if let Some(fact) = fact {
        super::apply_fact_environment(&unit.root, fact, &mut values)?;
    }
    Ok(values)
}
