[package]
name = "incan_stdlib"
description = "Standard library for Incan-generated Rust code"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
incan_core = { workspace = true }
incan_derive = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
axum = { version = "0.8", optional = true }
tokio = { workspace = true, optional = true, features = ["rt-multi-thread", "macros", "time", "sync", "net"] }
inventory = { version = "0.3", optional = true }
xxhash_rust = { package = "xxhash-rust", version = "0.8", optional = true, features = ["xxh3"] }

[features]
default = []
ordinal = ["dep:xxhash_rust"]
json = ["dep:serde", "dep:serde_json"]
async = ["dep:tokio"]
web = ["dep:axum", "async", "dep:serde", "dep:inventory"]
