//! Representative generated-Rust snapshots for stdlib inventory gaps.
//!
//! This suite intentionally covers selected high-value stdlib surfaces rather than every stdlib source file. It keeps
//! direct stdlib snapshots separate from `codegen_snapshot_tests` so broad generated-Rust quality work can land without
//! conflicting with the general codegen snapshot suite.

use incan_emit::IrCodegen;
use incan_frontend::{lexer, parser};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use incan_test_support as support;

use incan_test_support::builtin_stdlib as builtin_stdlib_support;

use incan_test_support::canonical_projection;

type TestResult = Result<(), Box<dyn std::error::Error>>;

fn err_box(message: impl Into<String>) -> Box<dyn std::error::Error> {
    Box::new(std::io::Error::other(message.into()))
}

fn generate_rust(source: &str, context: &str) -> Result<String, Box<dyn std::error::Error>> {
    let tokens = lexer::lex(source).map_err(|errs| err_box(format!("{context} lexer failed: {errs:?}")))?;
    let ast = parser::parse(&tokens).map_err(|errs| err_box(format!("{context} parser failed: {errs:?}")))?;
    let mut codegen = IrCodegen::new();
    codegen.set_sdk_provider_module_paths(builtin_stdlib_support::artifact_module_paths());
    let code = codegen
        .try_generate(&ast)
        .map_err(|err| err_box(format!("{context} codegen failed: {err:?}")))?;
    Ok(normalize_codegen_output(&code))
}

/// Normalize one generated stdlib artifact for snapshotting.
///
/// Beyond pinning the compiler and stdlib version strings, this decodes RFC 120 symbol projections back to the
/// spellings the stdlib source used. An encoded projection carries its declaration span, so snapshotting the raw
/// identifiers made these goldens churn on any edit that moved a line: a single added comment in `io.incn` rewrites
/// every projected identifier below it. `codegen_snapshot_tests` decodes for the same reason; this suite was reading
/// the raw names, which is why its goldens still carried them.
fn normalize_codegen_output(code: &str) -> String {
    let from = format!(
        "// Generated by the Incan compiler v{}\n\n",
        incan_lang::version::INCAN_VERSION
    );
    let to = "// Generated by the Incan compiler v<INCAN_VERSION>\n\n";
    let normalized = code
        .replace(&from, to)
        .lines()
        .map(|line| {
            if line.starts_with("incan_std_core::__incan_stdlib_version_check!(") {
                "incan_std_core::__incan_stdlib_version_check!(\"<INCAN_STDLIB_VERSION>\");"
            } else {
                line
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    canonical_projection::decoded_source_spellings(&normalized)
}

fn assert_stdlib_source_snapshot(snapshot_name: &str, path: &str) -> TestResult {
    let source = fs::read_to_string(support::repo_root().join(path))?;
    let context = path.to_string();
    let rust_code = incan_frontend::compiler_stack::run_on_compiler_stack(move || {
        generate_rust(&source, &context).map_err(|error| error.to_string())
    })
    .map_err(err_box)?;
    insta::assert_snapshot!(snapshot_name, rust_code);
    Ok(())
}

fn assert_import_snapshot(snapshot_name: &str, source: &str) -> TestResult {
    let rust_code = generate_rust(source, snapshot_name)?;
    insta::assert_snapshot!(snapshot_name, rust_code);
    Ok(())
}

/// Copy one complete stdlib tree without changing the checkout source used by other tests.
fn copy_stdlib_tree(source: &Path, destination: &Path) -> std::io::Result<()> {
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let file_name = entry.file_name();
        if matches!(file_name.to_str(), Some("target" | ".incan" | ".git")) {
            continue;
        }
        let destination_path = destination.join(file_name);
        if entry.file_type()?.is_dir() {
            copy_stdlib_tree(&source_path, &destination_path)?;
        } else {
            fs::copy(source_path, destination_path)?;
        }
    }
    Ok(())
}

/// Generate normalized `std.io` Rust in a fresh process whose stdlib source authority is `stdlib_root`.
fn generate_std_io_from_root(stdlib_root: &Path, output_path: &Path) -> TestResult {
    const CHILD_MODE: &str = "INCAN_TEST_1592_CHILD";
    let output = Command::new(std::env::current_exe()?)
        .args([
            "--exact",
            "issue_1592_std_io_is_invariant_to_collection_comment",
            "--nocapture",
        ])
        .env(CHILD_MODE, "1")
        .env("INCAN_STDLIB", stdlib_root)
        .env("INCAN_STDLIB_DIR", stdlib_root)
        .env("INCAN_TEST_1592_OUTPUT", output_path)
        .output()?;
    if !output.status.success() {
        return Err(err_box(format!(
            "#1592 codegen child failed for {}:\n{}\n{}",
            stdlib_root.display(),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        )));
    }
    Ok(())
}

/// Return the child-process output path used by the #1592 replay, when this invocation is a child.
fn issue_1592_child_output() -> Option<PathBuf> {
    std::env::var_os("INCAN_TEST_1592_CHILD")?;
    std::env::var_os("INCAN_TEST_1592_OUTPUT").map(PathBuf::from)
}

#[test]
fn std_root_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_root_prelude_import",
        r#"
from std import Debug, Eq, Clone, From, Add, Error, Index, Callable1

def touch_debug(value: Debug) -> None:
    return

def touch_eq(value: Eq) -> None:
    return

def touch_clone(value: Clone) -> None:
    return

def touch_from(value: From[int]) -> None:
    return

def touch_add(value: Add[int]) -> None:
    return

def touch_error(value: Error) -> None:
    return

def touch_index(value: Index[int, str]) -> None:
    return

def touch_callable(value: Callable1[int, str]) -> None:
    return
"#,
    )
}

#[test]
fn std_async_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_async_prelude_import",
        r#"
import std.async
from std.async import sleep, spawn, JoinHandle, Mutex, RaceArm

async def work() -> int:
    await sleep(0.01)
    return 1

def touch_handle(handle: JoinHandle[int]) -> None:
    return

def touch_lock(lock: Mutex[int]) -> None:
    return

def launch() -> JoinHandle[int]:
    return spawn(work)

def touch_arm(arm_value: RaceArm[int]) -> None:
    return
"#,
    )
}

#[test]
fn std_datetime_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_datetime_prelude_import",
        r#"
from std.datetime import DateTimeError, Duration, Instant, SystemTime, TimeDelta, Date, Time, DateTime, FixedOffset

def touch_error(error: DateTimeError) -> None:
    return

def touch_duration(duration: Duration) -> None:
    return

def touch_instant(instant: Instant) -> None:
    return

def touch_system_time(time: SystemTime) -> None:
    return

def touch_delta(delta: TimeDelta) -> None:
    return

def touch_date(date: Date) -> None:
    return

def touch_time(time: Time) -> None:
    return

def touch_datetime(value: DateTime) -> None:
    return

def touch_offset(offset: FixedOffset) -> None:
    return
"#,
    )
}

#[test]
fn std_encoding_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_encoding_prelude_import",
        r#"
from std.encoding import base32, base64, hex, EncodingError

def touch_error(error: EncodingError) -> None:
    return

def encode_samples(value: bytes) -> tuple[str, str, str]:
    return (hex.b16encode(value), base32.b32encode(value), base64.b64encode(value))
"#,
    )
}

#[test]
fn std_serde_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_serde_prelude_import",
        r#"
from std.serde import json

@derive(json)
model SnapshotConfig:
    name: str
    enabled: bool

def encode_config(config: SnapshotConfig) -> str:
    return config.to_json()
"#,
    )
}

#[test]
fn std_telemetry_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_telemetry_prelude_import",
        r#"
from std.telemetry import TelemetryValue, Attributes, Resource, InstrumentationScope, SpanContext

def touch_value(value: TelemetryValue) -> str:
    return value.display_text()

def touch_attributes(attributes: Attributes) -> None:
    return

def touch_resource(resource: Resource) -> None:
    return

def touch_scope(scope: InstrumentationScope) -> None:
    return

def touch_span_context(context: SpanContext) -> None:
    return
"#,
    )
}

#[test]
fn std_web_prelude_import_snapshot() -> TestResult {
    assert_import_snapshot(
        "std_web_prelude_import",
        r#"
import std.async
from std.web import App, Json, Html, Response, Query, Path, route, GET

model Search:
    q: str

@route("/snapshot/{id}", method=GET)
async def snapshot(id: Path[int], query: Query[Search]) -> Json[Search]:
    return Json(query.value)

def touch_app(app: App) -> None:
    return

def touch_response(response: Response) -> None:
    return

def render_html(value: str) -> Html:
    return Html(value)
"#,
    )
}

#[test]
fn std_result_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot("std_result_source", "loaves/stdlib/core/src/result.incn")
}

#[test]
/// `std.environ` reads the argument vector through `std::env::args` (#1668); the snapshot pins that host call.
fn std_environ_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot("std_environ_source", "loaves/stdlib/system/src/environ.incn")
}

#[test]
fn std_io_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot("std_io_source", "loaves/stdlib/system/src/io.incn")
}

#[test]
/// Generated `std.io` must not depend on an imported trait default's absolute source position.
fn issue_1592_std_io_is_invariant_to_collection_comment() -> TestResult {
    if let Some(output_path) = issue_1592_child_output() {
        let stdlib_root = PathBuf::from(std::env::var_os("INCAN_STDLIB").ok_or("#1592 child needs INCAN_STDLIB")?);
        let source_path = stdlib_root.join("system/src/io.incn");
        let source = fs::read_to_string(&source_path)?;
        let context = source_path.display().to_string();
        let generated = incan_frontend::compiler_stack::run_on_compiler_stack(move || {
            generate_rust(&source, &context).map_err(|error| error.to_string())
        })
        .map_err(err_box)?;
        fs::write(output_path, generated)?;
        return Ok(());
    }

    let workspace = tempfile::tempdir()?;
    let checkout_stdlib = support::repo_root().join("loaves/stdlib");
    let baseline_root = workspace.path().join("baseline-stdlib");
    let shifted_root = workspace.path().join("shifted-stdlib");
    copy_stdlib_tree(&checkout_stdlib, &baseline_root)?;
    copy_stdlib_tree(&checkout_stdlib, &shifted_root)?;

    let collection_path = shifted_root.join("core/src/derives/collection.incn");
    let collection = fs::read_to_string(&collection_path)?;
    let shifted = collection.replacen(
        "\npub trait FallibleIterator[T, E]:",
        "\n# Issue 1592 inert source-location shift.\npub trait FallibleIterator[T, E]:",
        1,
    );
    if shifted == collection {
        return Err(err_box("#1592 fixture could not find FallibleIterator insertion point"));
    }
    fs::write(collection_path, shifted)?;

    let baseline_output = workspace.path().join("baseline.rs");
    let shifted_output = workspace.path().join("shifted.rs");
    generate_std_io_from_root(&baseline_root, &baseline_output)?;
    generate_std_io_from_root(&shifted_root, &shifted_output)?;

    let baseline = fs::read_to_string(baseline_output)?;
    let shifted = fs::read_to_string(shifted_output)?;
    assert_eq!(
        baseline, shifted,
        "an inert collection.incn comment changed generated std.io Rust"
    );
    Ok(())
}

#[test]
fn std_telemetry_core_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot(
        "std_telemetry_core_source",
        "loaves/stdlib/observability/src/telemetry/core.incn",
    )
}

#[test]
fn std_compression_prelude_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot(
        "std_compression_prelude_source",
        "loaves/stdlib/compression/src/compression/prelude.incn",
    )
}

#[test]
fn std_compression_core_source_snapshot() -> TestResult {
    assert_stdlib_source_snapshot(
        "std_compression_core_source",
        "loaves/stdlib/compression/src/compression/_core.incn",
    )
}
