//! The stable #987 seed corpus: every case with its ID, category, evidence lane, disposition and evaluate
//! callback.

use super::*;

/// The stable #987 corpus, including RFC 120's executable checked-identity and artifact-projection rows, and
/// #1339's package-execution rows. Package/import execution is now a proven row rather than a named #989
/// boundary: one case executes a published package through its executable representation and one proves the
/// refusal, both still asserted explicitly rather than inferred from a passing build.
pub(super) fn seed_corpus() -> Vec<ParityCase> {
    vec![
        ParityCase {
            id: "parity-987-0001",
            title: "Match expressions over enums must be exhaustive",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_supported_match_exhaustiveness",
            disposition: Disposition::Preserved,
            source: CASE_1_SRC,
            evaluate: Some(case_supported_match_exhaustiveness),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0002",
            title: "Chained comparisons are rejected with a type-mismatch diagnostic",
            category: BehaviorCategory::DiagnosticBehavior,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_diagnostic_chained_comparison_rejected",
            disposition: Disposition::Preserved,
            source: CASE_2_SRC,
            evaluate: Some(case_diagnostic_chained_comparison_rejected),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0003",
            title: "String membership (`in`) matches the runtime helper's substring policy",
            category: BehaviorCategory::StdlibRuntimeBehavior,
            lane: EvidenceLane::GeneratedProjectRun,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_stdlib_runtime_string_membership",
            disposition: Disposition::Preserved,
            source: CASE_3_SRC,
            evaluate: Some(case_stdlib_runtime_string_membership),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0004",
            title: "Generated Rust stays syntactically valid and inspectable, not the semantic contract",
            category: BehaviorCategory::GeneratedArtifactBehavior,
            lane: EvidenceLane::CodegenSnapshot,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_generated_artifact_valid_rust_shape",
            disposition: Disposition::Preserved,
            source: CASE_4_SRC,
            evaluate: Some(case_generated_artifact_valid_rust_shape),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0005",
            title: "A lexical builtin-name collision (`len`) preserves the module binding",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_supported_builtin_len_shadowing",
            disposition: Disposition::Preserved,
            source: CASE_5_SRC,
            evaluate: Some(case_supported_builtin_len_shadowing),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0006",
            title: "Dead code after `return` reports an unreachable-code warning (INCAN-T0101)",
            category: BehaviorCategory::DiagnosticBehavior,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_diagnostic_unreachable_code_after_return",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1117,
                migration_note: "Migrated by #1117 before 0.6 cutover: statements after a `return` in the same \
                                  block now raise the non-fatal `INCAN-T0101` warning instead of typechecking \
                                  silently. Migration guidance for the replacement backend: the contract is the \
                                  frontend diagnostic, not generated Rust's own `unreachable_code` lint, so a \
                                  replacement backend must not be relied on to reproduce it. The rule is \
                                  deliberately block-local — it does not model divergence through `if`/`else`, \
                                  `match`, or loops — and existing user code with dead code still compiles, \
                                  because the diagnostic is a warning and never an error.",
            },
            source: CASE_6_SRC,
            evaluate: Some(case_diagnostic_unreachable_code_after_return),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0007",
            title: "Statement tuple unpack of a non-tuple value is a typechecker error",
            category: BehaviorCategory::DiagnosticBehavior,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_diagnostic_statement_tuple_unpack_of_non_tuple",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1132,
                migration_note: "Migrated by #1132 before 0.6 cutover: `a, b = <non-tuple>` and the `TupleAssign` \
                                  spelling now raise a source-span typechecker error naming the resolved value \
                                  type, instead of binding every name `Unknown` and failing later in generated \
                                  Rust. Migration guidance for the replacement backend: the contract is the \
                                  frontend diagnostic, so a replacement backend must not be relied on to \
                                  reproduce it, and must never emit a tuple-field projection into a value with no \
                                  such fields. A value is destructurable only when its shape is actually known: \
                                  inferred tuples, annotated `tuple[A, B]`, and Rust-interop paths whose tuple \
                                  spelling the compiler can read. `Unknown` and `Never` stay silent as recovery \
                                  states; a bare type variable and an opaque Rust path are both refused, because \
                                  \"not proven tuple-shaped\" must not be treated as destructurable.",
            },
            source: CASE_7_SRC,
            evaluate: Some(case_diagnostic_statement_tuple_unpack_of_non_tuple),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0008",
            title: "Named `model` construction lowers to Body IR with a resolved field binding",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1158; src/frontend/body_ir.rs::tests::named_construction_lowers_to_a_constructor_aggregate_with_a_resolved_field_binding",
            disposition: Disposition::Preserved,
            source: CASE_8_SRC,
            evaluate: Some(case_supported_named_construction_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0009",
            title: "Named, out-of-order, and defaulted call arguments lower to Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1158; src/frontend/body_ir.rs::tests::{out_of_order_named_call_arguments_evaluate_in_written_source_order, an_omitted_defaulted_argument_is_recorded_as_a_defaulted_slot}",
            disposition: Disposition::Preserved,
            source: CASE_9_SRC,
            evaluate: Some(case_supported_named_call_arguments_reach_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0010",
            title: "`await` lowers to a Body IR suspension point with a destination",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1164; src/frontend/body_ir.rs::tests::lowers_await_as_an_explicit_suspension_point_with_a_destination",
            disposition: Disposition::Preserved,
            source: CASE_10_SRC,
            evaluate: Some(case_supported_await_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0011",
            title: "`race for` lowers to a Body IR race with per-arm bindings and bodies",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1164; src/frontend/body_ir.rs::tests::lowers_a_two_arm_race_with_per_arm_bindings_and_pre_selection_awaitables",
            disposition: Disposition::Preserved,
            source: CASE_11_SRC,
            evaluate: Some(case_supported_race_for_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0012",
            title: "List and dict literal spreads lower with their fixed elements intact",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1159; src/frontend/body_ir.rs::tests::fixed_elements_keep_their_positions_on_both_sides_of_a_spread",
            disposition: Disposition::Preserved,
            source: CASE_12_SRC,
            evaluate: Some(case_supported_literal_spreads_reach_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0013",
            title: "Positional, spread, named, and keyword-spread call arguments lower together",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1159; src/frontend/body_ir.rs::tests::a_mixed_call_keeps_every_written_argument_form",
            disposition: Disposition::Preserved,
            source: CASE_13_SRC,
            evaluate: Some(case_supported_call_spreads_reach_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0014",
            title: "String membership (`in`) is representable in Body IR, not only in the runtime helper",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1160; loaves/compiler/incan_frontend/src/body_ir/tests/operators_literals_and_assignment.rs::lowers_string_membership_as_an_explicit_helper_call_with_its_runtime_requirement",
            disposition: Disposition::Preserved,
            source: CASE_3_SRC,
            evaluate: Some(case_supported_string_membership_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0015",
            title: "Byte-string literals are representable in Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1165; loaves/compiler/incan_frontend/src/body_ir/tests/operators_literals_and_assignment.rs::bytes_literals_lower_to_their_own_constant_rather_than_a_string",
            disposition: Disposition::Preserved,
            source: CASE_15_SRC,
            evaluate: Some(case_supported_bytes_literal_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0016",
            title: "A range bound to a local is representable in Body IR and iterates from that value",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1165; loaves/compiler/incan_frontend/src/body_ir/tests/control_flow_and_loops.rs::a_bound_range_iterates_with_the_same_facts_as_the_inline_range",
            disposition: Disposition::Preserved,
            source: CASE_16_SRC,
            evaluate: Some(case_supported_range_value_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0018",
            title: "Statement-position `loop:` is representable in Body IR, not only the expression spelling",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1162; loaves/compiler/incan_frontend/src/body_ir/tests/control_flow_and_loops.rs::a_statement_position_loop_lowers_to_the_same_loop_the_expression_spelling_produces",
            disposition: Disposition::Preserved,
            source: CASE_18_SRC,
            evaluate: Some(case_supported_statement_loop_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0019",
            title: "An `unsafe:` acknowledgment region refuses in Body IR under a named, stated boundary",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1162; loaves/compiler/incan_frontend/src/body_ir/tests/input_contract_and_refusals.rs::an_unsafe_region_refuses_under_a_named_permanent_boundary",
            // The corpus's first real `Unsupported` row, so it carries the full migration note the schema asks
            // for rather than a pointer to one.
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1162,
                migration_note: "An `unsafe:` region records an explicit acknowledgment that the operations \
                                 inside it require authorization. It introduces no separate Incan scope, so \
                                 lowering its statements into the enclosing block would be a two-line change — \
                                 and would erase exactly the fact the region exists to carry, leaving a direct \
                                 replacement execution profile running an authorized region it was never told \
                                 about. Body IR v0 has no acknowledgment fact a consumer could weigh, so the \
                                 region refuses under a named label stating that it is refused by design \
                                 (`BodyBuilder::refuse_unsafe_region` in src/frontend/body_ir/stmt.rs). \
                                 Cutover impact: a program whose `unsafe:` region must execute cannot use the \
                                 replacement backend; the legacy Rust-emission backend keeps compiling it \
                                 unchanged, so no accepted program regresses. Reversing this disposition means \
                                 designing the acknowledgment representation first and deciding who may admit \
                                 it — adding a dispatch arm alone would be the silent execution this row \
                                 exists to prevent. \
                                 \
                                 This is a deliberate, settled boundary for 0.6, not deferred work: `unsafe:` stays \
                                 restricted to the C ABI, so there is no acknowledgment representation to design \
                                 within this release and nothing for the replacement route to admit. #1162 named the \
                                 residual refusals and closed having done so, which is why this row is an intentional \
                                 migration rather than an unsupported one awaiting an owner. Widening `unsafe:` \
                                 beyond the C ABI is what would reopen the question.",
            },
            source: CASE_19_SRC,
            evaluate: Some(case_unsafe_region_is_a_stated_refusal),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0020",
            title: "A pattern assertion binds its payload as a declared local",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1167; loaves/compiler/incan_frontend/src/body_ir/tests/patterns_and_assertions.rs::\
                       a_pattern_assertion_binding_is_a_declared_local_read_by_the_statements_after_it",
            disposition: Disposition::Preserved,
            source: CASE_20_SRC,
            evaluate: Some(case_pattern_assertion_binding_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0022",
            title: "Collection membership names the container it was written over",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1246; loaves/compiler/incan_frontend/src/body_ir/tests/operators_literals_and_assignment.rs::\
                       lowers_collection_membership_as_a_helper_call_naming_its_own_container",
            disposition: Disposition::Preserved,
            source: CASE_22_SRC,
            evaluate: Some(case_collection_membership_names_its_container),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0023",
            title: "List concatenation is a helper call rather than a primitive addition",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1246; loaves/compiler/incan_frontend/src/body_ir/tests/operators_literals_and_assignment.rs::\
                       lowers_list_concatenation_as_a_helper_call_rather_than_a_primitive_addition",
            disposition: Disposition::Preserved,
            source: CASE_23_SRC,
            evaluate: Some(case_list_concatenation_is_not_a_primitive_addition),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0021",
            title: "A `raises` assertion carries its resolved expected error type",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1167; loaves/compiler/incan_frontend/src/body_ir/tests/patterns_and_assertions.rs::\
                       a_raises_assertion_retains_the_resolved_expected_error_rather_than_its_spelling",
            disposition: Disposition::Preserved,
            source: CASE_21_SRC,
            evaluate: Some(case_raises_assertion_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-0017",
            title: "A body behind an inactive feature never reaches Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectParserTypechecker,
            evidence: "#1166; src/cli/commands/build.rs::tests::\
                       the_replacement_build_never_executes_a_main_behind_an_inactive_feature",
            disposition: Disposition::Preserved,
            source: CASE_17_SRC,
            evaluate: Some(case_inactive_feature_body_never_reaches_body_ir),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "replacement-body-v0-001",
            title: "Parameterized integer addition executes through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#988 replacement-body-v0-001 executed directly; #1146 two-route comparison in \
                       loaves/compiler/incan_driver/tests/shadow_comparison_tests.rs and loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::seed_corpus",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_001_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "add",
                arguments: replacement_body_v0_001_arguments,
                expected: replacement_body_v0_001_expected,
                // The original #1146 scalar case now uses the separate typed-result report, never a program stream.
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-002",
            title: "Parameterized string concatenation executes through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#988 replacement-body-v0-002; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::seed_corpus",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_002_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "greet",
                arguments: replacement_body_v0_002_arguments,
                expected: replacement_body_v0_002_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-003",
            title: "Owned local return preserves move evidence through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#988 replacement-body-v0-003; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::seed_corpus",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_003_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "return_owned",
                arguments: replacement_body_v0_003_arguments,
                expected: replacement_body_v0_003_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-004",
            title: "Normalized range, branch, and while control flow execute through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#988 replacement-body-v0-004; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::seed_corpus",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_004_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "control_flow",
                arguments: replacement_body_v0_004_arguments,
                expected: replacement_body_v0_004_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-005",
            title: "Assertion and floor division execute through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#988 replacement-body-v0-005; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::seed_corpus",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_005_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "guarded_floor_div",
                arguments: replacement_body_v0_005_arguments,
                expected: replacement_body_v0_005_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-006",
            title: "Scalar tuple collection loops destructure through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#988 replacement-body-v0-006; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::seed_corpus",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_006_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "select_second_pair",
                arguments: replacement_body_v0_006_arguments,
                expected: replacement_body_v0_006_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-007",
            title: "Lazy generator expressions materialize through Body IR only when collected",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1123; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_a_lazy_generator_expression_only_when_collect_consumes_it",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_007_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "collect_lazy_values",
                arguments: replacement_body_v0_007_arguments,
                expected: replacement_body_v0_007_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-008",
            title: "Captured stored closures execute in isolated direct Body-IR frames",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1152; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_a_captured_stored_closure_in_an_isolated_frame",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_008_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "stored_closure",
                arguments: replacement_body_v0_008_arguments,
                expected: replacement_body_v0_008_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-009",
            title: "Partial presets and declaration defaults bind through direct Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1152; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_partial_presets_source_defaults_and_named_overrides",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_009_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "partial_defaults",
                arguments: replacement_body_v0_009_arguments,
                expected: replacement_body_v0_009_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-010",
            title: "Generator-function frames resume directly through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1152; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_resumes_a_generator_function_without_replaying_its_prefix",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_010_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "generator_function",
                arguments: replacement_body_v0_010_arguments,
                expected: replacement_body_v0_010_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-011",
            title: "Lazy generator map and filter adapters invoke local Body-IR callables",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1152; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_lazy_generator_adapters_with_local_callbacks",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_011_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "generator_adapters",
                arguments: replacement_body_v0_011_arguments,
                expected: replacement_body_v0_011_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-012",
            title: "Source-local tuple/list values and exact sibling dispatch execute through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1154; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_source_local_tuple_list_index_and_mutation_through_a_direct_callable; comparison remains non-green until #1154 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_012_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "structural_values",
                arguments: replacement_body_v0_012_arguments,
                expected: replacement_body_v0_012_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-013",
            title: "Source-local plain model values and canonical field reads execute through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1154; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_source_local_nominal_model_values_through_a_direct_callable; comparison remains non-green until #1154 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_013_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "nominal_values",
                arguments: replacement_body_v0_013_arguments,
                expected: replacement_body_v0_013_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-014",
            title: "Source-local RFC 032 value-enum members extract scalar values through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1154; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_source_local_value_enum_members_through_a_direct_callable; comparison remains non-green until #1154 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_014_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "value_enum_values",
                arguments: replacement_body_v0_014_arguments,
                expected: replacement_body_v0_014_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-015",
            title: "Source-local fieldless normal-enum values compare through retained Body IR identities",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1154; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_source_local_fieldless_enum_values_through_a_direct_callable; comparison remains non-green until #1154 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_015_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "fieldless_enum_values",
                arguments: replacement_body_v0_015_arguments,
                expected: replacement_body_v0_015_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-016",
            title: "Source-local nominal and fieldless-enum patterns dispatch through retained Body IR identities",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1154; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_identity_selected_nominal_and_fieldless_enum_match_patterns; comparison remains non-green until #1154 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_016_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "direct_patterns",
                arguments: replacement_body_v0_016_arguments,
                expected: replacement_body_v0_016_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-017",
            title: "Intrinsic Result construction, same-error propagation, and pattern dispatch execute through Body IR",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1154; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_same_error_result_routing_and_pattern_dispatch; comparison remains non-green until #1154 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_017_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "direct_result_routing",
                arguments: replacement_body_v0_017_arguments,
                expected: replacement_body_v0_017_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-018",
            title: "Source-local async await executes through direct Body-IR task frames",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1155; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_a_source_local_async_task_and_binds_its_lifecycle_evidence; comparison remains non-green until #1155 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_018_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "direct_async_await",
                arguments: replacement_body_v0_018_arguments,
                expected: replacement_body_v0_018_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-019",
            title: "Source-order ready ties execute through direct Body-IR race task frames",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1155; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_source_order_async_race_ties_with_loser_cancellation; comparison remains non-green until #1155 produces paired source-observable evidence through #1146's completed route",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_019_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "source_order_race",
                arguments: replacement_body_v0_019_arguments,
                expected: replacement_body_v0_019_expected,
                shadow_comparison: false,
            }),
        },
        ParityCase {
            id: HASHED_SHADOW_CASE_ID,
            title: "Hashed scalar-key set and dictionary membership agrees across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1247; loaves/compiler/incan_driver/tests/replacement_hashed_shadow_tests.rs::hashed_membership_matches_the_receipt_backed_native_route; all four key kinds and membership helpers, typed-empty constructors, exact stdout and a separate boolean result",
            disposition: Disposition::Preserved,
            source: HASHED_MEMBERSHIP_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "membership",
                arguments: Vec::new,
                expected: || ReplacementValue::Bool(true),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: STRING_HELPER_SHADOW_CASE_ID,
            title: "Canonical selected string helpers agree across independent routes",
            category: BehaviorCategory::StdlibRuntimeBehavior,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1256; loaves/compiler/incan_driver/tests/replacement_string_helper_shadow_tests.rs::selected_string_helpers_match_the_receipt_backed_native_route; seven retained helper identities, shared Unicode and separator behavior, exact stdout and a separate boolean result",
            disposition: Disposition::Preserved,
            source: STRING_HELPER_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "string_helpers",
                arguments: Vec::new,
                expected: || ReplacementValue::Bool(true),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: "replacement-body-v0-022",
            title: "Checked scalar conversions preserve typed results and program output through both routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; #1372 (a `float` renders as Python spells it through `incan_lang::numeric_strings::float_to_string` on both routes); loaves/compiler/incan_driver/tests/replacement_scalar_conversion_tests.rs::replacement_executes_checked_unary_scalar_conversions; loaves/compiler/incan_driver/tests/replacement_scalar_conversion_shadow_tests.rs::scalar_conversion_failure_keeps_its_canonical_class_before_legacy_substring_heuristics",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_022_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "scalar_conversions",
                arguments: replacement_body_v0_022_arguments,
                expected: replacement_body_v0_022_expected,
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: ENUMERATE_ZIP_SHADOW_CASE_ID,
            title: "Canonical stored Enumerate and direct Zip preserve source order through both routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; loaves/compiler/incan_driver/tests/fixtures/replacement/enumerate_zip.incn; \
                       loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::the_enumerate_zip_row_carries_two_route_receipts_and_exact_output",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_023_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "enumerate_zip_profile",
                arguments: replacement_body_v0_023_arguments,
                expected: replacement_body_v0_023_expected,
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: STRING_LEN_SHADOW_CASE_ID,
            title: "Global and method string length agree on Unicode-scalar semantics across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; loaves/compiler/incan_driver/tests/replacement_string_len_shadow_tests.rs::string_len_matches_the_receipt_backed_native_route; global builtin and checked method-helper identities, five Unicode rows, exact stdout and a separate boolean result",
            disposition: Disposition::Preserved,
            source: STRING_LEN_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "string_len",
                arguments: Vec::new,
                expected: || ReplacementValue::Bool(true),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: JSON_STRINGIFY_SHADOW_CASE_ID,
            title: "Scalar JSON stringification agrees across independent routes",
            category: BehaviorCategory::StdlibRuntimeBehavior,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; src/backend/shadow/json_stringify_tests.rs::scalar_json_stringify_matches_the_receipt_backed_native_route; int/bool/str/None exact bytes, empty streams, and independent route receipts",
            disposition: Disposition::Preserved,
            source: JSON_STRINGIFY_SCALARS_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "observe",
                arguments: Vec::new,
                expected: replacement_body_v0_025_expected,
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: COLLECTION_LEN_SHADOW_CASE_ID,
            title: "Hashed set and dict length returns duplicate-normalized entry counts across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; loaves/compiler/incan_driver/tests/replacement_collection_len_shadow_tests.rs::collection_len_matches_the_receipt_backed_native_route; canonical builtin identity, populated/duplicate/typed-empty counts, exact stdout and a separate integer result",
            disposition: Disposition::Preserved,
            source: COLLECTION_LEN_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "collection_len",
                arguments: Vec::new,
                expected: || ReplacementValue::Int(2200),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: BOOL_TRUTHINESS_SHADOW_CASE_ID,
            title: "Canonical bool preserves bounded scalar and container truthiness across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; loaves/compiler/incan_driver/tests/replacement_bool_truthiness_shadow_tests.rs::bool_truthiness_matches_the_receipt_backed_native_route; canonical builtin identity, empty/nonempty scalar and container behavior, exact stdout and a separate boolean result",
            disposition: Disposition::Preserved,
            source: BOOL_TRUTHINESS_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "bool_truthiness",
                arguments: Vec::new,
                expected: || ReplacementValue::Bool(true),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: SORTED_INT_LIST_SHADOW_CASE_ID,
            title: "Canonical sorted preserves a fresh ascending nonempty integer list across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1249; loaves/compiler/incan_driver/tests/replacement_sorted_int_list_shadow_tests.rs::sorted_int_list_matches_the_receipt_backed_native_route; canonical builtin identity, negative/duplicate ordering, source-list preservation, exact stdout and a separate integer result",
            disposition: Disposition::Preserved,
            source: SORTED_INT_LIST_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "sorted_int_list",
                arguments: Vec::new,
                expected: || ReplacementValue::Int(29_320_233),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: TYPED_NUMERIC_SHADOW_CASE_ID,
            title: "Exact-width and decimal carriers preserve checked values across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1279; loaves/compiler/incan_driver/tests/replacement_typed_numeric_tests.rs; loaves/compiler/incan_driver/tests/replacement_scalar_conversion_shadow_tests.rs; representative u8/i128/u128 endpoints, f32 rounding, decimal scale, exact stdout, typed cast edges, and an f32 result",
            disposition: Disposition::Preserved,
            source: REPLACEMENT_BODY_V0_029_SRC,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "typed_numeric_profile",
                arguments: Vec::new,
                expected: replacement_body_v0_029_expected,
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: ISINSTANCE_TARGETS_SHADOW_CASE_ID,
            title: "Checked primitive isinstance targets preserve true and false union narrowing across independent routes",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1281; loaves/compiler/incan_driver/tests/replacement_isinstance_shadow_tests.rs::checked_isinstance_targets_match_the_receipt_backed_native_route; retained compiler-owned target type/span, int/bool/str/float targets, true/false union branches, exact stdout/stderr and a separate boolean result; closed #1154 delivered the current direct nominal/value substrate and open #988 owns broader replacement execution",
            disposition: Disposition::Preserved,
            source: ISINSTANCE_TARGETS_SOURCE,
            evaluate: None,
            identity_conformance: None,
            replacement_execution: Some(parity_corpus::ReplacementExecutionPlan {
                function: "isinstance_targets",
                arguments: Vec::new,
                expected: || ReplacementValue::Bool(true),
                shadow_comparison: true,
            }),
        },
        ParityCase {
            id: "parity-987-1156-provider-allowed",
            title: "An allowed provider operation executes and its backend receipt references the RFC 104 receipt",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1156; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_provider_allowed_invocation; src/backend/replacement/provider.rs",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1156,
                migration_note: "New at cutover rather than preserved: the legacy backend cannot execute a \
                                  provider-service operation at all, so this is a deliberate migration from \
                                  \"refuse\" to \"execute under an RFC 104 authority decision\". The observable \
                                  contract is the provider's own result plus an operation receipt the backend \
                                  execution receipt references; generated Rust is not the contract. Comparison \
                                  stays non-green until #1146 supplies a receipt-bound paired comparison, because \
                                  there is no second route that can run this operation.",
            },
            source: PROVIDER_CASE_SRC,
            evaluate: Some(case_provider_allowed_invocation),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-1156-provider-denied",
            title: "A governed denial emits a denied receipt and never reaches the provider",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1156; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_provider_governed_denial; src/backend/replacement/provider.rs",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1156,
                migration_note: "New at cutover: a governed run refuses an ungranted capability before the \
                                  provider is reached, reports the refusal at the invocation's own source span, \
                                  and still records the denial as a receipt. Migration guidance: the denial is a \
                                  first-class recorded outcome, not an absence of one, so a consumer must read the \
                                  receipt rather than infer refusal from a missing result. Comparison stays \
                                  non-green until #1146.",
            },
            source: PROVIDER_CASE_SRC,
            evaluate: Some(case_provider_governed_denial),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-1156-provider-failed",
            title: "A provider failure keeps its allowing authority decision and reports its own diagnostic",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1156; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_provider_operation_failure; src/backend/replacement/provider.rs",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1156,
                migration_note: "New at cutover: authority was granted and the operation itself failed, which is \
                                  a different outcome from a denial and carries a different diagnostic code. \
                                  Migration guidance: a consumer must not collapse the two, because only one of \
                                  them is fixed by granting a capability. Comparison stays non-green until #1146.",
            },
            source: PROVIDER_CASE_SRC,
            evaluate: Some(case_provider_operation_failure),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-1156-provider-redacted",
            title: "A withheld provider attribute classifies its receipt as redacted without changing the result",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1156; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_provider_redaction_classification; src/backend/replacement/provider.rs",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1156,
                migration_note: "New at cutover: the publishing host decides redaction and the receipt records \
                                  the classification, so a withheld value keeps its key and sensitivity while its \
                                  value never reaches a sink. Migration guidance: redaction has exactly one owner, \
                                  and the backend must not re-derive it from the value later. Comparison stays \
                                  non-green until #1146.",
            },
            source: PROVIDER_CASE_SRC,
            evaluate: Some(case_provider_redaction_classification),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-1156-provider-cleanup",
            title: "An invocation that failed still releases what it acquired, exactly once",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "#1156; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::case_provider_lifecycle_cleanup; src/backend/replacement/provider.rs",
            disposition: Disposition::IntentionalMigration {
                owning_issue: 1156,
                migration_note: "New at cutover: cleanup is unconditional for an invocation that started, and \
                                  never runs for one that was denied or refused before it started. Migration \
                                  guidance: the lifecycle vocabulary is the contract a consumer reads, not the \
                                  host's internal resource handling. Comparison stays non-green until #1146.",
            },
            source: PROVIDER_CASE_SRC,
            evaluate: Some(case_provider_lifecycle_cleanup),
            identity_conformance: None,
            replacement_execution: None,
        },
        // Materialized package behavior is executable. Signed archive delivery remains owned by #1339/RFC034;
        // these callback observations do not promote the corpus's separate receipt-aware comparison axis.
        ParityCase {
            id: "parity-987-989-package-consumer-call",
            title: "A materialized package dependency executes natively and without linking Rust",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::PackageImportBoundary,
            evidence: "#989; #1339; incan_test_support::package_boundary_probe::observe_package_boundary",
            disposition: Disposition::Preserved,
            source: PACKAGE_CONSUMER_SRC,
            evaluate: Some(case_package_consumer_call_executes),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-989-package-representation-refusal",
            title: "A missing package representation refuses in packaging terms before output or receipt",
            category: BehaviorCategory::DiagnosticBehavior,
            lane: EvidenceLane::PackageImportBoundary,
            evidence: "#989; RFC 123; incan_test_support::package_boundary_probe::observe_package_boundary",
            disposition: Disposition::Preserved,
            source: PACKAGE_CONSUMER_SRC,
            evaluate: Some(case_package_representation_refusal_is_packaging_error),
            identity_conformance: None,
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-120-01-identity-matrix",
            title: "RFC 120 identities survive every semantically valid binding, namespace, and scope cell",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::PackageImportBoundary,
            evidence: "RFC 120 typed Cutover conformance coverage; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::verify_identity_matrix",
            disposition: Disposition::Preserved,
            source: IDENTITY_MATRIX_SRC,
            evaluate: None,
            identity_conformance: Some(IdentityConformancePlan::SourceGraph(SourceIdentityConformancePlan {
                modules: IDENTITY_MATRIX_MODULES,
                root_module: "identity_matrix",
                verify: verify_identity_matrix,
                replacement: IdentityReplacementPlan::Graph {
                    root_module: "identity_matrix",
                    entrypoints: IDENTITY_MATRIX_ENTRYPOINTS,
                    deferred: IDENTITY_MATRIX_DEFERRED,
                },
                comparison_reason: "the checked graph and the cross-module replacement route both executed, but no independent legacy execution was run for a source-observable comparison",
            })),
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-120-02-let-shadow",
            title: "Explicit let shadowing preserves distinct checked and replacement local identities",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "RFC 120 Cutover conformance; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::verify_let_shadow; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_let_shadowing_by_local_identity",
            disposition: Disposition::Preserved,
            source: LET_SHADOW_SRC,
            evaluate: None,
            identity_conformance: Some(IdentityConformancePlan::SourceGraph(SourceIdentityConformancePlan {
                modules: LET_SHADOW_MODULES,
                root_module: "identity_let_shadow",
                verify: verify_let_shadow,
                replacement: IdentityReplacementPlan::Direct {
                    module: "identity_let_shadow",
                    function: "shadow_let",
                    arguments: no_replacement_arguments,
                    expected: expected_three,
                },
                comparison_reason: "the checked graph and replacement route executed, but no independent legacy execution was run for a source-observable comparison",
            })),
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-120-03-mut-shadow",
            title: "Explicit mut shadowing preserves distinct checked and replacement local identities",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "RFC 120 Cutover conformance; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::verify_mut_shadow; loaves/compiler/incan_driver/tests/replacement_backend_execution_tests.rs::replacement_executes_mut_shadowing_by_local_identity",
            disposition: Disposition::Preserved,
            source: MUT_SHADOW_SRC,
            evaluate: None,
            identity_conformance: Some(IdentityConformancePlan::SourceGraph(SourceIdentityConformancePlan {
                modules: MUT_SHADOW_MODULES,
                root_module: "identity_mut_shadow",
                verify: verify_mut_shadow,
                replacement: IdentityReplacementPlan::Direct {
                    module: "identity_mut_shadow",
                    function: "shadow_mut",
                    arguments: no_replacement_arguments,
                    expected: expected_eleven,
                },
                comparison_reason: "the checked graph and replacement route executed, but no independent legacy execution was run for a source-observable comparison",
            })),
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-120-04-generic-binder",
            title: "Generic binders and their callable target retain distinct canonical identities",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "RFC 120 Cutover conformance; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::verify_generic_binder",
            disposition: Disposition::Preserved,
            source: GENERIC_BINDER_SRC,
            evaluate: None,
            identity_conformance: Some(IdentityConformancePlan::SourceGraph(SourceIdentityConformancePlan {
                modules: GENERIC_BINDER_MODULES,
                root_module: "identity_generic",
                verify: verify_generic_binder,
                replacement: IdentityReplacementPlan::Direct {
                    module: "identity_generic",
                    function: "generic_entry",
                    arguments: no_replacement_arguments,
                    expected: expected_forty_two,
                },
                comparison_reason: "the checked graph and replacement route executed, but no independent legacy execution was run for a source-observable comparison",
            })),
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-120-05-builtin-rebinding",
            title: "Ordinary builtin-name rebinding stays distinct from explicit std.builtins lookup",
            category: BehaviorCategory::SupportedLanguageContract,
            lane: EvidenceLane::DirectReplacementBodyIr,
            evidence: "RFC 120 Cutover conformance; loaves/compiler/incan_driver/tests/parity_corpus_tests.rs::verify_builtin_rebinding",
            disposition: Disposition::Preserved,
            source: BUILTIN_REBINDING_SRC,
            evaluate: None,
            identity_conformance: Some(IdentityConformancePlan::SourceGraph(SourceIdentityConformancePlan {
                modules: BUILTIN_REBINDING_MODULES,
                root_module: "identity_builtin",
                verify: verify_builtin_rebinding,
                replacement: IdentityReplacementPlan::Direct {
                    module: "identity_builtin",
                    function: "builtin_entry",
                    arguments: no_replacement_arguments,
                    expected: expected_eight,
                },
                comparison_reason: "the checked graph and replacement route executed, but no independent legacy execution was run for a source-observable comparison",
            })),
            replacement_execution: None,
        },
        ParityCase {
            id: "parity-987-120-06-release-artifact",
            title: "Pinned release artifacts recover four Incan identity categories and reject host frames",
            category: BehaviorCategory::GeneratedArtifactBehavior,
            lane: EvidenceLane::GeneratedProjectRun,
            evidence: "RFC 120 Cutover conformance; incan_test_support::emitted_symbol_artifact::verify_pinned_release_artifact",
            disposition: Disposition::Preserved,
            source: "RFC 120 pinned Rust 1.98.0 release artifact",
            evaluate: None,
            identity_conformance: Some(IdentityConformancePlan::ReleaseArtifact {
                verify: verify_release_artifact,
                comparison_reason: "the optimized artifact was built and its symbol table inspected, but no source-observable backend execution comparison was run",
            }),
            replacement_execution: None,
        },
    ]
}
