[package]
name = "incan_format"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "The Incan source formatter"

[lib]
name = "incan_format"
path = "src/lib.rs"

[dependencies]
incan_core = { path = "../../../crates/incan_core" }
incan_semantics_core = { path = "../../../crates/incan_semantics_core" }
incan_syntax = { path = "../../../crates/incan_syntax" }
incan_vocab = { path = "../../../crates/incan_vocab" }
thiserror = { workspace = true }
